/* Generated By:JavaCC: Do not edit this line. ParserTokenManager.java */
// Files created by javacc :-
//
//    ParseException.java
//    Parser.java
//    ParserConstants.java
//    ParserTokenManager.java
//    SimpleCharStream.java
//    Token.java
//    TokenMgrError.java
//
// Some of these files must be "massaged" after javacc has run - see the
// scripts in ../../scripts directory.

package threepl.parser;
import java.io.*;
import java.util.*;
import java.util.concurrent.*;
import java.text.*;
import static threepl.ThreePL.*;
import threepl.ThreePL;
import threepl.nodes.*;
import threepl.exec.*;
import threepl.exec.Module;
import threepl.mods.*;
import threepl.procs.*;
import threepl.funcs.*;
import threepl.codegen.*;
import threepl.exceptions.*;

/** Token Manager. */
public class ParserTokenManager implements ParserConstants
{

  /** Debug output. */
  public static  java.io.PrintStream debugStream = System.out;
  /** Set debug output. */
  public static  void setDebugStream(java.io.PrintStream ds) { debugStream = ds; }
private static final int jjStopStringLiteralDfa_0(int pos, long active0, long active1)
{
   switch (pos)
   {
      case 0:
         if ((active0 & 0x1a00000000L) != 0L)
         {
            jjmatchedKind = 121;
            return 26;
         }
         if ((active1 & 0x100100000000000L) != 0L)
            return 4;
         if ((active0 & 0x40000000000000L) != 0L)
         {
            jjmatchedKind = 121;
            return 22;
         }
         if ((active0 & 0x1fbfffe5ff800000L) != 0L)
         {
            jjmatchedKind = 121;
            return 29;
         }
         return -1;
      case 1:
         if ((active0 & 0x40000000000000L) != 0L)
         {
            if (jjmatchedPos != 1)
            {
               jjmatchedKind = 121;
               jjmatchedPos = 1;
            }
            return 21;
         }
         if ((active0 & 0x1fbfff7eff800000L) != 0L)
         {
            if (jjmatchedPos != 1)
            {
               jjmatchedKind = 121;
               jjmatchedPos = 1;
            }
            return 29;
         }
         if ((active0 & 0x8100000000L) != 0L)
            return 29;
         return -1;
      case 2:
         if ((active0 & 0x1ff7df76ff800000L) != 0L)
         {
            jjmatchedKind = 121;
            jjmatchedPos = 2;
            return 29;
         }
         if ((active0 & 0x8200800000000L) != 0L)
            return 29;
         return -1;
      case 3:
         if ((active0 & 0x17d7cf72fb800000L) != 0L)
         {
            jjmatchedKind = 121;
            jjmatchedPos = 3;
            return 29;
         }
         if ((active0 & 0x820100404000000L) != 0L)
            return 29;
         return -1;
      case 4:
         if ((active0 & 0x7d7cf70e2800000L) != 0L)
         {
            if (jjmatchedPos != 4)
            {
               jjmatchedKind = 121;
               jjmatchedPos = 4;
            }
            return 29;
         }
         if ((active0 & 0x1000000019000000L) != 0L)
            return 29;
         return -1;
      case 5:
         if ((active0 & 0x743c310c2000000L) != 0L)
         {
            if (jjmatchedPos != 5)
            {
               jjmatchedKind = 121;
               jjmatchedPos = 5;
            }
            return 29;
         }
         if ((active0 & 0x94086020800000L) != 0L)
            return 29;
         return -1;
      case 6:
         if ((active0 & 0x43421042000000L) != 0L)
         {
            if (jjmatchedPos != 6)
            {
               jjmatchedKind = 121;
               jjmatchedPos = 6;
            }
            return 29;
         }
         if ((active0 & 0x700810080000000L) != 0L)
            return 29;
         return -1;
      case 7:
         if ((active0 & 0x443020000000000L) != 0L)
         {
            jjmatchedKind = 121;
            jjmatchedPos = 7;
            return 29;
         }
         if ((active0 & 0x401040000000L) != 0L)
            return 29;
         return -1;
      case 8:
         if ((active0 & 0x442020000000000L) != 0L)
         {
            jjmatchedKind = 121;
            jjmatchedPos = 8;
            return 29;
         }
         if ((active0 & 0x1000000000000L) != 0L)
            return 29;
         return -1;
      case 9:
         if ((active0 & 0x440020000000000L) != 0L)
         {
            jjmatchedKind = 121;
            jjmatchedPos = 9;
            return 29;
         }
         if ((active0 & 0x2000000000000L) != 0L)
            return 29;
         return -1;
      case 10:
         if ((active0 & 0x40020000000000L) != 0L)
         {
            jjmatchedKind = 121;
            jjmatchedPos = 10;
            return 29;
         }
         if ((active0 & 0x400000000000000L) != 0L)
            return 29;
         return -1;
      case 11:
         if ((active0 & 0x20000000000L) != 0L)
            return 29;
         if ((active0 & 0x40000000000000L) != 0L)
         {
            jjmatchedKind = 121;
            jjmatchedPos = 11;
            return 29;
         }
         return -1;
      default :
         return -1;
   }
}
private static final int jjStartNfa_0(int pos, long active0, long active1)
{
   return jjMoveNfa_0(jjStopStringLiteralDfa_0(pos, active0, active1), pos + 1);
}
static private int jjStopAtPos(int pos, int kind)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   return pos + 1;
}
static private int jjMoveStringLiteralDfa0_0()
{
   switch(curChar)
   {
      case 10:
         return jjStopAtPos(0, 1);
      case 33:
         jjmatchedKind = 99;
         return jjMoveStringLiteralDfa1_0(0x0L, 0x200000L);
      case 37:
         jjmatchedKind = 92;
         return jjMoveStringLiteralDfa1_0(0x0L, 0x4L);
      case 38:
         jjmatchedKind = 98;
         return jjMoveStringLiteralDfa1_0(0x0L, 0x80000048L);
      case 40:
         return jjStopAtPos(0, 113);
      case 41:
         return jjStopAtPos(0, 114);
      case 42:
         jjmatchedKind = 90;
         return jjMoveStringLiteralDfa1_0(0x0L, 0x80001L);
      case 43:
         jjmatchedKind = 88;
         return jjMoveStringLiteralDfa1_0(0x4000000000000000L, 0x40000020000L);
      case 44:
         return jjStopAtPos(0, 117);
      case 45:
         jjmatchedKind = 89;
         return jjMoveStringLiteralDfa1_0(0x8000000000000000L, 0x80000041800L);
      case 46:
         jjmatchedKind = 120;
         return jjMoveStringLiteralDfa1_0(0x0L, 0x100000000000L);
      case 47:
         jjmatchedKind = 91;
         return jjMoveStringLiteralDfa1_0(0x30L, 0x2L);
      case 58:
         jjmatchedKind = 119;
         return jjMoveStringLiteralDfa1_0(0x0L, 0x2000L);
      case 59:
         return jjStopAtPos(0, 118);
      case 60:
         jjmatchedKind = 115;
         return jjMoveStringLiteralDfa1_0(0x0L, 0x4000418200L);
      case 61:
         jjmatchedKind = 61;
         return jjMoveStringLiteralDfa1_0(0x0L, 0x100000L);
      case 62:
         jjmatchedKind = 116;
         return jjMoveStringLiteralDfa1_0(0x0L, 0x28000800400L);
      case 63:
         return jjStopAtPos(0, 101);
      case 91:
         return jjStopAtPos(0, 111);
      case 93:
         return jjStopAtPos(0, 112);
      case 94:
         jjmatchedKind = 97;
         return jjMoveStringLiteralDfa1_0(0x0L, 0x10040000120L);
      case 98:
         return jjMoveStringLiteralDfa1_0(0x1800000L, 0x0L);
      case 99:
         return jjMoveStringLiteralDfa1_0(0x7e000000L, 0x0L);
      case 100:
         return jjMoveStringLiteralDfa1_0(0x180000000L, 0x0L);
      case 101:
         return jjMoveStringLiteralDfa1_0(0x400000000L, 0x0L);
      case 102:
         return jjMoveStringLiteralDfa1_0(0x1a00000000L, 0x0L);
      case 103:
         return jjMoveStringLiteralDfa1_0(0x6000000000L, 0x0L);
      case 105:
         return jjMoveStringLiteralDfa1_0(0x18000000000L, 0x0L);
      case 108:
         return jjMoveStringLiteralDfa1_0(0x60000000000L, 0x0L);
      case 109:
         return jjMoveStringLiteralDfa1_0(0x80000000000L, 0x0L);
      case 110:
         return jjMoveStringLiteralDfa1_0(0x100000000000L, 0x0L);
      case 112:
         return jjMoveStringLiteralDfa1_0(0x3e00000000000L, 0x0L);
      case 114:
         return jjMoveStringLiteralDfa1_0(0x4000000000000L, 0x0L);
      case 115:
         return jjMoveStringLiteralDfa1_0(0x38000000000000L, 0x0L);
      case 116:
         return jjMoveStringLiteralDfa1_0(0x40000000000000L, 0x0L);
      case 117:
         return jjMoveStringLiteralDfa1_0(0x80000000000000L, 0x0L);
      case 118:
         return jjMoveStringLiteralDfa1_0(0x100000000000000L, 0x0L);
      case 119:
         return jjMoveStringLiteralDfa1_0(0x1e00000000000000L, 0x0L);
      case 123:
         return jjStopAtPos(0, 109);
      case 124:
         jjmatchedKind = 96;
         return jjMoveStringLiteralDfa1_0(0x0L, 0x20004090L);
      case 125:
         return jjStopAtPos(0, 110);
      case 126:
         return jjStopAtPos(0, 100);
      default :
         return jjMoveNfa_0(0, 0);
   }
}
static private int jjMoveStringLiteralDfa1_0(long active0, long active1)
{
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(0, active0, active1);
      return 1;
   }
   switch(curChar)
   {
      case 38:
         if ((active1 & 0x80000000L) != 0L)
         {
            jjmatchedKind = 95;
            jjmatchedPos = 1;
         }
         return jjMoveStringLiteralDfa2_0(active0, 0L, active1, 0x40L);
      case 42:
         if ((active0 & 0x20L) != 0L)
            return jjStopAtPos(1, 5);
         break;
      case 43:
         if ((active1 & 0x40000000000L) != 0L)
            return jjStopAtPos(1, 106);
         break;
      case 45:
         if ((active1 & 0x4000L) != 0L)
            return jjStopAtPos(1, 78);
         else if ((active1 & 0x10000L) != 0L)
            return jjStopAtPos(1, 80);
         else if ((active1 & 0x80000000000L) != 0L)
            return jjStopAtPos(1, 107);
         break;
      case 46:
         if ((active1 & 0x100000000000L) != 0L)
            return jjStopAtPos(1, 108);
         break;
      case 47:
         if ((active0 & 0x10L) != 0L)
            return jjStopAtPos(1, 4);
         break;
      case 60:
         if ((active1 & 0x4000000000L) != 0L)
         {
            jjmatchedKind = 102;
            jjmatchedPos = 1;
         }
         return jjMoveStringLiteralDfa2_0(active0, 0L, active1, 0x100000e8200L);
      case 61:
         if ((active0 & 0x4000000000000000L) != 0L)
            return jjStopAtPos(1, 62);
         else if ((active0 & 0x8000000000000000L) != 0L)
            return jjStopAtPos(1, 63);
         else if ((active1 & 0x1L) != 0L)
            return jjStopAtPos(1, 64);
         else if ((active1 & 0x2L) != 0L)
            return jjStopAtPos(1, 65);
         else if ((active1 & 0x4L) != 0L)
            return jjStopAtPos(1, 66);
         else if ((active1 & 0x8L) != 0L)
            return jjStopAtPos(1, 67);
         else if ((active1 & 0x10L) != 0L)
            return jjStopAtPos(1, 68);
         else if ((active1 & 0x20L) != 0L)
            return jjStopAtPos(1, 69);
         else if ((active1 & 0x2000L) != 0L)
            return jjStopAtPos(1, 77);
         else if ((active1 & 0x100000L) != 0L)
            return jjStopAtPos(1, 84);
         else if ((active1 & 0x200000L) != 0L)
            return jjStopAtPos(1, 85);
         else if ((active1 & 0x400000L) != 0L)
            return jjStopAtPos(1, 86);
         else if ((active1 & 0x800000L) != 0L)
            return jjStopAtPos(1, 87);
         break;
      case 62:
         if ((active1 & 0x1000L) != 0L)
         {
            jjmatchedKind = 76;
            jjmatchedPos = 1;
         }
         else if ((active1 & 0x8000000000L) != 0L)
         {
            jjmatchedKind = 103;
            jjmatchedPos = 1;
         }
         return jjMoveStringLiteralDfa2_0(active0, 0L, active1, 0x20000000c00L);
      case 94:
         if ((active1 & 0x40000000L) != 0L)
         {
            jjmatchedKind = 94;
            jjmatchedPos = 1;
         }
         return jjMoveStringLiteralDfa2_0(active0, 0L, active1, 0x100L);
      case 97:
         return jjMoveStringLiteralDfa2_0(active0, 0x700200006000000L, active1, 0L);
      case 101:
         return jjMoveStringLiteralDfa2_0(active0, 0xc420080000000L, active1, 0L);
      case 102:
         if ((active0 & 0x8000000000L) != 0L)
            return jjStartNfaWithStates_0(1, 39, 29);
         break;
      case 104:
         return jjMoveStringLiteralDfa2_0(active0, 0x1800000000000000L, active1, 0L);
      case 105:
         return jjMoveStringLiteralDfa2_0(active0, 0x200000000L, active1, 0L);
      case 108:
         return jjMoveStringLiteralDfa2_0(active0, 0x6418000000L, active1, 0L);
      case 110:
         return jjMoveStringLiteralDfa2_0(active0, 0x80010000000000L, active1, 0L);
      case 111:
         if ((active0 & 0x100000000L) != 0L)
            return jjStartNfaWithStates_0(1, 32, 29);
         return jjMoveStringLiteralDfa2_0(active0, 0x20c0860000000L, active1, 0L);
      case 114:
         return jjMoveStringLiteralDfa2_0(active0, 0x41800001800000L, active1, 0L);
      case 117:
         return jjMoveStringLiteralDfa2_0(active0, 0x101000000000L, active1, 0L);
      case 119:
         return jjMoveStringLiteralDfa2_0(active0, 0x10000000000000L, active1, 0L);
      case 121:
         return jjMoveStringLiteralDfa2_0(active0, 0x20000000000000L, active1, 0L);
      case 124:
         if ((active1 & 0x20000000L) != 0L)
         {
            jjmatchedKind = 93;
            jjmatchedPos = 1;
         }
         return jjMoveStringLiteralDfa2_0(active0, 0L, active1, 0x80L);
      default :
         break;
   }
   return jjStartNfa_0(0, active0, active1);
}
static private int jjMoveStringLiteralDfa2_0(long old0, long active0, long old1, long active1)
{
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(0, old0, old1);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(1, active0, active1);
      return 2;
   }
   switch(curChar)
   {
      case 45:
         if ((active1 & 0x8000L) != 0L)
            return jjStopAtPos(2, 79);
         else if ((active1 & 0x20000L) != 0L)
            return jjStopAtPos(2, 81);
         else if ((active1 & 0x40000L) != 0L)
            return jjStopAtPos(2, 82);
         else if ((active1 & 0x80000L) != 0L)
            return jjStopAtPos(2, 83);
         break;
      case 60:
         if ((active1 & 0x10000000000L) != 0L)
            return jjStopAtPos(2, 104);
         break;
      case 61:
         if ((active1 & 0x40L) != 0L)
            return jjStopAtPos(2, 70);
         else if ((active1 & 0x80L) != 0L)
            return jjStopAtPos(2, 71);
         else if ((active1 & 0x100L) != 0L)
            return jjStopAtPos(2, 72);
         else if ((active1 & 0x200L) != 0L)
            return jjStopAtPos(2, 73);
         else if ((active1 & 0x400L) != 0L)
            return jjStopAtPos(2, 74);
         break;
      case 62:
         if ((active1 & 0x800L) != 0L)
            return jjStopAtPos(2, 75);
         break;
      case 94:
         if ((active1 & 0x20000000000L) != 0L)
            return jjStopAtPos(2, 105);
         break;
      case 97:
         return jjMoveStringLiteralDfa3_0(active0, 0x40020018800000L, active1, 0L);
      case 99:
         return jjMoveStringLiteralDfa3_0(active0, 0x40000000000L, active1, 0L);
      case 100:
         return jjMoveStringLiteralDfa3_0(active0, 0x80000000000L, active1, 0L);
      case 101:
         return jjMoveStringLiteralDfa3_0(active0, 0x800000001000000L, active1, 0L);
      case 102:
         return jjMoveStringLiteralDfa3_0(active0, 0x80000000L, active1, 0L);
      case 105:
         return jjMoveStringLiteralDfa3_0(active0, 0x1610810000000000L, active1, 0L);
      case 108:
         return jjMoveStringLiteralDfa3_0(active0, 0x80100202000000L, active1, 0L);
      case 109:
         return jjMoveStringLiteralDfa3_0(active0, 0x20000000L, active1, 0L);
      case 110:
         return jjMoveStringLiteralDfa3_0(active0, 0x20001040000000L, active1, 0L);
      case 111:
         return jjMoveStringLiteralDfa3_0(active0, 0x1006000000000L, active1, 0L);
      case 113:
         if ((active0 & 0x8000000000000L) != 0L)
            return jjStartNfaWithStates_0(2, 51, 29);
         break;
      case 114:
         if ((active0 & 0x800000000L) != 0L)
            return jjStartNfaWithStates_0(2, 35, 29);
         else if ((active0 & 0x200000000000L) != 0L)
            return jjStartNfaWithStates_0(2, 45, 29);
         return jjMoveStringLiteralDfa3_0(active0, 0x100000000000000L, active1, 0L);
      case 115:
         return jjMoveStringLiteralDfa3_0(active0, 0x2000404000000L, active1, 0L);
      case 116:
         return jjMoveStringLiteralDfa3_0(active0, 0x4400000000000L, active1, 0L);
      default :
         break;
   }
   return jjStartNfa_0(1, active0, active1);
}
static private int jjMoveStringLiteralDfa3_0(long old0, long active0, long old1, long active1)
{
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(1, old0, old1);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(2, active0, 0L);
      return 3;
   }
   switch(curChar)
   {
      case 97:
         return jjMoveStringLiteralDfa4_0(active0, 0x100040081000000L);
      case 98:
         return jjMoveStringLiteralDfa4_0(active0, 0x6000000000L);
      case 99:
         if ((active0 & 0x20000000000000L) != 0L)
            return jjStartNfaWithStates_0(3, 53, 29);
         return jjMoveStringLiteralDfa4_0(active0, 0x1001000000000L);
      case 100:
         return jjMoveStringLiteralDfa4_0(active0, 0x20000000000L);
      case 101:
         if ((active0 & 0x4000000L) != 0L)
            return jjStartNfaWithStates_0(3, 26, 29);
         else if ((active0 & 0x400000000L) != 0L)
            return jjStartNfaWithStates_0(3, 34, 29);
         return jjMoveStringLiteralDfa4_0(active0, 0x80000200000000L);
      case 105:
         return jjMoveStringLiteralDfa4_0(active0, 0x40000000000000L);
      case 108:
         if ((active0 & 0x100000000000L) != 0L)
            return jjStartNfaWithStates_0(3, 44, 29);
         return jjMoveStringLiteralDfa4_0(active0, 0x1000000002000000L);
      case 109:
         return jjMoveStringLiteralDfa4_0(active0, 0x20000000L);
      case 110:
         if ((active0 & 0x800000000000000L) != 0L)
            return jjStartNfaWithStates_0(3, 59, 29);
         return jjMoveStringLiteralDfa4_0(active0, 0x800000L);
      case 114:
         return jjMoveStringLiteralDfa4_0(active0, 0x400000000000L);
      case 115:
         return jjMoveStringLiteralDfa4_0(active0, 0x18000000L);
      case 116:
         return jjMoveStringLiteralDfa4_0(active0, 0x612010040000000L);
      case 117:
         return jjMoveStringLiteralDfa4_0(active0, 0x4080000000000L);
      case 118:
         return jjMoveStringLiteralDfa4_0(active0, 0x800000000000L);
      default :
         break;
   }
   return jjStartNfa_0(2, active0, 0L);
}
static private int jjMoveStringLiteralDfa4_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(2, old0, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(3, active0, 0L);
      return 4;
   }
   switch(curChar)
   {
      case 46:
         if ((active0 & 0x200000000L) != 0L)
            return jjStopAtPos(4, 33);
         break;
      case 97:
         return jjMoveStringLiteralDfa5_0(active0, 0x806000000000L);
      case 99:
         return jjMoveStringLiteralDfa5_0(active0, 0x10000000800000L);
      case 101:
         if ((active0 & 0x1000000000000000L) != 0L)
            return jjStartNfaWithStates_0(4, 60, 29);
         return jjMoveStringLiteralDfa5_0(active0, 0x1020000000000L);
      case 105:
         return jjMoveStringLiteralDfa5_0(active0, 0x410042000000L);
      case 107:
         if ((active0 & 0x1000000L) != 0L)
            return jjStartNfaWithStates_0(4, 24, 29);
         break;
      case 108:
         return jjMoveStringLiteralDfa5_0(active0, 0x400c0000000000L);
      case 109:
         return jjMoveStringLiteralDfa5_0(active0, 0x2000000000000L);
      case 111:
         return jjMoveStringLiteralDfa5_0(active0, 0x20000000L);
      case 112:
         return jjMoveStringLiteralDfa5_0(active0, 0x600000000000000L);
      case 114:
         return jjMoveStringLiteralDfa5_0(active0, 0x104000000000000L);
      case 115:
         if ((active0 & 0x8000000L) != 0L)
         {
            jjmatchedKind = 27;
            jjmatchedPos = 4;
         }
         return jjMoveStringLiteralDfa5_0(active0, 0x80000010000000L);
      case 116:
         return jjMoveStringLiteralDfa5_0(active0, 0x1000000000L);
      case 117:
         return jjMoveStringLiteralDfa5_0(active0, 0x80000000L);
      default :
         break;
   }
   return jjStartNfa_0(3, active0, 0L);
}
static private int jjMoveStringLiteralDfa5_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(3, old0, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(4, active0, 0L);
      return 5;
   }
   switch(curChar)
   {
      case 46:
         if ((active0 & 0x10000000L) != 0L)
            return jjStopAtPos(5, 28);
         else if ((active0 & 0x40000000000L) != 0L)
            return jjStopAtPos(5, 42);
         break;
      case 97:
         return jjMoveStringLiteralDfa6_0(active0, 0x10000000000L);
      case 100:
         return jjMoveStringLiteralDfa6_0(active0, 0x1000000000000L);
      case 101:
         if ((active0 & 0x80000000000L) != 0L)
            return jjStartNfaWithStates_0(5, 43, 29);
         return jjMoveStringLiteralDfa6_0(active0, 0x40000000000000L);
      case 103:
         return jjMoveStringLiteralDfa6_0(active0, 0x100000000000000L);
      case 104:
         if ((active0 & 0x800000L) != 0L)
            return jjStartNfaWithStates_0(5, 23, 29);
         else if ((active0 & 0x10000000000000L) != 0L)
            return jjStartNfaWithStates_0(5, 52, 29);
         break;
      case 105:
         return jjMoveStringLiteralDfa6_0(active0, 0x1000000000L);
      case 108:
         if ((active0 & 0x2000000000L) != 0L)
         {
            jjmatchedKind = 37;
            jjmatchedPos = 5;
         }
         return jjMoveStringLiteralDfa6_0(active0, 0x4080000000L);
      case 110:
         if ((active0 & 0x20000000L) != 0L)
            return jjStartNfaWithStates_0(5, 29, 29);
         else if ((active0 & 0x4000000000000L) != 0L)
            return jjStartNfaWithStates_0(5, 50, 29);
         return jjMoveStringLiteralDfa6_0(active0, 0x400042000000L);
      case 111:
         return jjMoveStringLiteralDfa6_0(active0, 0x2000000000000L);
      case 114:
         return jjMoveStringLiteralDfa6_0(active0, 0x600020000000000L);
      case 115:
         if ((active0 & 0x80000000000000L) != 0L)
            return jjStartNfaWithStates_0(5, 55, 29);
         break;
      case 116:
         return jjMoveStringLiteralDfa6_0(active0, 0x800000000000L);
      default :
         break;
   }
   return jjStartNfa_0(4, active0, 0L);
}
static private int jjMoveStringLiteralDfa6_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(4, old0, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(5, active0, 0L);
      return 6;
   }
   switch(curChar)
   {
      case 46:
         if ((active0 & 0x4000000000L) != 0L)
            return jjStopAtPos(6, 38);
         break;
      case 100:
         return jjMoveStringLiteralDfa7_0(active0, 0x2000000000000L);
      case 101:
         if ((active0 & 0x800000000000L) != 0L)
            return jjStartNfaWithStates_0(6, 47, 29);
         return jjMoveStringLiteralDfa7_0(active0, 0x400000000000L);
      case 103:
         return jjMoveStringLiteralDfa7_0(active0, 0x2000000L);
      case 105:
         if ((active0 & 0x200000000000000L) != 0L)
         {
            jjmatchedKind = 57;
            jjmatchedPos = 6;
         }
         return jjMoveStringLiteralDfa7_0(active0, 0x400000000000000L);
      case 108:
         if ((active0 & 0x10000000000L) != 0L)
            return jjStartNfaWithStates_0(6, 40, 29);
         break;
      case 109:
         return jjMoveStringLiteralDfa7_0(active0, 0x20000000000L);
      case 111:
         return jjMoveStringLiteralDfa7_0(active0, 0x1000000000L);
      case 114:
         return jjMoveStringLiteralDfa7_0(active0, 0x40000000000000L);
      case 115:
         if ((active0 & 0x100000000000000L) != 0L)
            return jjStartNfaWithStates_0(6, 56, 29);
         break;
      case 116:
         if ((active0 & 0x80000000L) != 0L)
            return jjStartNfaWithStates_0(6, 31, 29);
         break;
      case 117:
         return jjMoveStringLiteralDfa7_0(active0, 0x1000040000000L);
      default :
         break;
   }
   return jjStartNfa_0(5, active0, 0L);
}
static private int jjMoveStringLiteralDfa7_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(5, old0, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(6, active0, 0L);
      return 7;
   }
   switch(curChar)
   {
      case 46:
         if ((active0 & 0x2000000L) != 0L)
            return jjStopAtPos(7, 25);
         break;
      case 101:
         if ((active0 & 0x40000000L) != 0L)
            return jjStartNfaWithStates_0(7, 30, 29);
         break;
      case 108:
         return jjMoveStringLiteralDfa8_0(active0, 0x400000000000000L);
      case 109:
         return jjMoveStringLiteralDfa8_0(active0, 0x40000000000000L);
      case 110:
         if ((active0 & 0x1000000000L) != 0L)
            return jjStartNfaWithStates_0(7, 36, 29);
         break;
      case 111:
         return jjMoveStringLiteralDfa8_0(active0, 0x20000000000L);
      case 114:
         return jjMoveStringLiteralDfa8_0(active0, 0x1000000000000L);
      case 116:
         if ((active0 & 0x400000000000L) != 0L)
            return jjStartNfaWithStates_0(7, 46, 29);
         break;
      case 117:
         return jjMoveStringLiteralDfa8_0(active0, 0x2000000000000L);
      default :
         break;
   }
   return jjStartNfa_0(6, active0, 0L);
}
static private int jjMoveStringLiteralDfa8_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(6, old0, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(7, active0, 0L);
      return 8;
   }
   switch(curChar)
   {
      case 100:
         return jjMoveStringLiteralDfa9_0(active0, 0x20000000000L);
      case 101:
         if ((active0 & 0x1000000000000L) != 0L)
            return jjStartNfaWithStates_0(8, 48, 29);
         break;
      case 108:
         return jjMoveStringLiteralDfa9_0(active0, 0x2000000000000L);
      case 111:
         return jjMoveStringLiteralDfa9_0(active0, 0x440000000000000L);
      default :
         break;
   }
   return jjStartNfa_0(7, active0, 0L);
}
static private int jjMoveStringLiteralDfa9_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(7, old0, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(8, active0, 0L);
      return 9;
   }
   switch(curChar)
   {
      case 99:
         return jjMoveStringLiteralDfa10_0(active0, 0x400000000000000L);
      case 100:
         return jjMoveStringLiteralDfa10_0(active0, 0x40000000000000L);
      case 101:
         if ((active0 & 0x2000000000000L) != 0L)
            return jjStartNfaWithStates_0(9, 49, 29);
         break;
      case 117:
         return jjMoveStringLiteralDfa10_0(active0, 0x20000000000L);
      default :
         break;
   }
   return jjStartNfa_0(8, active0, 0L);
}
static private int jjMoveStringLiteralDfa10_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(8, old0, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(9, active0, 0L);
      return 10;
   }
   switch(curChar)
   {
      case 107:
         if ((active0 & 0x400000000000000L) != 0L)
            return jjStartNfaWithStates_0(10, 58, 29);
         break;
      case 108:
         return jjMoveStringLiteralDfa11_0(active0, 0x20000000000L);
      case 117:
         return jjMoveStringLiteralDfa11_0(active0, 0x40000000000000L);
      default :
         break;
   }
   return jjStartNfa_0(9, active0, 0L);
}
static private int jjMoveStringLiteralDfa11_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(9, old0, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(10, active0, 0L);
      return 11;
   }
   switch(curChar)
   {
      case 101:
         if ((active0 & 0x20000000000L) != 0L)
            return jjStartNfaWithStates_0(11, 41, 29);
         break;
      case 108:
         return jjMoveStringLiteralDfa12_0(active0, 0x40000000000000L);
      default :
         break;
   }
   return jjStartNfa_0(10, active0, 0L);
}
static private int jjMoveStringLiteralDfa12_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(10, old0, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(11, active0, 0L);
      return 12;
   }
   switch(curChar)
   {
      case 101:
         if ((active0 & 0x40000000000000L) != 0L)
            return jjStartNfaWithStates_0(12, 54, 29);
         break;
      default :
         break;
   }
   return jjStartNfa_0(11, active0, 0L);
}
static private int jjStartNfaWithStates_0(int pos, int kind, int state)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) { return pos + 1; }
   return jjMoveNfa_0(state, pos + 1);
}
static final long[] jjbitVec0 = {
   0x0L, 0x0L, 0xffffffffffffffffL, 0xffffffffffffffffL
};
static private int jjMoveNfa_0(int startState, int curPos)
{
   int startsAt = 0;
   jjnewStateCnt = 89;
   int i = 1;
   jjstateSet[0] = startState;
   int kind = 0x7fffffff;
   for (;;)
   {
      if (++jjround == 0x7fffffff)
         ReInitRounds();
      if (curChar < 64)
      {
         long l = 1L << curChar;
         do
         {
            switch(jjstateSet[--i])
            {
               case 26:
               case 29:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 121)
                     kind = 121;
                  jjCheckNAdd(29);
                  break;
               case 22:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 121)
                     kind = 121;
                  jjCheckNAdd(29);
                  break;
               case 0:
                  if ((0x3ff000000000000L & l) != 0L)
                  {
                     if (kind > 19)
                        kind = 19;
                     jjCheckNAddStates(0, 5);
                  }
                  else if ((0x100000200L & l) != 0L)
                  {
                     if (kind > 3)
                        kind = 3;
                  }
                  else if (curChar == 35)
                     jjAddStates(6, 9);
                  else if (curChar == 34)
                     jjCheckNAddStates(10, 12);
                  else if (curChar == 46)
                     jjCheckNAdd(4);
                  if ((0x3fe000000000000L & l) != 0L)
                  {
                     if (kind > 14)
                        kind = 14;
                     jjCheckNAdd(2);
                  }
                  else if (curChar == 48)
                  {
                     if (kind > 14)
                        kind = 14;
                     jjCheckNAddStates(13, 15);
                  }
                  break;
               case 21:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 121)
                     kind = 121;
                  jjCheckNAdd(29);
                  break;
               case 1:
                  if ((0x3fe000000000000L & l) == 0L)
                     break;
                  if (kind > 14)
                     kind = 14;
                  jjCheckNAdd(2);
                  break;
               case 2:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 14)
                     kind = 14;
                  jjCheckNAdd(2);
                  break;
               case 3:
                  if (curChar == 46)
                     jjCheckNAdd(4);
                  break;
               case 4:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 19)
                     kind = 19;
                  jjCheckNAddTwoStates(4, 5);
                  break;
               case 6:
                  if ((0x280000000000L & l) != 0L)
                     jjCheckNAdd(7);
                  break;
               case 7:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 19)
                     kind = 19;
                  jjCheckNAdd(7);
                  break;
               case 8:
                  if (curChar == 34)
                     jjCheckNAddStates(10, 12);
                  break;
               case 9:
                  if ((0xfffffffbffffdbffL & l) != 0L)
                     jjCheckNAddStates(10, 12);
                  break;
               case 11:
                  if ((0x8400000000L & l) != 0L)
                     jjCheckNAddStates(10, 12);
                  break;
               case 12:
                  if (curChar == 34 && kind > 21)
                     kind = 21;
                  break;
               case 14:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 15;
                  break;
               case 15:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(10, 12);
                  break;
               case 16:
                  if (curChar == 48)
                     jjstateSet[jjnewStateCnt++] = 17;
                  break;
               case 17:
                  if ((0xf000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 18;
                  break;
               case 18:
                  if ((0xff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 19;
                  break;
               case 19:
                  if ((0xff000000000000L & l) != 0L)
                     jjCheckNAddStates(10, 12);
                  break;
               case 30:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 19)
                     kind = 19;
                  jjCheckNAddStates(0, 5);
                  break;
               case 31:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(31, 32);
                  break;
               case 32:
                  if (curChar == 46)
                     jjCheckNAdd(33);
                  break;
               case 33:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 19)
                     kind = 19;
                  jjCheckNAddTwoStates(33, 34);
                  break;
               case 35:
                  if ((0x280000000000L & l) != 0L)
                     jjCheckNAdd(36);
                  break;
               case 36:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 19)
                     kind = 19;
                  jjCheckNAdd(36);
                  break;
               case 37:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(37, 38);
                  break;
               case 38:
                  if (curChar == 46)
                     jjstateSet[jjnewStateCnt++] = 39;
                  break;
               case 40:
                  if ((0x280000000000L & l) != 0L)
                     jjCheckNAdd(41);
                  break;
               case 41:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 19)
                     kind = 19;
                  jjCheckNAdd(41);
                  break;
               case 42:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 19)
                     kind = 19;
                  jjCheckNAddTwoStates(42, 43);
                  break;
               case 44:
                  if ((0x280000000000L & l) != 0L)
                     jjCheckNAdd(45);
                  break;
               case 45:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 19)
                     kind = 19;
                  jjCheckNAdd(45);
                  break;
               case 46:
                  if (curChar != 48)
                     break;
                  if (kind > 14)
                     kind = 14;
                  jjCheckNAddStates(13, 15);
                  break;
               case 48:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 14)
                     kind = 14;
                  jjstateSet[jjnewStateCnt++] = 48;
                  break;
               case 50:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 14)
                     kind = 14;
                  jjstateSet[jjnewStateCnt++] = 50;
                  break;
               case 51:
                  if ((0xff000000000000L & l) == 0L)
                     break;
                  if (kind > 14)
                     kind = 14;
                  jjCheckNAdd(51);
                  break;
               case 52:
                  if (curChar == 35)
                     jjAddStates(6, 9);
                  break;
               case 53:
                  if (curChar == 35)
                     jjCheckNAdd(54);
                  break;
               case 54:
                  if ((0xfffffff7ffffffffL & l) != 0L)
                     jjCheckNAddTwoStates(54, 55);
                  break;
               case 55:
                  if (curChar == 35)
                     jjCheckNAdd(56);
                  break;
               case 56:
                  if ((0xfffffff7ffffffffL & l) != 0L)
                     jjCheckNAddTwoStates(56, 57);
                  break;
               case 57:
                  if (curChar == 35)
                     jjCheckNAddTwoStates(58, 60);
                  break;
               case 58:
                  if ((0xfffffff7ffffffffL & l) != 0L)
                     jjCheckNAddTwoStates(58, 60);
                  break;
               case 59:
                  if (curChar == 10 && kind > 10)
                     kind = 10;
                  break;
               case 60:
                  if (curChar == 35)
                     jjstateSet[jjnewStateCnt++] = 59;
                  break;
               case 62:
                  if (curChar == 35)
                     jjCheckNAdd(63);
                  break;
               case 63:
                  if ((0xfffffff7ffffffffL & l) != 0L)
                     jjCheckNAddTwoStates(63, 64);
                  break;
               case 64:
                  if (curChar == 35)
                     jjCheckNAdd(65);
                  break;
               case 65:
                  if ((0xfffffff7ffffffffL & l) != 0L)
                     jjCheckNAddTwoStates(65, 66);
                  break;
               case 66:
                  if (curChar == 35)
                     jjCheckNAddTwoStates(67, 69);
                  break;
               case 67:
                  if ((0xfffffff7ffffffffL & l) != 0L)
                     jjCheckNAddTwoStates(67, 69);
                  break;
               case 68:
                  if (curChar == 10 && kind > 11)
                     kind = 11;
                  break;
               case 69:
                  if (curChar == 35)
                     jjstateSet[jjnewStateCnt++] = 68;
                  break;
               case 71:
                  if (curChar == 35)
                     jjCheckNAdd(72);
                  break;
               case 72:
                  if ((0xfffffff7ffffffffL & l) != 0L)
                     jjCheckNAddTwoStates(72, 73);
                  break;
               case 73:
                  if (curChar == 35)
                     jjCheckNAdd(74);
                  break;
               case 74:
                  if ((0xfffffff7ffffffffL & l) != 0L)
                     jjCheckNAddTwoStates(74, 75);
                  break;
               case 75:
                  if (curChar == 35)
                     jjCheckNAddTwoStates(76, 78);
                  break;
               case 76:
                  if ((0xfffffff7ffffffffL & l) != 0L)
                     jjCheckNAddTwoStates(76, 78);
                  break;
               case 77:
                  if (curChar == 10 && kind > 12)
                     kind = 12;
                  break;
               case 78:
                  if (curChar == 35)
                     jjstateSet[jjnewStateCnt++] = 77;
                  break;
               case 80:
                  if (curChar == 35)
                     jjCheckNAdd(81);
                  break;
               case 81:
                  if ((0xfffffff7ffffffffL & l) != 0L)
                     jjCheckNAddTwoStates(81, 82);
                  break;
               case 82:
                  if (curChar == 35)
                     jjCheckNAdd(83);
                  break;
               case 83:
                  if ((0xfffffff7ffffffffL & l) != 0L)
                     jjCheckNAddTwoStates(83, 84);
                  break;
               case 84:
                  if (curChar == 35)
                     jjCheckNAddTwoStates(85, 87);
                  break;
               case 85:
                  if ((0xfffffff7ffffffffL & l) != 0L)
                     jjCheckNAddTwoStates(85, 87);
                  break;
               case 86:
                  if (curChar == 10 && kind > 13)
                     kind = 13;
                  break;
               case 87:
                  if (curChar == 35)
                     jjstateSet[jjnewStateCnt++] = 86;
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else if (curChar < 128)
      {
         long l = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 26:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                  {
                     if (kind > 121)
                        kind = 121;
                     jjCheckNAdd(29);
                  }
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 25;
                  break;
               case 22:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                  {
                     if (kind > 121)
                        kind = 121;
                     jjCheckNAdd(29);
                  }
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 21;
                  break;
               case 0:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                  {
                     if (kind > 121)
                        kind = 121;
                     jjCheckNAdd(29);
                  }
                  if (curChar == 102)
                     jjstateSet[jjnewStateCnt++] = 26;
                  else if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 22;
                  break;
               case 21:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                  {
                     if (kind > 121)
                        kind = 121;
                     jjCheckNAdd(29);
                  }
                  if (curChar == 117)
                     jjCheckNAdd(20);
                  break;
               case 5:
                  if ((0x2000000020L & l) != 0L)
                     jjAddStates(16, 17);
                  break;
               case 9:
                  if ((0xffffffffefffffffL & l) != 0L)
                     jjCheckNAddStates(10, 12);
                  break;
               case 10:
                  if (curChar == 92)
                     jjAddStates(18, 20);
                  break;
               case 11:
                  if ((0x14404410000000L & l) != 0L)
                     jjCheckNAddStates(10, 12);
                  break;
               case 13:
                  if (curChar == 120)
                     jjstateSet[jjnewStateCnt++] = 14;
                  break;
               case 14:
                  if ((0x7e00000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 15;
                  break;
               case 15:
                  if ((0x7e00000000L & l) != 0L)
                     jjCheckNAddStates(10, 12);
                  break;
               case 20:
                  if (curChar == 101 && kind > 22)
                     kind = 22;
                  break;
               case 23:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 22;
                  break;
               case 24:
                  if (curChar == 115)
                     jjCheckNAdd(20);
                  break;
               case 25:
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 24;
                  break;
               case 27:
                  if (curChar == 102)
                     jjstateSet[jjnewStateCnt++] = 26;
                  break;
               case 28:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 121)
                     kind = 121;
                  jjCheckNAdd(29);
                  break;
               case 29:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 121)
                     kind = 121;
                  jjCheckNAdd(29);
                  break;
               case 34:
                  if ((0x2000000020L & l) != 0L)
                     jjAddStates(21, 22);
                  break;
               case 39:
                  if ((0x2000000020L & l) != 0L)
                     jjAddStates(23, 24);
                  break;
               case 43:
                  if ((0x2000000020L & l) != 0L)
                     jjAddStates(25, 26);
                  break;
               case 47:
                  if ((0x100000001000000L & l) != 0L)
                     jjCheckNAdd(48);
                  break;
               case 48:
                  if ((0x7e0000007eL & l) == 0L)
                     break;
                  if (kind > 14)
                     kind = 14;
                  jjCheckNAdd(48);
                  break;
               case 49:
                  if ((0x400000004L & l) != 0L)
                     jjCheckNAdd(50);
                  break;
               case 50:
                  if ((0x7e0000007eL & l) == 0L)
                     break;
                  if (kind > 14)
                     kind = 14;
                  jjCheckNAdd(50);
                  break;
               case 54:
                  jjAddStates(27, 28);
                  break;
               case 56:
                  jjAddStates(29, 30);
                  break;
               case 58:
                  jjAddStates(31, 32);
                  break;
               case 61:
                  if (curChar == 77)
                     jjstateSet[jjnewStateCnt++] = 53;
                  break;
               case 63:
                  jjAddStates(33, 34);
                  break;
               case 65:
                  jjAddStates(35, 36);
                  break;
               case 67:
                  jjAddStates(37, 38);
                  break;
               case 70:
                  if (curChar == 109)
                     jjstateSet[jjnewStateCnt++] = 62;
                  break;
               case 72:
                  jjAddStates(39, 40);
                  break;
               case 74:
                  jjAddStates(41, 42);
                  break;
               case 76:
                  jjAddStates(43, 44);
                  break;
               case 79:
                  if (curChar == 83)
                     jjstateSet[jjnewStateCnt++] = 71;
                  break;
               case 81:
                  jjAddStates(45, 46);
                  break;
               case 83:
                  jjAddStates(47, 48);
                  break;
               case 85:
                  jjAddStates(49, 50);
                  break;
               case 88:
                  if (curChar == 115)
                     jjstateSet[jjnewStateCnt++] = 80;
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else
      {
         int i2 = (curChar & 0xff) >> 6;
         long l2 = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 9:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     jjAddStates(10, 12);
                  break;
               case 54:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     jjAddStates(27, 28);
                  break;
               case 56:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     jjAddStates(29, 30);
                  break;
               case 58:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     jjAddStates(31, 32);
                  break;
               case 63:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     jjAddStates(33, 34);
                  break;
               case 65:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     jjAddStates(35, 36);
                  break;
               case 67:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     jjAddStates(37, 38);
                  break;
               case 72:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     jjAddStates(39, 40);
                  break;
               case 74:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     jjAddStates(41, 42);
                  break;
               case 76:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     jjAddStates(43, 44);
                  break;
               case 81:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     jjAddStates(45, 46);
                  break;
               case 83:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     jjAddStates(47, 48);
                  break;
               case 85:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     jjAddStates(49, 50);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      if (kind != 0x7fffffff)
      {
         jjmatchedKind = kind;
         jjmatchedPos = curPos;
         kind = 0x7fffffff;
      }
      ++curPos;
      if ((i = jjnewStateCnt) == (startsAt = 89 - (jjnewStateCnt = startsAt)))
         return curPos;
      try { curChar = input_stream.readChar(); }
      catch(java.io.IOException e) { return curPos; }
   }
}
static private int jjMoveStringLiteralDfa0_2()
{
   switch(curChar)
   {
      case 10:
         return jjStopAtPos(0, 8);
      case 42:
         return jjMoveStringLiteralDfa1_2(0x80L);
      default :
         return 1;
   }
}
static private int jjMoveStringLiteralDfa1_2(long active0)
{
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      return 1;
   }
   switch(curChar)
   {
      case 47:
         if ((active0 & 0x80L) != 0L)
            return jjStopAtPos(1, 7);
         break;
      default :
         return 2;
   }
   return 2;
}
static private int jjMoveStringLiteralDfa0_1()
{
   switch(curChar)
   {
      case 10:
         return jjStopAtPos(0, 6);
      default :
         return 1;
   }
}
static final int[] jjnextStates = {
   31, 32, 37, 38, 42, 43, 61, 70, 79, 88, 9, 10, 12, 47, 49, 51, 
   6, 7, 11, 13, 16, 35, 36, 40, 41, 44, 45, 54, 55, 56, 57, 58, 
   60, 63, 64, 65, 66, 67, 69, 72, 73, 74, 75, 76, 78, 81, 82, 83, 
   84, 85, 87, 
};

/** Token literal values. */
public static final String[] jjstrLiteralImages = {
"", null, null, null, null, null, null, null, null, null, null, null, null, 
null, null, null, null, null, null, null, null, null, null, 
"\142\162\141\156\143\150", "\142\162\145\141\153", "\143\141\154\154\151\156\147\56", "\143\141\163\145", 
"\143\154\141\163\163", "\143\154\141\163\163\56", "\143\157\155\155\157\156", 
"\143\157\156\164\151\156\165\145", "\144\145\146\141\165\154\164", "\144\157", "\146\151\154\145\56", 
"\145\154\163\145", "\146\157\162", "\146\165\156\143\164\151\157\156", 
"\147\154\157\142\141\154", "\147\154\157\142\141\154\56", "\151\146", "\151\156\151\164\151\141\154", 
"\154\145\141\144\145\162\155\157\144\165\154\145", "\154\157\143\141\154\56", "\155\157\144\165\154\145", "\156\165\154\154", 
"\160\141\162", "\160\145\164\162\151\156\145\164", "\160\162\151\166\141\164\145", 
"\160\162\157\143\145\144\165\162\145", "\160\157\163\164\155\157\144\165\154\145", "\162\145\164\165\162\156", 
"\163\145\161", "\163\167\151\164\143\150", "\163\171\156\143", 
"\164\162\141\151\154\145\162\155\157\144\165\154\145", "\165\156\154\145\163\163", "\166\141\162\141\162\147\163", 
"\167\141\151\164\160\162\151", "\167\141\151\164\160\162\151\154\157\143\153", "\167\150\145\156", 
"\167\150\151\154\145", "\75", "\53\75", "\55\75", "\52\75", "\57\75", "\45\75", "\46\75", "\174\75", 
"\136\75", "\46\46\75", "\174\174\75", "\136\136\75", "\74\74\75", "\76\76\75", 
"\55\76\76", "\55\76", "\72\75", "\174\55", "\74\74\55", "\74\55", "\53\74\55", 
"\55\74\55", "\52\74\55", "\75\75", "\41\75", "\74\75", "\76\75", "\53", "\55", "\52", 
"\57", "\45", "\174\174", "\136\136", "\46\46", "\174", "\136", "\46", "\41", "\176", 
"\77", "\74\74", "\76\76", "\136\74\74", "\76\76\136", "\53\53", "\55\55", "\56\56", 
"\173", "\175", "\133", "\135", "\50", "\51", "\74", "\76", "\54", "\73", "\72", 
"\56", null, null, null, };

/** Lexer state names. */
public static final String[] lexStateNames = {
   "DEFAULT",
   "IN_SINGLE_LINE_COMMENT",
   "IN_MULTI_LINE_COMMENT",
};

/** Lex State array. */
public static final int[] jjnewLexState = {
   -1, -1, -1, -1, 1, 2, 0, 0, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
   -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
   -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
   -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
   -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
};
static final long[] jjtoToken = {
   0xffffffffffe87c01L, 0x3ffffffffffffffL, 
};
static final long[] jjtoSkip = {
   0x3feL, 0x0L, 
};
static protected SimpleCharStream input_stream;
static private final int[] jjrounds = new int[89];
static private final int[] jjstateSet = new int[178];
private static final StringBuilder jjimage = new StringBuilder();
private static StringBuilder image = jjimage;
private static int jjimageLen;
private static int lengthOfMatch;
static protected char curChar;
/** Constructor. */
public ParserTokenManager(SimpleCharStream stream){
   if (input_stream != null)
      throw new TokenMgrError("ERROR: Second call to constructor of static lexer. You must use ReInit() to initialize the static variables.", TokenMgrError.STATIC_LEXER_ERROR);
   input_stream = stream;
}

/** Constructor. */
public ParserTokenManager(SimpleCharStream stream, int lexState){
   this(stream);
   SwitchTo(lexState);
}

/** Reinitialise parser. */
static public void ReInit(SimpleCharStream stream)
{
   jjmatchedPos = jjnewStateCnt = 0;
   curLexState = defaultLexState;
   input_stream = stream;
   ReInitRounds();
}
static private void ReInitRounds()
{
   int i;
   jjround = 0x80000001;
   for (i = 89; i-- > 0;)
      jjrounds[i] = 0x80000000;
}

/** Reinitialise parser. */
static public void ReInit(SimpleCharStream stream, int lexState)
{
   ReInit(stream);
   SwitchTo(lexState);
}

/** Switch to specified lex state. */
static public void SwitchTo(int lexState)
{
   if (lexState >= 3 || lexState < 0)
      throw new TokenMgrError("Error: Ignoring invalid lexical state : " + lexState + ". State unchanged.", TokenMgrError.INVALID_LEXICAL_STATE);
   else
      curLexState = lexState;
}

static protected Token jjFillToken()
{
   final Token t;
   final String curTokenImage;
   final int beginLine;
   final int endLine;
   final int beginColumn;
   final int endColumn;
   String im = jjstrLiteralImages[jjmatchedKind];
   curTokenImage = (im == null) ? input_stream.GetImage() : im;
   beginLine = input_stream.getBeginLine();
   beginColumn = input_stream.getBeginColumn();
   endLine = input_stream.getEndLine();
   endColumn = input_stream.getEndColumn();
   t = Token.newToken(jjmatchedKind, curTokenImage);

   t.beginLine = beginLine;
   t.endLine = endLine;
   t.beginColumn = beginColumn;
   t.endColumn = endColumn;

   return t;
}

static int curLexState = 0;
static int defaultLexState = 0;
static int jjnewStateCnt;
static int jjround;
static int jjmatchedPos;
static int jjmatchedKind;

/** Get the next Token. */
public static Token getNextToken() 
{
  Token matchedToken;
  int curPos = 0;

  EOFLoop :
  for (;;)
  {
   try
   {
      curChar = input_stream.BeginToken();
   }
   catch(java.io.IOException e)
   {
      jjmatchedKind = 0;
      matchedToken = jjFillToken();
      return matchedToken;
   }
   image = jjimage;
   image.setLength(0);
   jjimageLen = 0;

   switch(curLexState)
   {
     case 0:
       try { input_stream.backup(0);
          while (curChar <= 13 && (0x2000L & (1L << curChar)) != 0L)
             curChar = input_stream.BeginToken();
       }
       catch (java.io.IOException e1) { continue EOFLoop; }
       jjmatchedKind = 0x7fffffff;
       jjmatchedPos = 0;
       curPos = jjMoveStringLiteralDfa0_0();
       break;
     case 1:
       jjmatchedKind = 0x7fffffff;
       jjmatchedPos = 0;
       curPos = jjMoveStringLiteralDfa0_1();
       if (jjmatchedPos == 0 && jjmatchedKind > 9)
       {
          jjmatchedKind = 9;
       }
       break;
     case 2:
       jjmatchedKind = 0x7fffffff;
       jjmatchedPos = 0;
       curPos = jjMoveStringLiteralDfa0_2();
       if (jjmatchedPos == 0 && jjmatchedKind > 9)
       {
          jjmatchedKind = 9;
       }
       break;
   }
     if (jjmatchedKind != 0x7fffffff)
     {
        if (jjmatchedPos + 1 < curPos)
           input_stream.backup(curPos - jjmatchedPos - 1);
        if ((jjtoToken[jjmatchedKind >> 6] & (1L << (jjmatchedKind & 077))) != 0L)
        {
           matchedToken = jjFillToken();
           TokenLexicalActions(matchedToken);
       if (jjnewLexState[jjmatchedKind] != -1)
         curLexState = jjnewLexState[jjmatchedKind];
           return matchedToken;
        }
        else
        {
           SkipLexicalActions(null);
         if (jjnewLexState[jjmatchedKind] != -1)
           curLexState = jjnewLexState[jjmatchedKind];
           continue EOFLoop;
        }
     }
     int error_line = input_stream.getEndLine();
     int error_column = input_stream.getEndColumn();
     String error_after = null;
     boolean EOFSeen = false;
     try { input_stream.readChar(); input_stream.backup(1); }
     catch (java.io.IOException e1) {
        EOFSeen = true;
        error_after = curPos <= 1 ? "" : input_stream.GetImage();
        if (curChar == '\n' || curChar == '\r') {
           error_line++;
           error_column = 0;
        }
        else
           error_column++;
     }
     if (!EOFSeen) {
        input_stream.backup(1);
        error_after = curPos <= 1 ? "" : input_stream.GetImage();
     }
     throw new TokenMgrError(EOFSeen, curLexState, error_line, error_column, error_after, curChar, TokenMgrError.LEXICAL_ERROR);
  }
}

static void SkipLexicalActions(Token matchedToken)
{
   switch(jjmatchedKind)
   {
      case 1 :
         image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
          ThreePL.incrLineNo();
         break;
      case 6 :
         image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
          ThreePL.incrLineNo();
         break;
      case 8 :
         image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
            ThreePL.incrLineNo();
         break;
      default :
         break;
   }
}
static void TokenLexicalActions(Token matchedToken)
{
   switch(jjmatchedKind)
   {
      case 10 :
        image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
                                                                      ThreePL.setPosition(image);
         break;
      case 11 :
        image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
                                                                       ThreePL.setPosition(image);
         break;
      case 12 :
        image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
                                                                      ThreePL.setPosition(image);
         break;
      case 13 :
        image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
                                                                       ThreePL.setPosition(image);
         break;
      default :
         break;
   }
}
static private void jjCheckNAdd(int state)
{
   if (jjrounds[state] != jjround)
   {
      jjstateSet[jjnewStateCnt++] = state;
      jjrounds[state] = jjround;
   }
}
static private void jjAddStates(int start, int end)
{
   do {
      jjstateSet[jjnewStateCnt++] = jjnextStates[start];
   } while (start++ != end);
}
static private void jjCheckNAddTwoStates(int state1, int state2)
{
   jjCheckNAdd(state1);
   jjCheckNAdd(state2);
}

static private void jjCheckNAddStates(int start, int end)
{
   do {
      jjCheckNAdd(jjnextStates[start]);
   } while (start++ != end);
}

}
