/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */
// Files created by javacc :-
//
//    ParseException.java
//    Parser.java
//    ParserConstants.java
//    ParserTokenManager.java
//    SimpleCharStream.java
//    Token.java
//    TokenMgrError.java
//
// Some of these files must be "massaged" after javacc has run - see the
// scripts in ../../scripts directory.

package threepl.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int WHITE_SPACE = 3;
  /** RegularExpression Id. */
  int FMODSTART = 10;
  /** RegularExpression Id. */
  int FMODFINISH = 11;
  /** RegularExpression Id. */
  int FSRCSTART = 12;
  /** RegularExpression Id. */
  int FSRCFINISH = 13;
  /** RegularExpression Id. */
  int INTEGER_LITERAL = 14;
  /** RegularExpression Id. */
  int DECIMAL_LITERAL = 15;
  /** RegularExpression Id. */
  int HEX_LITERAL = 16;
  /** RegularExpression Id. */
  int BIN_LITERAL = 17;
  /** RegularExpression Id. */
  int OCTAL_LITERAL = 18;
  /** RegularExpression Id. */
  int FLOATING_POINT_LITERAL = 19;
  /** RegularExpression Id. */
  int EXPONENT = 20;
  /** RegularExpression Id. */
  int STRING_LITERAL = 21;
  /** RegularExpression Id. */
  int LOG_LITERAL = 22;
  /** RegularExpression Id. */
  int BRANCH = 23;
  /** RegularExpression Id. */
  int BREAK = 24;
  /** RegularExpression Id. */
  int CALLINGDOT = 25;
  /** RegularExpression Id. */
  int CASE = 26;
  /** RegularExpression Id. */
  int CLASS = 27;
  /** RegularExpression Id. */
  int CLASSDOT = 28;
  /** RegularExpression Id. */
  int COMMON = 29;
  /** RegularExpression Id. */
  int CONTINUE = 30;
  /** RegularExpression Id. */
  int DEF = 31;
  /** RegularExpression Id. */
  int DO = 32;
  /** RegularExpression Id. */
  int FILEDOT = 33;
  /** RegularExpression Id. */
  int ELSE = 34;
  /** RegularExpression Id. */
  int FOR = 35;
  /** RegularExpression Id. */
  int FUNCTION = 36;
  /** RegularExpression Id. */
  int GLOBAL = 37;
  /** RegularExpression Id. */
  int GLOBALDOT = 38;
  /** RegularExpression Id. */
  int IF = 39;
  /** RegularExpression Id. */
  int INITIAL = 40;
  /** RegularExpression Id. */
  int LEADERMODULE = 41;
  /** RegularExpression Id. */
  int LOCALDOT = 42;
  /** RegularExpression Id. */
  int MODULE = 43;
  /** RegularExpression Id. */
  int NULL = 44;
  /** RegularExpression Id. */
  int PAR = 45;
  /** RegularExpression Id. */
  int PETRINET = 46;
  /** RegularExpression Id. */
  int PRIVATE = 47;
  /** RegularExpression Id. */
  int PROCEDURE = 48;
  /** RegularExpression Id. */
  int POSTMODULE = 49;
  /** RegularExpression Id. */
  int RETURN = 50;
  /** RegularExpression Id. */
  int SEQ = 51;
  /** RegularExpression Id. */
  int SWITCH = 52;
  /** RegularExpression Id. */
  int SYNC = 53;
  /** RegularExpression Id. */
  int TRAILERMODULE = 54;
  /** RegularExpression Id. */
  int UNLESS = 55;
  /** RegularExpression Id. */
  int VARARGS = 56;
  /** RegularExpression Id. */
  int WAITPRI = 57;
  /** RegularExpression Id. */
  int WAITPRILOCK = 58;
  /** RegularExpression Id. */
  int WHEN = 59;
  /** RegularExpression Id. */
  int WHILE = 60;
  /** RegularExpression Id. */
  int EQ = 61;
  /** RegularExpression Id. */
  int PLUSEQ = 62;
  /** RegularExpression Id. */
  int MINEQ = 63;
  /** RegularExpression Id. */
  int MULEQ = 64;
  /** RegularExpression Id. */
  int DIVEQ = 65;
  /** RegularExpression Id. */
  int REMEQ = 66;
  /** RegularExpression Id. */
  int BANDEQ = 67;
  /** RegularExpression Id. */
  int BOREQ = 68;
  /** RegularExpression Id. */
  int BXOREQ = 69;
  /** RegularExpression Id. */
  int LANDEQ = 70;
  /** RegularExpression Id. */
  int LOREQ = 71;
  /** RegularExpression Id. */
  int LXOREQ = 72;
  /** RegularExpression Id. */
  int LSEQ = 73;
  /** RegularExpression Id. */
  int RSEQ = 74;
  /** RegularExpression Id. */
  int RRPOINT = 75;
  /** RegularExpression Id. */
  int RPOINT = 76;
  /** RegularExpression Id. */
  int COLEQ = 77;
  /** RegularExpression Id. */
  int BUSPOINT = 78;
  /** RegularExpression Id. */
  int LLPOINT = 79;
  /** RegularExpression Id. */
  int LPOINT = 80;
  /** RegularExpression Id. */
  int PLUSLPOINT = 81;
  /** RegularExpression Id. */
  int MINUSLPOINT = 82;
  /** RegularExpression Id. */
  int MULLPOINT = 83;
  /** RegularExpression Id. */
  int EQEQ = 84;
  /** RegularExpression Id. */
  int NE = 85;
  /** RegularExpression Id. */
  int LE = 86;
  /** RegularExpression Id. */
  int GE = 87;
  /** RegularExpression Id. */
  int PLUS = 88;
  /** RegularExpression Id. */
  int MINUS = 89;
  /** RegularExpression Id. */
  int STAR = 90;
  /** RegularExpression Id. */
  int SLASH = 91;
  /** RegularExpression Id. */
  int PERCENT = 92;
  /** RegularExpression Id. */
  int OROR = 93;
  /** RegularExpression Id. */
  int UPUP = 94;
  /** RegularExpression Id. */
  int ANDAND = 95;
  /** RegularExpression Id. */
  int OR = 96;
  /** RegularExpression Id. */
  int UP = 97;
  /** RegularExpression Id. */
  int AND = 98;
  /** RegularExpression Id. */
  int EXCL = 99;
  /** RegularExpression Id. */
  int TILDE = 100;
  /** RegularExpression Id. */
  int QUEST = 101;
  /** RegularExpression Id. */
  int LS = 102;
  /** RegularExpression Id. */
  int RS = 103;
  /** RegularExpression Id. */
  int LR = 104;
  /** RegularExpression Id. */
  int RR = 105;
  /** RegularExpression Id. */
  int INCR = 106;
  /** RegularExpression Id. */
  int DECR = 107;
  /** RegularExpression Id. */
  int DOTDOT = 108;
  /** RegularExpression Id. */
  int LBRACE = 109;
  /** RegularExpression Id. */
  int RBRACE = 110;
  /** RegularExpression Id. */
  int LBRACK = 111;
  /** RegularExpression Id. */
  int RBRACK = 112;
  /** RegularExpression Id. */
  int LPAREN = 113;
  /** RegularExpression Id. */
  int RPAREN = 114;
  /** RegularExpression Id. */
  int LANGLE = 115;
  /** RegularExpression Id. */
  int RANGLE = 116;
  /** RegularExpression Id. */
  int COMMA = 117;
  /** RegularExpression Id. */
  int SEMICOL = 118;
  /** RegularExpression Id. */
  int COLON = 119;
  /** RegularExpression Id. */
  int DOT = 120;
  /** RegularExpression Id. */
  int IDENTIFIER = 121;
  /** RegularExpression Id. */
  int LETTER = 122;
  /** RegularExpression Id. */
  int DIGIT = 123;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int IN_SINGLE_LINE_COMMENT = 1;
  /** Lexical state. */
  int IN_MULTI_LINE_COMMENT = 2;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"\\n\"",
    "\"\\r\"",
    "<WHITE_SPACE>",
    "\"//\"",
    "\"/*\"",
    "\"\\n\"",
    "\"*/\"",
    "\"\\n\"",
    "<token of kind 9>",
    "<FMODSTART>",
    "<FMODFINISH>",
    "<FSRCSTART>",
    "<FSRCFINISH>",
    "<INTEGER_LITERAL>",
    "<DECIMAL_LITERAL>",
    "<HEX_LITERAL>",
    "<BIN_LITERAL>",
    "<OCTAL_LITERAL>",
    "<FLOATING_POINT_LITERAL>",
    "<EXPONENT>",
    "<STRING_LITERAL>",
    "<LOG_LITERAL>",
    "\"branch\"",
    "\"break\"",
    "\"calling.\"",
    "\"case\"",
    "\"class\"",
    "\"class.\"",
    "\"common\"",
    "\"continue\"",
    "\"default\"",
    "\"do\"",
    "\"file.\"",
    "\"else\"",
    "\"for\"",
    "\"function\"",
    "\"global\"",
    "\"global.\"",
    "\"if\"",
    "\"initial\"",
    "\"leadermodule\"",
    "\"local.\"",
    "\"module\"",
    "\"null\"",
    "\"par\"",
    "\"petrinet\"",
    "\"private\"",
    "\"procedure\"",
    "\"postmodule\"",
    "\"return\"",
    "\"seq\"",
    "\"switch\"",
    "\"sync\"",
    "\"trailermodule\"",
    "\"unless\"",
    "\"varargs\"",
    "\"waitpri\"",
    "\"waitprilock\"",
    "\"when\"",
    "\"while\"",
    "\"=\"",
    "\"+=\"",
    "\"-=\"",
    "\"*=\"",
    "\"/=\"",
    "\"%=\"",
    "\"&=\"",
    "\"|=\"",
    "\"^=\"",
    "\"&&=\"",
    "\"||=\"",
    "\"^^=\"",
    "\"<<=\"",
    "\">>=\"",
    "\"->>\"",
    "\"->\"",
    "\":=\"",
    "\"|-\"",
    "\"<<-\"",
    "\"<-\"",
    "\"+<-\"",
    "\"-<-\"",
    "\"*<-\"",
    "\"==\"",
    "\"!=\"",
    "\"<=\"",
    "\">=\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\"||\"",
    "\"^^\"",
    "\"&&\"",
    "\"|\"",
    "\"^\"",
    "\"&\"",
    "\"!\"",
    "\"~\"",
    "\"?\"",
    "\"<<\"",
    "\">>\"",
    "\"^<<\"",
    "\">>^\"",
    "\"++\"",
    "\"--\"",
    "\"..\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\"(\"",
    "\")\"",
    "\"<\"",
    "\">\"",
    "\",\"",
    "\";\"",
    "\":\"",
    "\".\"",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
  };

}
