/* Generated By:JJTree&JavaCC: Do not edit this line. SimExprConstants.java */
package threepl.simulator;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface SimExprConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int WHITESP = 1;
  /** RegularExpression Id. */
  int EOL = 2;
  /** RegularExpression Id. */
  int BREAK = 3;
  /** RegularExpression Id. */
  int CALL = 4;
  /** RegularExpression Id. */
  int CLOCK = 5;
  /** RegularExpression Id. */
  int CONT = 6;
  /** RegularExpression Id. */
  int DISP = 7;
  /** RegularExpression Id. */
  int EXIT = 8;
  /** RegularExpression Id. */
  int FORMAT = 9;
  /** RegularExpression Id. */
  int HELP = 10;
  /** RegularExpression Id. */
  int PANNOT = 11;
  /** RegularExpression Id. */
  int PLOT = 12;
  /** RegularExpression Id. */
  int PRINT = 13;
  /** RegularExpression Id. */
  int QUIT = 14;
  /** RegularExpression Id. */
  int RESET = 15;
  /** RegularExpression Id. */
  int RUN = 16;
  /** RegularExpression Id. */
  int SET = 17;
  /** RegularExpression Id. */
  int SHOW = 18;
  /** RegularExpression Id. */
  int STEP = 19;
  /** RegularExpression Id. */
  int TRACE = 20;
  /** RegularExpression Id. */
  int ADDCMD = 21;
  /** RegularExpression Id. */
  int CLEARCMD = 22;
  /** RegularExpression Id. */
  int CLOCKCMD = 23;
  /** RegularExpression Id. */
  int LISTCMD = 24;
  /** RegularExpression Id. */
  int OFFCMD = 25;
  /** RegularExpression Id. */
  int ONCMD = 26;
  /** RegularExpression Id. */
  int REMCMD = 27;
  /** RegularExpression Id. */
  int SHOWCMD = 28;
  /** RegularExpression Id. */
  int EDGECMD = 29;
  /** RegularExpression Id. */
  int LEVELCMD = 30;
  /** RegularExpression Id. */
  int WORD = 31;
  /** RegularExpression Id. */
  int INTCAST = 32;
  /** RegularExpression Id. */
  int FLOATCAST = 33;
  /** RegularExpression Id. */
  int PI = 34;
  /** RegularExpression Id. */
  int E = 35;
  /** RegularExpression Id. */
  int NULL = 36;
  /** RegularExpression Id. */
  int T = 37;
  /** RegularExpression Id. */
  int SIZEOF = 38;
  /** RegularExpression Id. */
  int WRIT = 39;
  /** RegularExpression Id. */
  int READ = 40;
  /** RegularExpression Id. */
  int ACC = 41;
  /** RegularExpression Id. */
  int CHANGED = 42;
  /** RegularExpression Id. */
  int COUNT = 43;
  /** RegularExpression Id. */
  int FREQ = 44;
  /** RegularExpression Id. */
  int PERIOD = 45;
  /** RegularExpression Id. */
  int LOG10 = 46;
  /** RegularExpression Id. */
  int LN = 47;
  /** RegularExpression Id. */
  int MIN = 48;
  /** RegularExpression Id. */
  int MAX = 49;
  /** RegularExpression Id. */
  int POW = 50;
  /** RegularExpression Id. */
  int DIMS = 51;
  /** RegularExpression Id. */
  int DIM = 52;
  /** RegularExpression Id. */
  int QUEUEWORDS = 53;
  /** RegularExpression Id. */
  int QUEUESPACES = 54;
  /** RegularExpression Id. */
  int QUEUEWRITESTATUS = 55;
  /** RegularExpression Id. */
  int QUEUEREADSTATUS = 56;
  /** RegularExpression Id. */
  int IDENT_GROUP = 57;
  /** RegularExpression Id. */
  int BOOLEAN_LITERAL = 58;
  /** RegularExpression Id. */
  int IDENTIFIER = 59;
  /** RegularExpression Id. */
  int WILDCARD_IDENTIFIER = 60;
  /** RegularExpression Id. */
  int DIGIT = 61;
  /** RegularExpression Id. */
  int LETTER = 62;
  /** RegularExpression Id. */
  int WILDCARD = 63;
  /** RegularExpression Id. */
  int OPENSQUAREBRACKET = 64;
  /** RegularExpression Id. */
  int CLOSESQUAREBRACKET = 65;
  /** RegularExpression Id. */
  int INTEGER_LITERAL = 67;
  /** RegularExpression Id. */
  int DECIMAL_LITERAL = 68;
  /** RegularExpression Id. */
  int HEX_LITERAL = 69;
  /** RegularExpression Id. */
  int OCTAL_LITERAL = 70;
  /** RegularExpression Id. */
  int BINARY_LITERAL = 71;
  /** RegularExpression Id. */
  int FLOATING_LITERAL = 72;
  /** RegularExpression Id. */
  int EXPONENT = 73;
  /** RegularExpression Id. */
  int STRING_LITERAL = 74;
  /** RegularExpression Id. */
  int EQUALS = 75;
  /** RegularExpression Id. */
  int COLON = 76;
  /** RegularExpression Id. */
  int XORL = 77;
  /** RegularExpression Id. */
  int ORL = 78;
  /** RegularExpression Id. */
  int ANDL = 79;
  /** RegularExpression Id. */
  int CARAT = 80;
  /** RegularExpression Id. */
  int ORB = 81;
  /** RegularExpression Id. */
  int ANDB = 82;
  /** RegularExpression Id. */
  int NE = 83;
  /** RegularExpression Id. */
  int EQ = 84;
  /** RegularExpression Id. */
  int LE = 85;
  /** RegularExpression Id. */
  int GE = 86;
  /** RegularExpression Id. */
  int GT = 87;
  /** RegularExpression Id. */
  int LT = 88;
  /** RegularExpression Id. */
  int RSH = 89;
  /** RegularExpression Id. */
  int LSH = 90;
  /** RegularExpression Id. */
  int MINUS = 91;
  /** RegularExpression Id. */
  int PLUS = 92;
  /** RegularExpression Id. */
  int REM = 93;
  /** RegularExpression Id. */
  int DIV = 94;
  /** RegularExpression Id. */
  int MUL = 95;
  /** RegularExpression Id. */
  int HOOK = 96;
  /** RegularExpression Id. */
  int TILDE = 97;
  /** RegularExpression Id. */
  int BANG = 98;
  /** RegularExpression Id. */
  int ELLIPSES = 99;
  /** RegularExpression Id. */
  int OPENBRACE = 100;
  /** RegularExpression Id. */
  int CLOSEBRACE = 101;
  /** RegularExpression Id. */
  int COMMA = 102;
  /** RegularExpression Id. */
  int DUMMY = 103;

  /** Lexical state. */
  int FUNCTION = 0;
  /** Lexical state. */
  int IN_HELP = 1;
  /** Lexical state. */
  int IN_SUBCOMMAND = 2;
  /** Lexical state. */
  int IN_COMMAND = 3;
  /** Lexical state. */
  int DEFAULT = 4;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<WHITESP>",
    "<EOL>",
    "<BREAK>",
    "<CALL>",
    "<CLOCK>",
    "<CONT>",
    "<DISP>",
    "<EXIT>",
    "<FORMAT>",
    "<HELP>",
    "<PANNOT>",
    "<PLOT>",
    "<PRINT>",
    "<QUIT>",
    "<RESET>",
    "<RUN>",
    "<SET>",
    "<SHOW>",
    "<STEP>",
    "<TRACE>",
    "<ADDCMD>",
    "<CLEARCMD>",
    "<CLOCKCMD>",
    "<LISTCMD>",
    "<OFFCMD>",
    "\"on\"",
    "<REMCMD>",
    "<SHOWCMD>",
    "<EDGECMD>",
    "<LEVELCMD>",
    "<WORD>",
    "\"int\"",
    "\"float\"",
    "\"PI\"",
    "\"E\"",
    "\"null\"",
    "\"t\"",
    "\"sizeof\"",
    "\"writ\"",
    "\"read\"",
    "\"acc\"",
    "\"changed\"",
    "\"count\"",
    "\"freq\"",
    "\"period\"",
    "\"log\"",
    "\"ln\"",
    "\"min\"",
    "\"max\"",
    "\"pow\"",
    "\"dimensions\"",
    "\"dimension\"",
    "\"queuewords\"",
    "\"queuespaces\"",
    "\"queuewritestatus\"",
    "\"queuereadstatus\"",
    "<IDENT_GROUP>",
    "<BOOLEAN_LITERAL>",
    "<IDENTIFIER>",
    "<WILDCARD_IDENTIFIER>",
    "<DIGIT>",
    "<LETTER>",
    "<WILDCARD>",
    "\"[\"",
    "\"]\"",
    "\".\"",
    "<INTEGER_LITERAL>",
    "<DECIMAL_LITERAL>",
    "<HEX_LITERAL>",
    "<OCTAL_LITERAL>",
    "<BINARY_LITERAL>",
    "<FLOATING_LITERAL>",
    "<EXPONENT>",
    "<STRING_LITERAL>",
    "\"=\"",
    "\":\"",
    "\"^^\"",
    "\"||\"",
    "\"&&\"",
    "\"^\"",
    "\"|\"",
    "\"&\"",
    "\"!=\"",
    "\"==\"",
    "\"<=\"",
    "\">=\"",
    "\">\"",
    "\"<\"",
    "\">>\"",
    "\"<<\"",
    "\"-\"",
    "\"+\"",
    "\"%\"",
    "\"/\"",
    "\"*\"",
    "\"?\"",
    "\"~\"",
    "\"!\"",
    "\"..\"",
    "\"{\"",
    "\"}\"",
    "\",\"",
    "\"<>\"",
    "\"(\"",
    "\")\"",
    "\"()\"",
  };

}
