/* Generated By:JavaCC: Do not edit this line. SimExprTreeConstants.java Version 5.0 */
package threepl.simulator;

public interface SimExprTreeConstants
{
  public int JJTCOMMAND = 0;
  public int JJTFORMATSPEC = 1;
  public int JJTBREAKCMD = 2;
  public int JJTCLOCKCMD = 3;
  public int JJTCONTCMD = 4;
  public int JJTDISPCMD = 5;
  public int JJTCALLCMD = 6;
  public int JJTFORMATCMD = 7;
  public int JJTHELPCMD = 8;
  public int JJTPLOTCMD = 9;
  public int JJTPRINTCMD = 10;
  public int JJTQUITCMD = 11;
  public int JJTRESETCMD = 12;
  public int JJTRUNCMD = 13;
  public int JJTSETCMD = 14;
  public int JJTSHOWCMD = 15;
  public int JJTSTEPCMD = 16;
  public int JJTTRACECMD = 17;
  public int JJTEXPRESSION = 18;
  public int JJTASSIGNMENT = 19;
  public int JJTRHSEXPRESSION = 20;
  public int JJTCONDITIONALEXP = 21;
  public int JJTLOGICALEXP = 22;
  public int JJTLOGICALOP = 23;
  public int JJTBITWISEEXP = 24;
  public int JJTBITWISEOP = 25;
  public int JJTEQUALITYEXP = 26;
  public int JJTEQUALITYOP = 27;
  public int JJTRELATIONALEXP = 28;
  public int JJTSHIFTEXP = 29;
  public int JJTSHIFTOP = 30;
  public int JJTADDITIVEEXP = 31;
  public int JJTADDITIVEOP = 32;
  public int JJTMULTIPLICATIVEEXP = 33;
  public int JJTMULTIPLICATIVEOP = 34;
  public int JJTUNARYEXP = 35;
  public int JJTCASTEXP = 36;
  public int JJTVAREXP = 37;
  public int JJTARRAYSUBSCRIPT = 38;
  public int JJTRANGEEXP = 39;
  public int JJTSTRUCTFIELD = 40;
  public int JJTFUNCEXP = 41;
  public int JJTPRIMARYEXP = 42;
  public int JJTCONSTANT = 43;
  public int JJTINITIALISER = 44;
  public int JJTINITELEMENT = 45;
  public int JJTIDENTIFIER = 46;
  public int JJTIDENTGROUP = 47;
  public int JJTINTEGERLITERAL = 48;
  public int JJTINTEGERDOTLITERAL = 49;
  public int JJTFLOATINGLITERAL = 50;
  public int JJTBOOLEANLITERAL = 51;
  public int JJTSTRINGLITERAL = 52;
  public int JJTWORD = 53;
  public int JJTWILDCARD = 54;


  public String[] jjtNodeName = {
    "command",
    "formatSpec",
    "breakCmd",
    "clockCmd",
    "contCmd",
    "dispCmd",
    "callCmd",
    "formatCmd",
    "helpCmd",
    "plotCmd",
    "printCmd",
    "quitCmd",
    "resetCmd",
    "runCmd",
    "setCmd",
    "showCmd",
    "stepCmd",
    "traceCmd",
    "expression",
    "assignment",
    "rhsExpression",
    "conditionalExp",
    "logicalExp",
    "logicalOp",
    "bitwiseExp",
    "bitwiseOp",
    "equalityExp",
    "equalityOp",
    "relationalExp",
    "shiftExp",
    "shiftOp",
    "additiveExp",
    "additiveOp",
    "multiplicativeExp",
    "multiplicativeOp",
    "unaryExp",
    "castExp",
    "varExp",
    "arraySubscript",
    "rangeExp",
    "structField",
    "funcExp",
    "primaryExp",
    "constant",
    "initialiser",
    "initElement",
    "identifier",
    "identGroup",
    "integerLiteral",
    "integerDotLiteral",
    "floatingLiteral",
    "booleanLiteral",
    "stringLiteral",
    "word",
    "wildcard",
  };
}
/* JavaCC - OriginalChecksum=d0b47f71814c5d4be5bd518c923e5342 (do not edit this line) */
