/*
 * 3PL - Parallel Pipeline Programming Language
 *
 * Copyright (C) 2002-2003
 *     CSIRO Manufacturing and Infrastructure Technology
 */

/* Generated By:JJTree: Do not edit this line. SimExprSimpleNode.java */

package threepl.simulator;

import java.util.ArrayList;
import java.util.Collection;
import java.util.HashMap;
import java.util.Iterator;

import threepl.parser.Constant;

/**
 * A SimExprSimpleNode is a node in a SimExpr expression tree.
 * A reference to the root node is obtained with SimExpr.getRoot().
 * The SimExpr constructors parse the input expression and call
 * a number of SimExprSimpleNode methods on the root node after the parse.
 * Firstly, trim() is called to remove redundant nodes from the tree.
 * A node is redundant where it contains no token and has a single child:
 * it is replaced with the child node. Secondly, resolve() is called to
 * resolve references to threepl identifiers (clocks and variables) and
 * generate values for constant and literal nodes. Thirdly, getType()
 * is called to type check the expression and generate storage for
 * node values where these have not already been created in resolve().
 * Finally, compressLiteral() is called to replace node sub-trees consisting
 * purely of literal or constant nodes with a single literal node.
 *
 * Once the above process has successfully completed, the expression
 * may be evaluated with the eval() method. eval() returns a SimExpNodeValue
 * object which contains the expression result. Refer SimExpNodeValue
 * for methods to access the value. The expr() method may be called to
 * return the expression String. This will be different to the originally
 * parsed expression String if any literals were removed in compressLiteral().
 * 
 * @version $Revision: 8254 $
 * @author Generated by JJTree, modified Andrew Tulloh
 */
@SuppressWarnings("all")
public class SimExprSimpleNode
      implements SimExprNode, SimExprConstants, SimExprTreeConstants, SimTypes, Constant {
      
   /** Reference to Sim object - required for variable references */
   public static Sim sim;

   // Reference to the parser
   protected SimExpr parser;

   // Node type
   protected int id;

   // Parent of this node      
   protected SimExprSimpleNode parent;

   // Children of this node
   protected SimExprSimpleNode[] children;

   // Reference to associated token
   protected SimExprToken token;

   // Object containing this node's value  
   protected SimExprNodeValue nodeValue;

   // Flag indicating whether queue availability should be ignored when
   // evaluating this node and its children
   private boolean ignoreAvailability;

   // Map containing all clocks associated with this expression 
   private HashMap associatedClockMap;
   
   // The single clock associated with this expression if there is only one,
   // else null
   private SimClock associatedClock;

   // Flag to indicate this is an identifier node with an @ preceding the name
   protected boolean bufferView;

   // Constant: ln 10
   private static final double LN10 = Math.log(10);

   /** 
    * Constructor with id
    * @param i The type of SimExprSimpleNode to create
    */    
   public SimExprSimpleNode(int i) {
     id = i;
   }

   /**
    * Constructor with SimExpr and id
    * @param p Reference to the SimExpr parser
    * @param i The type of SimExprSimpleNode to create
    */    
   public SimExprSimpleNode(SimExpr p, int i) {
      this(i);
      parser = p;
   }

   /**
    * Add child node in specified position. Any existing node at that position is replaced.
    * @param n The child node
    * @param i Index in children array to add child node
    */
   public void jjtAddChild(SimExprNode n, int i) {
      if (children == null) {
	 children = new SimExprSimpleNode[i + 1];
      } else if (i >= children.length) {
         SimExprSimpleNode c[] = new SimExprSimpleNode[i + 1];
	 System.arraycopy(children, 0, c, 0, children.length);
	 children = c;
      }
      children[i] = (SimExprSimpleNode)n;
      n.jjtSetParent(this);
   }

   /** Close a node */
   public void jjtClose() {
   }

   /**
    * Return reference to child node in specified position
    * @param i Index of child to return
    * @return The child node
    */
   public SimExprNode jjtGetChild(int i) {
      return children[i];
   }

   /**
    * Return number of child nodes
    * @return Number of child nodes
    */
   public int jjtGetNumChildren() {
      return (children == null) ? 0 : children.length;
   }

   /**
    * Get parent node
    * @return This node's parent
    */  
   public SimExprNode jjtGetParent() {
      return parent;
   }

   /**
    * Insert a child node at the ith position in the children[] array.
    * Existing children are shifted up in the array to make room.
    * @param child The child node to insert
    * @param i The index at which to insert the child in the children array
    */
   public void jjtInsertChild ( SimExprNode child, int i ) {
   
      SimExprSimpleNode[] c;

      if (children==null)
         children = new SimExprSimpleNode[0];
	 
      if (i == 0) {
         c = new SimExprSimpleNode[children.length + 1];
         System.arraycopy(children, 0, c, 1, children.length);
      
      } else if (i >= children.length) {
         c = new SimExprSimpleNode[i + 1];
         System.arraycopy(children, 0, c, 0, children.length);
      
      } else {
         c = new SimExprSimpleNode[children.length + 1];
         System.arraycopy(children, 0, c, 0, i);
	 System.arraycopy(children, i, c, i+1, children.length-i);
      }
      child.jjtSetParent(this);
      c[i] = (SimExprSimpleNode)child;
      children = c;	 
   }

   /** Open a node */
   public void jjtOpen() {
   }

   /**
    * Remove the ith child node and shift the children[] array appropriately
    * @param i Index of child to remove
    * @return A reference to the removed node, or null if none was removed
    */
   public SimExprNode jjtRemoveChild (int i) {
      
      if (children==null || i >= children.length)
         return null;

      SimExprNode orphan = children[i];
      SimExprSimpleNode[] c = new SimExprSimpleNode[children.length - 1];
      if (i == 0)
          System.arraycopy(children, 1, c, 0, children.length - 1);
      else {
          System.arraycopy(children, 0, c, 0, i);
          if (i < (children.length - 1))
              System.arraycopy(children, i + 1, c, i, 
                               children.length - i - 1);
      }
      children = c;
      orphan.jjtSetParent(null);
      return orphan;
   }      

   /**
    * Set parent node
    * @param n Node to make parent of this
    */  
   public void jjtSetParent(SimExprNode n) {
      parent = (SimExprSimpleNode)n;
   }
  
   /**
    * Compress a sub-tree containing only literal nodes into a single literal node.
    * Should not be called before getType().
    * @throws SimExprParseException If an error occurs evaluating a literal expression
    * @return true if this node and its sub-tree consists of literal nodes
    */
   public boolean compressLiteral () throws SimExprParseException {
      boolean isLiteral = true;
            
      switch (id) {
	 
      // These are always literal
      case JJTCONSTANT:
      case JJTINTEGERLITERAL:
      case JJTFLOATINGLITERAL:
      case JJTBOOLEANLITERAL:
      case JJTSTRINGLITERAL:
      case JJTIDENTGROUP:
      case JJTWORD:
	 break;

      // Some functions always return literal values. Others: fall through to default case
      case JJTFUNCEXP:
         if (token.kind==FREQ   ||
	     token.kind==PERIOD)
	    break;
		 
      // All other nodes (except command related nodes) and their sub-trees are
      // potentially replaced by a single literal node
      default:
         int nc;
	 if ((nc = jjtGetNumChildren())==0) {
	    isLiteral = false;
	    break;
         }	    
         for (int i=0; i<nc; i++)
	    isLiteral = children[i].compressLiteral() && isLiteral;

	 // If a command related node, or if any child node isn't literal,
	 // or this is a JJTIDENTIFIER, JJTRANGEEXP, JJTARRAYSUBSCRIPT,
	 // JJTSTRUCTFIELD or JJTINITIALISER node, can't replace this node
	 // with a literal
         switch (id) {
	 case JJTCOMMAND:
	 case JJTBREAKCMD:
	 case JJTCLOCKCMD:
	 case JJTCONTCMD:
	 case JJTDISPCMD:
	 case JJTCALLCMD:
	 case JJTFORMATCMD:
	 case JJTFORMATSPEC:
	 case JJTHELPCMD:
	 case JJTPRINTCMD:
	 case JJTQUITCMD:
	 case JJTRESETCMD:
	 case JJTRUNCMD:
	 case JJTSETCMD:
	 case JJTSHOWCMD:
	 case JJTSTEPCMD:
	 case JJTTRACECMD:
	 case JJTPLOTCMD:
	 case JJTWILDCARD:
	 case JJTIDENTIFIER:
	 case JJTRANGEEXP:
	 case JJTARRAYSUBSCRIPT:
         case JJTSTRUCTFIELD:
	 case JJTINITIALISER:
	    isLiteral = false;
	    break;
	 }
	 break;
      }	 

      // The sub-tree is literal, replace this node with a single literal without children
      if (isLiteral) {	 	    
	 try {	    
	    eval();
         } catch (SimException e) {
	    throw new SimExprParseException(e);
         }	    	    
	 token = new SimExprToken();
	 token.image = nodeValue.toString();
	 switch (nodeValue.getType()) {
	 case INT:
	 case UINT:
	 case BITS:
	    id = JJTINTEGERLITERAL;
	    token.kind = INTEGER_LITERAL;
	    break;
         case FIXED:
	 case UFIXED:	    
	 case FLOAT:
	    id = JJTFLOATINGLITERAL;
	    token.kind = FLOATING_LITERAL;
	    break;
	 case LOG:
	 case CONTROL:	       
	    id = JJTBOOLEANLITERAL;
	    token.kind = BOOLEAN_LITERAL;
	    break;
         case STRING:
	    id = JJTSTRINGLITERAL;
	    token.kind = STRING_LITERAL;
	    break;	    
	 } 
	 children = null;
      }
      
      return isLiteral;
   }

  /**
   * Print the tree at this node to standard output. Children are indented
   * under their parent.
   * @param prefix A String to prepend to each node's details, or null
   */
   public void dump(String prefix) {
      System.out.println(toString(prefix));
      if (children != null) {
         for (int i = 0; i < children.length; ++i) {
	    SimExprSimpleNode n = children[i];
	    if (n != null)
	       n.dump(prefix + " ");
         }
      }
   }

   /**
    * Evaluate node. This is called for the root node (and then recursively for
    * each node in the expression tree) when the expression is evaluated. It must
    * therefore be efficient (avoid memory allocation, unnecessary calls) as
    * breakpoint expressions are evaluated after each simulator clock cycle.
    * Efficiency is not as important for command related nodes as these are not
    * evaluated repetitively while the simulator runs. Should not be called
    * before getType().
    * @throws SimException If runtime evaluation error occurs, eg divide by zero
    * @return The SimExprNodeValue containing the evaluated value for this node
    */
   public SimExprNodeValue eval () throws SimException {
   
      double flhs, frhs;
      boolean blhs, brhs;
      SimExprSimpleNode child;
      String[] names;
      SimExprSimpleNode[] exprs;
      
      switch (id) {

      // *** Expression nodes ***
      
      case JJTASSIGNMENT:

         // Assign rhs to lhs
	 children[1].eval();
	 sim.assign(children[0], children[1]);
         break;
      
      case JJTCONDITIONALEXP:	 
         if (children[0].eval().getBoolean())
	    nodeValue.put(children[1].eval());
         else
	    nodeValue.put(children[2].eval());	    
         break;

      // Logical operator: short circuit calculation where possible	 	    
      case JJTLOGICALOP:
	 switch (token.kind) {
	 case XORL:	    
            blhs = children[0].eval().getBoolean();
	    brhs = children[1].eval().getBoolean();
	    nodeValue.put((blhs || brhs) && !(blhs && brhs));
	    break;	 
	 case ORL:
            if (children[0].eval().getBoolean())
	       nodeValue.put(true);	       
            else
	       nodeValue.put(children[1].eval().getBoolean());
	    break;
	 case ANDL:
            if (children[0].eval().getBoolean())
	       nodeValue.put(children[1].eval().getBoolean());
            else
	       nodeValue.put(false);	       
	    break;
	 }
         break;

      case JJTBITWISEOP:
         nodeValue.put(children[0].eval());
	 switch (token.kind) {
	 case CARAT:
	    nodeValue.xor(children[1].eval());
	    break;
	 case ORB:
	    nodeValue.or(children[1].eval());
	    break;
	 case ANDB:
	    nodeValue.and(children[1].eval());
	    break;
	 }
         break;
     
      case JJTEQUALITYOP:
         switch (token.kind) {
	 case NE:
	    nodeValue.put(!children[0].eval().eq(children[1].eval()));
            break;	    
	 case EQ:
	    nodeValue.put(children[0].eval().eq(children[1].eval()));
            break;
         }
	 break;

      case JJTRELATIONALEXP:
         flhs = children[0].eval().getDouble();
	 frhs = children[1].eval().getDouble();
         switch (token.kind) {
         case GE:
	    nodeValue.put(flhs >= frhs);
	    break;
         case LE:
	    nodeValue.put(flhs <= frhs);
	    break;
         case GT:
	    nodeValue.put(flhs > frhs);
	    break;
         case LT:
	    nodeValue.put(flhs < frhs);
	    break;
         }
	 break;
	 
      case JJTSHIFTOP:
         flhs = children[0].eval().getDouble();
	 frhs = children[1].eval().getDouble();
	 switch (token.kind) {
	 case RSH:
            nodeValue.put(flhs / Math.pow(2.0, frhs));
	    break;
	 case LSH:
            nodeValue.put(flhs * Math.pow(2.0, frhs));
	    break;	 
	 }
         break;

      case JJTADDITIVEOP:
         flhs = children[0].eval().getDouble();
	 frhs = children[1].eval().getDouble();         
	 switch (token.kind) {
	 case MINUS:
	    nodeValue.put(flhs - frhs);
	    break;
	 case PLUS:
	    nodeValue.put(flhs + frhs);
	    break;	 
	 }
         break;            
      
      case JJTMULTIPLICATIVEOP:
         flhs = children[0].eval().getDouble();
	 frhs = children[1].eval().getDouble();         
	 switch (token.kind) {
	 case REM:
	    if (frhs==0)
	       throw new SimException("divide by zero");
	    nodeValue.put(flhs % frhs);
	    break;
	 case DIV:
	    if (frhs==0)
	       throw new SimException("divide by zero");
	    nodeValue.put(flhs / frhs);
	    break;	 
	 case MUL:
	    nodeValue.put(flhs * frhs);
	    break;	 
	 }
         break;            
      
      case JJTUNARYEXP:
         switch (token.kind) {
         case MINUS:
	    nodeValue.put(-children[0].eval().getDouble());
	    break;
         case PLUS: 
	    nodeValue.put(children[0].eval().getDouble());
	    break;
         case TILDE:
	    // Complement = two's complement - 1 = negated value - 1
	    nodeValue.put(-children[0].eval().getDouble() - 1);
	    break;
         case BANG:
	    nodeValue.put(!children[0].eval().getBoolean());
	    break;	 	 
	 case LT:
	 case GT:
	    // Read/Write availability: child is a queue read availability signal, ie boolean
	    nodeValue.put(children[0].eval().getBoolean());
	    break;
	 case HOOK:
	    // Examine: just take queue data value
	    nodeValue.put(children[0].eval());
	    break;
	 }
	 break;      

      case JJTCASTEXP:
         nodeValue.put(children[0].eval());
         break;

      case JJTVAREXP:
         // Evaluate var exp, check queue read availability
         nodeValue.replaceVal(evalVarExp(true));
	 break;
	 
      case JJTARRAYSUBSCRIPT:
         if (jjtGetNumChildren()>0)
	    nodeValue.put(children[0].eval());
         break;
	      	 
      case JJTRANGEEXP:
         if (jjtGetNumChildren()==0)
	    nodeValue.getRange().put(0);
	 else if (children.length==1)
	    nodeValue.getRange().put((int)children[0].eval().getDouble());
	 else
            nodeValue.getRange().put((int)children[0].eval().getDouble(), (int)children[1].eval().getDouble());
	 break;
	 
      case JJTFUNCEXP:
         child = (children!=null && children.length>0) ? children[0] : null;
         switch (token.kind) {
	 
	 case T:
	    nodeValue.put(sim.getTime());
	    break;

         // QUEUEWORDS, QUEUESPACES, QUEUEWRITESTATUS and QUEUEREADSTATUS apply only to queues.
	 // Variable name only is specified (not a var expression).
	 case QUEUEWORDS:
	    nodeValue.put(child.nodeValue.getVariable().getQueuewords());
	    break;
	 case QUEUESPACES:
	    nodeValue.put(child.nodeValue.getVariable().getQueuespaces());
	    break;
	 case QUEUEWRITESTATUS:
	    nodeValue.put(child.nodeValue.getVariable().getQueueWriteStatus());
	    break;
	 case QUEUEREADSTATUS:
	    nodeValue.put(child.nodeValue.getVariable().getQueueReadStatus());
	    break;
	 	    
	 // READ, WRIT, ACC apply only to queues and statics. Variable name only is specified
	 // (not a var expression).
	 case READ:
            nodeValue.put(child.nodeValue.getVariable().wasRead());	    
	    break;
	 case WRIT:
            nodeValue.put(child.nodeValue.getVariable().wasWrit());
	    break;
	 case ACC:
            nodeValue.put(child.nodeValue.getVariable().wasAcc());
	    break;
	 
	 // COUNT, FREQ, PERIOD apply only to clocks  
	 case COUNT:
	    nodeValue.put((double)child.nodeValue.getClock().getCount());
	    break;
	 case FREQ:
	    // Freq, Mhz
            nodeValue.put(child.nodeValue.getClock().getFreq());
	    break;
	 case PERIOD:
	    // Period, ns
            nodeValue.put(child.nodeValue.getClock().getPeriod());
	    break;
	    
	 // CHANGED applies to any var expression or clock   
	 case CHANGED:
            nodeValue.put(child.eval().getIdentifier().wasChanged());
	    break;

	 // SIZEOF applies to any var expression   
         case SIZEOF:
	    nodeValue.put(child.eval().getValue().sizeof());
	    break;

         // DIMENSIONS applies to any var expression
	 case DIMS:
	    nodeValue.put(child.eval().getValue().dimensions());
	    break;

         // DIMENSION applies to any var expression
	 case DIM:
	    nodeValue.put(child.eval().getValue().dimension((int)children[1].eval().getDouble()));
	    break;
	    	    	    
         // Following functions can be used with any numerical expression parameters	    
	 case LOG10:
	    nodeValue.put(Math.log(child.eval().getDouble())/LN10);
	    break;
	 case LN:
	    nodeValue.put(Math.log(child.eval().getDouble()));
	    break;
	 case MIN:
	    nodeValue.put(Math.min(child.eval().getDouble(), children[1].eval().getDouble()));
	    break;
	 case MAX:
	    nodeValue.put(Math.max(child.eval().getDouble(), children[1].eval().getDouble()));
	    break;
	 case POW:
	    nodeValue.put(Math.pow(child.eval().getDouble(), children[1].eval().getDouble()));
	    break;
	 }
         break;

      // If an identifier, just return the value unless there are children. The presence of
      // children indicates this node represents a queuebuffer output and the children
      // represent the associated queuebuffer read and write availability variables. 
      case JJTIDENTIFIER:
      
         // If this represents a queue..
         if (children!=null) {

            // If buffer view, refer to internal buffer
	    if (isBufferView())
	       nodeValue.replaceVal(((SDEQueuebuffer)(nodeValue.getVariable().getSourceSDE())).getBuffer());
	    
	    // ..else check output availability if required:
            // if the read availability variable (first child) is false, the data output variable
	    // is undefined and we throw an exception, UNLESS the ignoreAvailability flag is set.	    
            else if (!ignoreAvailability && !children[0].eval().getBoolean())
	       throw new SimAvailException();
	 }

	 // ..else if a combinatorial ram with buffer view, refer to internal buffer
	 else if (isCram() && isBufferView())
	    nodeValue.replaceVal(((SDECram)(nodeValue.getVariable().getSourceSDE())).getBuffer());
	 	    
	 // ..else if a registered ram with buffer view, refer to internal buffer
	 else if (isRram() && isBufferView())
	    nodeValue.replaceVal(((SDERram)(nodeValue.getVariable().getSourceSDE())).getBuffer());

         break;
	 
      // No action for constants, literals, struct fields, just return the value	  
      case JJTINTEGERLITERAL:
      case JJTFLOATINGLITERAL:
      case JJTBOOLEANLITERAL:
      case JJTSTRINGLITERAL:
      case JJTCONSTANT:
      case JJTIDENTGROUP:
      case JJTWORD:
      case JJTSTRUCTFIELD:
         break;

      // A wildcard identifier node should have already been replaced by it's children in resolve()
      case JJTWILDCARD:
         throw new SimException("SimExprSimpleNode.eval():JJTWILDCARD node encountered");

      case JJTINITIALISER:
         if (children!=null)
            for (int i=0; i<children.length; i++)
	       children[i].eval();
         break;

      case JJTINITELEMENT:
         if (children!=null && children.length>0)
	    nodeValue.put(children[0].eval());
         break;
	 	    	 	 	 	 	              
      // *** Command nodes ***

      
      case JJTBREAKCMD:
         switch (token.kind) {
	 // Add breakpoint(s)
	 case ADDCMD:
            for (int i=0; i<children.length; i++)
	       sim.addBreak(children[i].expr(), children[i]);
            break;	       
	 // Remove breakpoint(s)
         case REMCMD:
	    names = new String[children.length];
            for (int i=0; i<names.length; i++)
	       names[i] = children[i].expr();
            sim.remBreak(names);
            break;	 
	 // Clear all breakpoints
	 case CLEARCMD:
	    sim.clearBreak();
	    break;
	 // List all breakpoints
	 case BREAK:
	 case LISTCMD:
	    sim.listBreak();
	    break;  
         // Set breakpoint(s) to edge or level type
	 case EDGECMD:
	 case LEVELCMD:
	    names = new String[children.length];
            for (int i=0; i<names.length; i++)
	       names[i] = children[i].expr();
	    sim.setBreak(names, token.kind==EDGECMD);
            break;	       
	 }	       
         break;
	       
      case JJTCLOCKCMD:
         if (children!=null && children.length>0)
	    sim.setClockDefault(children[0].nodeValue.getClock());
         else
	    sim.listClockDefault();
	 break;	    

      case JJTCONTCMD:
         sim.cont();
	 break;

      case JJTDISPCMD:
         switch (token.kind) {

	 // Add display(s), with optional preceding format spec.
	 // A format spec applies to the following argument. If the argument is a
	 // wildcard, the format is applied to the first matching identifier only.
	 case ADDCMD:
	    String fmt=null;
            for (int i=0; i<children.length; i++) {
	       child = children[i];
	       if (child.id==JJTFORMATSPEC)
	          fmt = child.eval().getString();
               else {		  
	          sim.addDisplay(child.expr(), child, fmt);
		  fmt = null;
               }		  
            }	       
            break;	       
	 // Remove display(s)
         case REMCMD:
	    names = new String[children.length];
            for (int i=0; i<children.length; i++)
	       names[i] = children[i].expr();
            sim.remDisplay(names);
            break;	 
	 // Clear all displays
	 case CLEARCMD:
	    sim.clearDisplay();
	    break;
	 // List all displays
	 case DISP:
	 case LISTCMD:
	    sim.listDisplay();
	    break;   
	 }	       
         break;

      case JJTCALLCMD:
      
         // Open file named in (single) child node, read command and execute,
	 // continue until eof.
	 sim.callFile(children[0].eval().getString());
	 break;
	 	 	    
      case JJTFORMATCMD:
         switch (token.kind) {

	 // Add format(s).
	 // A format spec applies to the following argument. If the argument is a
	 // wildcard, the format is applied to all matching identifiers.
	 case ADDCMD:
	    String fmt=null;
            for (int i=0; i<children.length; i++) {
	       child = children[i];
	       if (child.id==JJTFORMATSPEC)
	          fmt = child.eval().getString();
               else
	          sim.addFormat(child.expr(), fmt);
            }	       
            break;	       
	 // Remove format(s)
         case REMCMD:
	    names = new String[children.length];
            for (int i=0; i<children.length; i++)
	       names[i] = children[i].expr();
            sim.remFormat(names);
            break;	 
	 // Clear all formats
	 case CLEARCMD:
	    sim.clearFormat();
	    break;
	 // List all formats
	 case FORMAT:
	 case LISTCMD:
	    sim.listFormat();
	    break;   
	 }	       
         break;
	 	          
      case JJTHELPCMD:
	 names = children!=null ? new String[children.length] : null; 
         if (names!=null)
	    for (int i=0; i<children.length; i++)
	       names[i] = children[i].expr();
         sim.help(names);
         break;

      case JJTPRINTCMD:
	 String fmt=null;
	 ArrayList pair, pairs=null;

	 // Print expression(s), with optional preceding format spec.
	 // A format spec applies to the following argument. If the argument is a
	 // wildcard, the format is applied to the first matching identifier only.
	 // If command was print, just print values; else command was pannot, print
	 // all values in a formatted table.
         if (token.kind==PANNOT)
	    pairs = new ArrayList();	  
         for (int i=0; i<children.length; i++) {
	    child = children[i];
	    if (child.id==JJTFORMATSPEC) 
	       fmt = child.eval().getString();
	    else {
	       if (token.kind==PANNOT) {       
	          pair = new ArrayList();
	          pair.add(child);
	          pair.add(fmt);
	          pairs.add(pair);
               } else
	          // token.kind==PRINT
	          sim.printExprValue(child, fmt);
	       fmt = null;
            }
	 }
         if (token.kind==PANNOT)  
	    sim.printExprAnnot((ArrayList[])pairs.toArray(new ArrayList[0]));
	 break;
	 
      case JJTQUITCMD:
         sim.quitRequest();
	 break;

      case JJTRESETCMD:
         sim.reset();
	 break;
	 
      case JJTRUNCMD:
         sim.run();
	 break;

      case JJTCOMMAND:	 
         children[0].eval();
	 break;
	 
      case JJTSETCMD:
         for (int i=0; i<children.length; i++)
	    children[i].eval();
         break;
	 	    
      case JJTSHOWCMD:
	 sim.showExp(getExprs(), getNames());
         break;	       

      case JJTSTEPCMD:
	 if (children==null || children.length==0)
	    sim.step(1);
	 else if (children.length==1)
            sim.step((int)children[0].eval().getDouble());
	 else if (children.length==2)
            sim.step((int)children[0].eval().getDouble(),
	             (SimClock)children[1].nodeValue.getClock());
	 break;

      case JJTTRACECMD:
         switch (token.kind) {
	 // Add trace expr(s)
	 case ADDCMD:

	    // Show any filenames supplied in a new trace window for each filename.
	    // Do this before creating need trace(s) with exprs because exprs recreate filenames -
	    // could overwrite an old file we want to show in this command.
	    sim.addTrace(getNames());
	    // Create trace for any expressions supplied in a single trace window
	    sim.addTrace(getExprs());	       
            break;
	 // Remove trace(s) either by trace name or trace index number
         case REMCMD:
            sim.remTrace(getNamesOrIndices());
            break;	 
	 // Clear all traces
	 case CLEARCMD:
	    sim.clearTrace();
	    break;
	 // List all traces
	 case TRACE:
	 case LISTCMD:
	    sim.listTrace();
	    break;   
         // Enable trace(s) or specify trace(s) on condition
	 case ONCMD:
	    names = getNamesOrIndices();
	    exprs = getExprs();
	    SimExprSimpleNode expr = (exprs!=null && exprs[exprs.length-1].nodeValue.getType()==LOG) ?
	                             exprs[exprs.length-1] : null;
	    sim.enableTrace(names, expr);
	    break;
         // Disable trace(s)    	    	    
	 case OFFCMD:
	    sim.disableTrace(getNamesOrIndices());
	    break;
	 }	       
         break;
	 	 
      case JJTPLOTCMD:
         switch (token.kind) {

	 // Create and display a single plot containing a number of expressions, or
	 // create and display an number of plots from pre-existing plot file data
	 case ADDCMD:
	    // Plot any filenames supplied in a new plot window for each filename.
	    // Do this before plotting exprs because exprs recreate filenames -
	    // could overwrite an old file we want to plot in this command.
	    sim.addPlot(getNames());
            // Plot any expressions supplied in a single plot window            
            sim.addPlot(getExprs());             
            break;
	 // Remove plot(s) either by plot name or plot index number
         case REMCMD:
            sim.remPlot(getNamesOrIndices());
            break;	 
	 // Clear all plots
	 case CLEARCMD:
	    sim.clearPlot();
	    break;
	 // List all plots
	 case PLOT:
	 case LISTCMD:
	    sim.listPlot();
	    break;   
	 }	       
         break;
	 	 
      // No action for format spec nodes, just return value
      case JJTFORMATSPEC:
         break;      

      // Take evaluation from child for other (expression) nodes
      default:
         nodeValue.put(children[0].eval());
	 break;
	  
      }
      
      return nodeValue;
   }

   /**
    * Return the expression string for this node
    * @return The expression string for this node
    */
   public String expr () {

      String s;
      int nc = jjtGetNumChildren();
      String childString[] = new String[nc];
      for (int i=0; i<nc; i++)
         childString[i] = children[i].expr();
	  
      switch (id) {

      // *** Command line nodes ***
      
      case JJTFORMATSPEC:
         return "\""+token.image+"\"";

      case JJTWILDCARD:
         return "'"+token.image+"'";
	 	 	 
      case JJTBREAKCMD:
         s = "break" + (token.kind!=BREAK ? " "+token.image : "");
	 for (int i=0; i<nc; i++)
	    s += " "+childString[i];
         return s;	    

      case JJTDISPCMD:
         s = "disp" + (token.kind!=DISP ? " "+token.image : "");
	 for (int i=0; i<nc; i++)
	    s += " "+childString[i];
         return s;	    

      case JJTCALLCMD:
         return "exec \""+childString[0]+"\"";
	 
      case JJTFORMATCMD:
         s = "format" + (token.kind!=FORMAT ? " "+token.image : "");
	 for (int i=0; i<nc; i++)
	    s += " "+childString[i];
         return s;	    

      case JJTTRACECMD:
         s = "trace" +(token.kind!=TRACE ? " "+token.image : "");
	 for (int i=0; i<nc; i++)
	    s += " "+childString[i];
         return s;	    

      case JJTPLOTCMD:
         s = "plot" +(token.kind!=PLOT ? " "+token.image : "");
	 for (int i=0; i<nc; i++)
	    s += " "+childString[i];
         return s;	    
	 	    
      case JJTCLOCKCMD:
      case JJTCONTCMD:
      case JJTHELPCMD:
      case JJTPRINTCMD:
      case JJTQUITCMD:
      case JJTRESETCMD:
      case JJTRUNCMD:
      case JJTSETCMD:
      case JJTSHOWCMD:
      case JJTSTEPCMD:
         s = token.image;
	 for (int i=0; i<nc; i++)
	    s += " "+childString[i];
         return s;

            
      // *** Expression nodes ***

      	       	      
      case JJTPRIMARYEXP:
         if (token!=null)
            return "("+childString[0]+")";
         return childString[0];         	    
	 	 	 
      case JJTASSIGNMENT:
         return childString[0]+"="+childString[1];
      
      case JJTCONDITIONALEXP:
         return childString[0]+"?"+childString[1]+":"+childString[2];	 

      case JJTLOGICALOP:
      case JJTBITWISEOP:
      case JJTEQUALITYOP:
      case JJTRELATIONALEXP:
      case JJTSHIFTOP:
      case JJTADDITIVEOP:
      case JJTMULTIPLICATIVEOP:
         return childString[0]+token.image+childString[1];
      
      case JJTUNARYEXP:
         return token.image+childString[0];
	 
      case JJTCASTEXP:
         return "("+token.image+")";

      case JJTVAREXP:
         s = childString[0];
         for (int i=1; i<nc; i++)
	    s += childString[i];
         return s;	    
      	 
      case JJTSTRUCTFIELD:
         return "."+token.image;	    
      
      case JJTARRAYSUBSCRIPT:
         return "["+(nc>0?childString[0]:"")+"]";
         	 
      case JJTRANGEEXP:
         return childString[0]+(nc>1 ? ".."+childString[1] : "");

      case JJTFUNCEXP:
         s = token.image+"("+(nc>0?childString[0]:"");
	 for (int i=1; i<nc; i++)
	    s += ","+childString[i];
         s += ")";
	 return s;	    

      case JJTIDENTIFIER:
         return (bufferView ? "@" : "")+token.image;
	 	 
      case JJTINTEGERLITERAL:
      case JJTFLOATINGLITERAL:
      case JJTBOOLEANLITERAL:
      case JJTSTRINGLITERAL:
      case JJTCONSTANT:
      case JJTIDENTGROUP:
      case JJTWORD:
         return token.image;

      case JJTINITIALISER:
         s = "{";
	 for (int i=0; i<nc; i++)
	    s += childString[i];
         s += "}";
	 return s;	    

      case JJTINITELEMENT:
         return ","+(nc>0?childString[0]:"");	    
	 
      default:
         return childString[0];
      }
   }                     

   /**
    * Get type of this node, checking type of child nodes.
    * @throws SimExprParseException If type is invalid for operation
    * @return Node type as returned by SimExprNodeValue.getType()
    */
   public int getType () throws SimExprParseException {
      
      SimExprSimpleNode child;
         
      // Return type immediately if nodeValue exists, else generate it
      if (nodeValue!=null)
         return nodeValue.getType();

      // For identifier related expressions, resolve. Do this before
      // getting child types (immediately below) because some children
      // may be used in resolve(), eg for var expression nodes.
      switch (id) {
      case JJTCONSTANT:     
      case JJTIDENTIFIER:
      case JJTVAREXP:
      case JJTSTRUCTFIELD:
      case JJTINTEGERLITERAL:
      case JJTFLOATINGLITERAL:
      case JJTBOOLEANLITERAL:
      case JJTSTRINGLITERAL:
      case JJTFORMATSPEC:
      case JJTWILDCARD:
      case JJTIDENTGROUP:
      case JJTWORD:
         if (nodeValue==null)
            resolve();
         return nodeValue.getType();	       
      }
           	 
      // Get child types
      int nc = jjtGetNumChildren();
      for (int i=0; i<nc; i++)
         children[i].getType();

      switch(id) {      

      // *** COMMAND NODES ***
      
      case JJTCOMMAND:
      case JJTCONTCMD:
      case JJTDISPCMD:
      case JJTCALLCMD:
      case JJTFORMATCMD:
      case JJTHELPCMD:
      case JJTPRINTCMD:
      case JJTQUITCMD:
      case JJTRESETCMD:
      case JJTRUNCMD:
      case JJTSHOWCMD:
         nodeValue =  new SimExprNodeValue(SimExprNodeValue.CMD);
	 break;

      // Breakpoint command. Check all expressions being added have LOG result.
      case JJTBREAKCMD:
         switch (token.kind) {
	 case ADDCMD:
	    for (int i=0; i<nc; i++) {
	       if (!children[i].isBoolean())
	          throw new SimExprParseException(
	             "non-boolean breakpoint expression");
	    }
	    break;
         }	    
         nodeValue =  new SimExprNodeValue(SimExprNodeValue.CMD);
	 break;

      // Clock command. Check that child identifier, if present, is a SimClock
      case JJTCLOCKCMD:
         if (nc==1)
	    if (!children[0].nodeValue.isClock())
	       throw new SimExprParseException(children[0].token.image+" is not a clock");
         nodeValue =  new SimExprNodeValue(SimExprNodeValue.CMD);
	 break;

      // Set command. Check all expressions are assignments	 
      case JJTSETCMD:
	 for (int i=0; i<nc; i++)
	    if (children[i].id!=JJTASSIGNMENT)
	       throw new SimExprParseException("non-assignment expression");
         nodeValue =  new SimExprNodeValue(SimExprNodeValue.CMD);
	 break;

      // Step command. Allowed formats are:
      // step
      // step n
      // step n clock
      // 
      // Check n is an integer expression. Check clock is a SimClock (identifier).
      case JJTSTEPCMD:
         if (nc>=1) {
	    if (!children[0].isInt())
	       throw new SimExprParseException("non-integer expression");
         }	    
         if (nc==2) {
	    if (!children[1].nodeValue.isClock())
               throw new SimExprParseException(children[1].token.image+" is not a clock");
	 }	    
         nodeValue =  new SimExprNodeValue(SimExprNodeValue.CMD);
         break;

      // Trace command. Allowed formats are:
      // trace add expr|"filename" [ expr|"filename".. ]
      // trace rem index|"name" [index|"name"..]
      // trace clear
      // trace [list]
      // trace on index|"name" [index|"name"..] [expr]
      // trace off index|"name" [index|"name"..]
      case JJTTRACECMD:
         switch (token.kind) {
	 
	 // If trace rem or off, check all child expressions are integer or STRING
	 case REMCMD:
	 case OFFCMD:
	    for (int i=0; i<nc; i++)
	       if (!(children[i].isInt() || children[i].getType()==STRING))
	          throw new SimExprParseException(
	             "arguments to trace rem must be existing trace indices or trace names");
            break;
	    		     	       	 
	 // If trace on, check all children are integer or STRING, except that if
	 // number of children exceeds 1, last child may be LOG.
         case ONCMD:
            for (int i=0; i<nc; i++) {
	       if (nc>1 && i==nc-1) {
	          if (!(children[i].isInt() || children[i].isBoolean() || children[i].getType()==STRING))
                     throw new SimExprParseException(
		        "non-integer or non-string trace specifier, or non-boolean trace "+token.image+" expression");		      
               } else if (!(children[i].isInt() || children[i].getType()==STRING))
	          throw new SimExprParseException(
	             "non-integer or non-string trace specifier");
            }		     
	    break;	    	  
         }	    
         nodeValue =  new SimExprNodeValue(SimExprNodeValue.CMD);
         break;

      // Plot command. Allowed formats are:
      // plot add expr|"filename" [ expr|"filename".. ]
      // plot rem index|"name" [index|"name"..]
      // plot clear
      // plot [list]
      case JJTPLOTCMD:
	 switch (token.kind) {
	 // If plot add, insert a FLOAT child node as the first expression, to
	 // hold time of the sample (this is used as the x-axis value when plotting
	 // expressions).
         case ADDCMD:
	    SimExprSimpleNode time = new SimExprSimpleNode(JJTFLOATINGLITERAL);
	    time.nodeValue = new SimExprNodeValue(FLOAT);	    
	    jjtInsertChild(time, 0); 
	    break;
         // If plot rem, check all child expressions are integer or STRING
	 case REMCMD:
	    for (int i=0; i<nc; i++)
               if (!(children[i].isInt() || children[i].getType()==STRING))
	          throw new SimExprParseException(
	             "arguments to plot rem must be existing plot indices or plot names");
            break;		     	       
	 }
         nodeValue =  new SimExprNodeValue(SimExprNodeValue.CMD);
         break;
             
       	        	 
      // *** EXPRESSION NODES ***


      // Assignment operands must be compatible, but this is not checked until eval() because
      // var expressions cannot be resolved until then. Result type is same as
      // lhs type. Result node refers to lhs value.
      case JJTASSIGNMENT:

         // Check compatibility
         if (!children[0].nodeValue.isCastable(children[1].nodeValue))
	    throw new SimException("mixed type(s) in assignment expression");

         // Ignore queue availability with queue on lhs of assignment	       
         if (children[0].isQueue())
	    children[0].ignoreAvailability();
	    	       
         nodeValue = children[0].nodeValue;	       
         break;	    	    
         	          
      // Ternary conditional expression requires a boolean (LOG or CONTROL) first operand.
      // Two remaining operands may be numeric or boolean but not mixed.
      // Result is same type as last two operands.
      case JJTCONDITIONALEXP:
         if (!children[0].isBoolean())
	    throw new SimExprParseException(
	       "non-boolean type on lhs in ?: expression");
         if (!children[1].nodeValue.isCastable(children[2].nodeValue))	       
	    throw new SimExprParseException(
	       "mixed types on rhs in ?: expression");
         nodeValue = new SimExprNodeValue(
	    SimType.resultType(children[1].getType(), children[2].getType()));	       
         break;
	 	 	
      // Children of binary logical operator must be boolean. Result is LOG.
      case JJTLOGICALOP:
         if (!(children[0].isBoolean() && children[1].isBoolean()))
	    throw new SimExprParseException(
	       "non-boolean type in logical ("+token.image+") expression");
         nodeValue = new SimExprNodeValue(LOG);
	 break;		  
      
      // Children of binary bitwise operator must be integer. Result is same as first child.
      case JJTBITWISEOP:
         if (!(children[0].isInt() && children[1].isInt()))
	    throw new SimExprParseException(
	       "non-integer type in bitwise ("+token.image+") expression");
	 nodeValue = new SimExprNodeValue(children[0].getType());
	 break;		  
      
      // Children of binary equality operator must be of same type (numeric or boolean).
      // Result is LOG.
      case JJTEQUALITYOP:
         if (!children[0].nodeValue.isCastable(children[1].nodeValue))
	    throw new SimExprParseException(
	       "mixed types in equality expression");
         nodeValue = new SimExprNodeValue(LOG);
	 break;		  
      
      // Children of binary relational operator must be numeric. Result is LOG.
      case JJTRELATIONALEXP:
         if (!(children[0].isNumeric() && children[1].isNumeric()))
	    throw new SimExprParseException(
	       "non-numeric type used in relational expression");
         nodeValue = new SimExprNodeValue(LOG);
	 break;		  
	 
      // Children of binary shift operator must be integer. Result is same as first child.
      case JJTSHIFTOP:
         if (!(children[0].isInt() && children[1].isInt()))
	    throw new SimExprParseException(
	       "non-integer type in shift ("+token.image+") expression");
	 nodeValue = new SimExprNodeValue(children[0].getType());
	 break;		  

      // Children of binary additive operator must be numeric. Result is FLOAT if one
      // of the operands is FLOAT, else INT.
      case JJTADDITIVEOP:
         if (!(children[0].isNumeric() && children[1].isNumeric()))
	    throw new SimExprParseException(
	       "non-numeric type in additive expression");
         nodeValue = new SimExprNodeValue(
	    SimType.resultType(children[0].getType(), children[1].getType()));	       
         break;
      
      // Children of binary multiplicative operator must be numeric for DIV and MUL, and
      // must be INTEGER for REM. Result is FLOAT if one of the operands is FLOAT, else INT.
      case JJTMULTIPLICATIVEOP:
         switch (token.kind) {
	 // REM requires two integer operands
	 case REM:
            if (!(children[0].isInt() && children[1].isInt()))
	       throw new SimExprParseException(
	          "non-integer type in multiplicative ("+token.image+") expression");
            nodeValue = new SimExprNodeValue(INT);
	    break;
         // DIV and MUL require two numeric operands    
	 case DIV:
	 case MUL:
            if (!(children[0].isNumeric() && children[1].isNumeric()))
	       throw new SimExprParseException(
	          "non-numeric type in multiplicative ("+token.image+") expression");
            nodeValue = new SimExprNodeValue(
	       SimType.resultType(children[0].getType(), children[1].getType()));	       
            break;
         }	    		   
         break;	    	    

      // Unary operators.
      // LT, GT and HOOK require a queue operand. Result is LOG for LT or GT (queue availability)
      // and same as child for HOOK (queue examine).
      // MINUS, PLUS require a numeric operand. Result is numeric.
      // TILDE requires an integer operand. Result type is same as child type.
      // BANG requires a LOG operand. Result is LOG.
      case JJTUNARYEXP:

         switch (token.kind) {
	       
         // Queue read or write availability operator, parameter must be a queue variable name
	 case LT:
	 case GT:
	    if (!children[0].nodeValue.isQueue())
	       throw new SimExprParseException(
	          "non-queuebuffer type with unary "+token.image+" operator");

	    // Point to boolean queue read/write availability signal instead of queue data output signal
	    // Result is LOG even though the queue availability signal is CONTROL.	    
	    jjtAddChild(children[0].jjtGetChild(token.kind==LT?0:1), 0);
            nodeValue = new SimExprNodeValue(LOG);	       
            break;

         // Queue examine operator, parameter can be a queue variable name or a var exp involving one.
	 // Just replace this node with it's first child. Set the ignoreAvailability flag in this node
	 // and its children so queue read availability is ignored later during eval().
         case HOOK:
	    if (!children[0].isQueue())
	       throw new SimException("non-queuebuffer type with unary "+token.image+" operator");	       
            id = children[0].id;
	    token = children[0].token;
	    nodeValue = children[0].nodeValue;
	    children = children[0].children;	       	       
            ignoreAvailability();	       
	    break;
	 
	 // General operators..   	    
	 case MINUS:
	 case PLUS:
	    if (!children[0].isNumeric())
	       throw new SimExprParseException(
	          "non-numeric type with unary "+token.image+" operator");
            nodeValue = new SimExprNodeValue(children[0].getType());	       
            break;
	 case TILDE:
	    if (!children[0].isInt())
	       throw new SimExprParseException(
	          "non-integer type with unary "+token.image+" operator");
            nodeValue = new SimExprNodeValue(children[0].getType());	       
            break;
         case BANG:
	    if (!children[0].isBoolean())
	       throw new SimExprParseException(
	          "non-boolean type with unary "+token.image+" operator");
            nodeValue = new SimExprNodeValue(children[0].getType());	       
	    break;
         }	        	    	 
	 break;

      // Cast expression defines it's own type. Child type must be compatible.
      case JJTCASTEXP:
         // Casts are either (int) or (float), so child must be numeric
	 if (!children[0].isNumeric())
	    throw new SimExprParseException(
	       "non-numeric type with "+token.image+" cast");
         switch (token.kind) {
	 case INTCAST:
            nodeValue = new SimExprNodeValue(INT);
	    break;	       
	 case FLOATCAST:
            nodeValue = new SimExprNodeValue(FLOAT);
	    break;	       
         }	 	 
         break;

      // Array subscript.
      // If there is a child, it is either a range expression or a single expression.
      // If there are no children the node represents an empty subscript [].
      // If the child is a single expression, check it is integer type.
      // If there are no children, do not create a nodeValue as in this case it is not used.
      // If a nodeValue is created, its type (ie result type) is the same as the child.
      case JJTARRAYSUBSCRIPT:
         if (nc>0) {
	    if (children[0].id!=JJTRANGEEXP) {
	       if (!children[0].isInt())
	          throw new SimExprParseException("non-integer array subscript");
            }	       		  
            nodeValue = new SimExprNodeValue(children[0].getType());      
	 } 
         break;
	             	 	 
      // Range expression (for array subscript) has one or two children,
      // which must be type integer. The first child is the low range specifier (or the single specifier
      // if no second child is present). The second child, if present, is the high range specifier.
      // Result type is RANGE.
      case JJTRANGEEXP:
         for (int i=0; i<nc; i++)
	    if (!children[i].isInt())
	       throw new SimExprParseException("non-integer type in range expression");	       
	 nodeValue = new SimExprNodeValue(SimExprNodeValue.RANGE);
         break; 

      // A function's argument type(s) and its return type are function dependent
      case JJTFUNCEXP:
	 child = (children!=null && children.length>0) ? children[0] : null;
	    
         switch (token.kind) {

         // t: Simulator time.
         case T:
	    nodeValue = new SimExprNodeValue(FLOAT);
	    break;
	    
	 // queuewords and queuespaces: identifier must be a queue data output variable, ie corresponding to
	 // the threepl queue. Array subscripts/struct fields are not allowed.
	 case QUEUEWORDS:
	 case QUEUESPACES:
	    if (nc!=1 || !child.nodeValue.isQueue() || child.id!=JJTIDENTIFIER)
	       throw new SimExprParseException(token.image+
	          " requires a queue variable name parameter");	    
	    nodeValue = new SimExprNodeValue(UINT);
	    break;
	 
	 // queuewritestatus and queuereadstatus: identifier must be a queue data output variable,
	 // ie corresponding to the threepl queue, which must be an asynchronous queue.
	 // Array subscripts/struct fields are not allowed.
	 case QUEUEWRITESTATUS:
	 case QUEUEREADSTATUS:
	    if (nc!=1 || !child.nodeValue.isAsyncQueue() || child.id!=JJTIDENTIFIER)
	       throw new SimExprParseException(token.image+
	          " requires an async queue variable name parameter");
            SimVariable var = child.nodeValue.getVariable();		  	    
	    nodeValue = new SimExprNodeValue(var);
	    if (token.kind==QUEUEWRITESTATUS)
	       nodeValue.replaceVal(var.getQueueWriteStatus().duplicate());
            else
	       nodeValue.replaceVal(var.getQueueReadStatus().duplicate());	    	       
	    break;
	 
	 // read: identifier must be a queue or registered ram data output variable.
	 // Array subscripts/struct fields are not allowed. (This function nyi for
	 // statics and vals as these are deemed to be read when their dest threepl
	 // variables are written - a more complicated scenario to sort out.)
	 case READ:
	    if (nc!=1 || child.id!=JJTIDENTIFIER || !(child.nodeValue.isQueue() || child.nodeValue.isRram()))
	       throw new SimExprParseException(token.image+
	          " requires a queue or registered ram output variable name parameter, without array subscripts");	    
	    nodeValue = new SimExprNodeValue(LOG);
	    break;
	 
	 // writ: identifier must be a queue, static or ram data output variable.
	 // Array subscripts/struct fields are not allowed.
         //
	 // acc: identifier must be a queue, static or ram data output variable.
	 // Array subscripts/struct fields are not allowed.
	 // (This function nyi for vals - see READ above).
	 case WRIT:
	 case ACC:
	    if (child.id!=JJTIDENTIFIER ||
	        (!child.nodeValue.isQueue() && !child.nodeValue.isStatic() && !child.nodeValue.isCram() && !child.nodeValue.isRram()))
	       throw new SimExprParseException(token.image+
	          " requires a queue, static or ram output variable name parameter, without array subscripts");	    
	    nodeValue = new SimExprNodeValue(LOG);
	    break;
	 
	 // changed: parameter may be a var expression or an identifier if a variable,
	 // or an identifier only if a clock.
	 case CHANGED:
	    // Check child is a var expression or an identifier
	    if (!(child.id==JJTIDENTIFIER || child.id==JJTVAREXP))
	       throw new SimExprParseException(
	          token.image+" requires a clock name, variable name or variable expression parameter");
	    nodeValue = new SimExprNodeValue(LOG);
	    break;
	    
         // Functions of a clock identifier. Parameter must be a clock identifier.
	 case COUNT:
	    if (!child.nodeValue.isClock())
	       throw new SimExprParseException(
	          token.image+" requires a clock name parameter");	    
	    nodeValue = new SimExprNodeValue(UINT);
	    break;
	 case FREQ:
	 case PERIOD:
	    if (!child.nodeValue.isClock())
	       throw new SimExprParseException(
	          token.image+" requires a clock name parameter");	    
	    nodeValue = new SimExprNodeValue(FLOAT);
	    break;
	        
	 // Functions of a single numeric variable returning a FLOAT result
	 case LOG10:
	 case LN:
	    if (nc!=1 || !children[0].isNumeric())
	       throw new SimExprParseException(
	          token.image+" function takes a single numeric argument");
	    nodeValue = new SimExprNodeValue(FLOAT);
	    break;
	    
	 // Functions of two numeric variables returning a float result
	 case MIN:
	 case MAX:
	 case POW:
	    if (nc!=2 || 
	        !(children[0].isNumeric() && children[1].isNumeric()))
	       throw new SimExprParseException(
	          token.image+" function takes two numeric arguments");
	    nodeValue = new SimExprNodeValue(FLOAT);
	    break;
	    
	 // sizeof and dimensions functions. Parameter must be a var expression
	 // or variable identifier. Result is a UINT.
	 case SIZEOF:
	 case DIMS:
	    if (!child.nodeValue.isVariable())
	       throw new SimExprParseException(
	          token.image+" function requires variable name or variable expression parameter");
	    nodeValue = new SimExprNodeValue(UINT);	    
	    break;
	    
         // dimension function. First parameter must be a var expression or variable identifier
	 // and second parameter an integer type. Result is a UINT
	 case DIM:
	    if (!(nc==2 && child.nodeValue.isVariable() && children[1].isInt()))
	       throw new SimExprParseException(
	          token.image+" function requires variable expression and int parameters");
            nodeValue = new SimExprNodeValue(UINT);		  
	    break;	    	    
	 }
         break;
	               	        	 
      case JJTINITIALISER:                  
	 SimExprNodeValue[] nodeValues = new SimExprNodeValue[nc];
	 for (int i=0; i<nc; i++)
	    nodeValues[i] = children[i].nodeValue;	    
         nodeValue = new SimExprNodeValue(nodeValues);
	 break;

      case JJTINITELEMENT:
         if (nc>0)
	    nodeValue = new SimExprNodeValue(children[0].getType());
         break;
	 	 	
      // Use the (single) child's type for other nodes
      default:
         nodeValue = new SimExprNodeValue(children[0].getType());
         break;
      }

      // Get map of all clocks associated with the expression,
      // also the single clock associated with the expression if there
      // is only one
      getAssociatedClocks();
                  
      return nodeValue!=null ? nodeValue.getType() : NULL_TYPE;
   }    

   /**
    * Return the single SimClock associated with this expression, if there is only
    * one, else return null
    * @return The single SimClock associated with this expression, if there is only
    * one, else return null
    */
   public SimClock getAssociatedClock () {
      return associatedClock;
   }

   /**
    * Return a map of the clocks used in this expression. Map key is String clock name
    * and map value is the corresponding SimClock.
    * @return A map of the clocks used in this expression
    */         
   public HashMap getAssociatedClocks () {
   
      SimClock clock;
      
      // Create the map which will contain all clocks associated with this expression      
      associatedClockMap = new HashMap();
      
      // Add the clock associated with this node, if any, to the map
      if (nodeValue!=null && (clock = nodeValue.getAssociatedClock()) != null)
         associatedClockMap.put(clock.getId(), clock);

      // Merge the child maps with this one too	 
      for (int i=0; i<jjtGetNumChildren(); i++)
         associatedClockMap.putAll(children[i].getAssociatedClocks());

      // Get the single clock associated with the expression if there
      // is only one, otherwise null (used for convenience in plotting)
      if (associatedClockMap.size()==1) {
         Collection values = associatedClockMap.values();
         Iterator it = values.iterator();
	 associatedClock = (SimClock)it.next();
      } else
         associatedClock = null;
	 
      return associatedClockMap;	 
   }
   
   /**
    * Return true if this represents a boolean value
    * @return True if this represents a boolean value
    */
   public boolean isBoolean () {
      return nodeValue!=null && nodeValue.isBoolean();
   }      

   /**
    * Return true if this represents an integer boolean
    * @return True if this represents an integer value
    */
   public boolean isInt () {
      return nodeValue!=null && nodeValue.isInt();
   }      
                
   /**
    * Return true if this represents a numeric value
    * @return True if this represents a numeric value
    */
   public boolean isNumeric () {
      return nodeValue!=null && nodeValue.isNumeric();
   }      
                
   /**
    * Generate constant and literal values, resolve variable expressions to SimValues and SimClocks,
    * expand wildcard identifier names.
    * @throws SimExprParseException If an identifier cannot be resolved
    */
   public void resolve () throws SimExprParseException {

      SimExprSimpleNode child;
               
      switch (id) {

      case JJTCONSTANT:
         switch (token.kind) {
	 case PI:
	    nodeValue = new SimExprNodeValue(FLOAT);
	    nodeValue.put(Math.PI);
	    break;
         case E:
	    nodeValue = new SimExprNodeValue(FLOAT);
	    nodeValue.put(Math.E);
	    break;
         case NULL:
	    nodeValue = new SimExprNodeValue(NULL_TYPE);
	    break;
         }
	 break;	 	    

      // Identifier: clock or variable. Generate reference to it.	      	 	          
      case JJTIDENTIFIER:	 	 
         if (sim!=null) {
	 
	    // If identifier is name of a clock, take as a clock, else take as a variable
	    SimIdentifier sid;
	    if (sim.existsClock(token.image))
               sid = sim.getClock (token.image);
            else if ((sid = sim.getVariable (token.image))==null)
	       throw new SimExprParseException("variable "+token.image+" does not exist");
	    nodeValue = new SimExprNodeValue(sid);

	    // If the identifier name had an @ prefix, check it represents a queue or a ram
	    if (isBufferView() && !(isQueue() || isCram() || isRram()))
	       throw new SimException("an @ prefix can only be applied to a queuebuffer or ram variable");
	       
	    // If this variable is a queuebuffer data output, create two child nodes
	    // representing the associated read and write availability variables respectively.
	    // A queue value expression is undefined at evaluation time if the read availability
	    // variable is false.
	    if (isQueue()) {
	    
	       // Read availability variable
	       child = newNode(JJTIDENTIFIER, IDENTIFIER, token.image+".NE");
	       jjtAddChild(child, 0);
	       child.resolve(); 
	       
	       // Write availability variable
	       child = newNode(JJTIDENTIFIER, IDENTIFIER, token.image+".RA");
	       jjtAddChild(child, 1);
	       child.resolve();
	       
	       // If the bufferView flag is set we resolve the buffer 'variable' later in eval(). 
	    }
	     
         } else
	    throw new SimExprParseException(
	       "identifiers cannot be accessed unless parser runs in simulator");
         break;

      // Variable expression. Contains a number of children. The names of the first few (or all) may
      // represent an identifier which resolves to a clock or variable. At the least, the first child
      // must resolve. Subsequent children represent struct fields and/or array subscripts. A clock
      // identifier cannot have struct fields or array subscripts. Array subscripts cannot contain
      // a variable range, g. the var exp a[1..b] is invalid. Single array subscripts may contain
      // a variable, g. a[b] is valid.
      // The node value created for a var exp node references the identifier (clock/variable)
      // represented by the first child.
      case JJTVAREXP:

	 // Handle variable names containing ".", which occur for most variables
	 // g. glob.a and also for queue and static special fields .PUSH, .CE, .D etc. Further, a clock
	 // with name C.c100 must be resolved as a clock but C.c100.start must be resolved as a
	 // variable.
	 // Do this by concatenating the names of all children up to but not including the first array
	 // subscript child, if present. This String is a potential variable name. Attempt to resolve
	 // to a clock or variable, and if found, then collapse all children names which contributed to the new
	 // clock/variable name into the first child, and discard those other children. If the variable
	 // cannot be resolved, attempt the process again with a concatenated name String that does
	 // not contain the last child. Continue until the clock/variable is resolved or none can be
	 // resolved. The result is an valid indentifier child, which resolves to a clock or variable,
	 // followed by struct fields or array subscripts. If there is only one child, this var exp node
	 // is replaced by the child identifier node..
	 
	 // Find, from start, index of last child+1 which is not an array subscript
	 int end;
	 for (end=1; end<jjtGetNumChildren(); end++)
	    if (children[end].id==JJTARRAYSUBSCRIPT)
	       break;

         // Build potential variable names starting with the longest, try to resolve to a clock/variable.
	 // If fails, try again with last field removed. Continue until variable resolved or cannot
	 // resolve first child.
	 String name, saveName = children[0].token.image;
         for (int i=end; i>0; i--) {
	    name = saveName;
	    for (int j=1; j<i; j++)
	       name += "."+children[j].token.image;
            children[0].token.image = name;
	    try {
	       children[0].resolve();
	       for (int k=1; k<i; k++)
	          jjtRemoveChild(1);
	       break;
            } catch (SimExprParseException e) {
               if (i==1)
	          throw(e);
	    }
         }

	 // If this node has a single child, turn it into an identifier node based on the child..
	 if (jjtGetNumChildren()==1) {
	    id = JJTIDENTIFIER;
	    token = children[0].token;
	    nodeValue = children[0].nodeValue;
	    bufferView = children[0].isBufferView();
	    children = children[0].children;  
	 }

	 // If this node represents a clock, error (clock doesn't have fields or array subscripts)
	 else if (children[0].nodeValue.isClock())
	    throw new SimException("a clock cannot have fields or array subscripts");
	 
	 // ..else it's a variable with struct fields and/or array subscripts
	 else {

	    // Check/get type of remaining children
	    for (int i=1; i<jjtGetNumChildren(); i++)
	       children[i].getType();

            // Disallow variable array subscripts or variable subscript ranges (a range is variable
	    // if at least one of the range limits is a variable). This is necessary so we can evaluate
	    // the var exp now and determine its type, which is used in getType() by this node's ancestors.
	    if (hasVariableSubscriptRange() || hasVariableSubscript(1))
	       throw new SimExprParseException("array subscripts cannot be variable");

            // Point node value to first child's node value (root variable)
	    nodeValue = children[0].nodeValue;

	    // Evaluate now to resolve the SimValue which is the result of the var exp,
	    // and check validity. Ignore queue availability.
	    try {
	       evalVarExp(false);
            } catch (SimException e) {
	       throw new SimExprParseException(e);
	    }	        
         }
         break;      
      
      // Struct field: store the field name as a String
      case JJTSTRUCTFIELD:
         nodeValue = new SimExprNodeValue(STRING);
	 nodeValue.put(token.image);
	 break;
	 
      case JJTINTEGERLITERAL:
	 int radix;
	 String trimmed = token.image;
         nodeValue = new SimExprNodeValue(INT);
	 
	 // Determine radix and remove hex, binary or octal prefix
	 if (token.image.matches("^0[xX].+")) {
	    trimmed = token.image.substring(2);
	    radix = 16;
         } else if (token.image.matches("^0[bB].+")) {
	    trimmed = token.image.substring(2);
	    radix = 2;	 	    
	 } else if (token.image.matches("^0.+")) {
	    trimmed = token.image.substring(1);
	    radix = 8;
         } else
	    radix = 10;
	 
	 // Remove L suffix if present; always parse as a long
        if (token.image.matches(".*[lL]$"))
	    trimmed = trimmed.substring(0, trimmed.length()-1);
         nodeValue.put(Long.parseLong(trimmed, radix));
	 break;
	 
      case JJTFLOATINGLITERAL:
         // Always parsed as double regardless of optional type suffix (f,F,d,D)
         nodeValue = new SimExprNodeValue(FLOAT);
         nodeValue.put(Double.parseDouble(token.image));
	 break;
	 
      case JJTBOOLEANLITERAL:
         nodeValue = new SimExprNodeValue(
	    (token.image.equals("true") || token.image.equals("false"))?LOG:CONTROL);
         nodeValue.put(Boolean.getBoolean(token.image));
	 break;

      case JJTFORMATSPEC:
      case JJTSTRINGLITERAL:
      case JJTIDENTGROUP:
      case JJTWORD:
         nodeValue = new SimExprNodeValue(STRING);
         nodeValue.put(token.image);
	 break;

      // The wildcard identifier in a wildcard node is expanded according
      // to the context, ie the parent node. A child node is created for
      // each match. The type of the child node is JJTIDENTIFIER if the wildcard
      // is in the context of a print, show or (break, display or format) add
      // command. Otherwise the type of the child node is JJTSTRINGLITERAL
      // and it is assumed to be in the context of a (break, display or format)
      // remove command. The new child JJTIDENTIFIER nodes are automatically
      // resolved and used in parent node type checking (g. to check that 
      // all expressions are boolean during a break add). The new JJTSTRINGLITERAL
      // nodes are not used in parent type checking but are simply used to
      // remove break, display or format table entries in eval().
      // Note that all wildcard nodes are replaced by their children in the
      // default case below.
      case JJTWILDCARD:
         String[] matches=null;
         SimExprSimpleNode p = parent;
	 int nodeType=0, tokenType=0;
	 
	 // If doing a print, show, plot or adding (a break, display or format),
	 // expand the wildcard against the identifierMap..
	 if (p.id==JJTPRINTCMD || p.id==JJTSHOWCMD || p.id==JJTPLOTCMD ||
	     p.token.kind == ADDCMD) {
	    matches = sim.identifierMatch(token.image);
	    nodeType = JJTIDENTIFIER;
	    tokenType = IDENTIFIER;
         }
	 	    
         // ..else doing a rem, expand wildcard	against appropriate map   
         else {
	    switch (p.id) {
	    case JJTBREAKCMD:
	       matches = sim.breakMatch(token.image);
	       break;
	    case JJTDISPCMD:
	       matches = sim.displayMatch(token.image);
	       break;
	    case JJTFORMATCMD:
	       matches = sim.formatMatch(token.image);
	       break;
            }
	    nodeType = JJTSTRINGLITERAL;
	    tokenType = STRING_LITERAL;
         }
	 	    
	 // Make identifier or string child node for each wildcard match
	 if (matches!=null && matches.length>0) {
            for (int i=0; i<matches.length; i++) {
	       child = newNode(nodeType, tokenType, matches[i]);
               jjtAddChild(child, i);
            }
         }	       
         nodeValue = new SimExprNodeValue(STRING);
         nodeValue.put(token.image);
         break;

      default:
         for (int i=0; i<jjtGetNumChildren(); i++) {
	    child = children[i];
	    child.resolve();
	    
            // If child was a wildcard identifier, replace it with its children
            if (child.id==JJTWILDCARD) {
               jjtRemoveChild(i);
               SimExprNode orphan;
               for (int j=0; child.jjtGetNumChildren()>0; j++) {
                  orphan = child.jjtRemoveChild(0);
                  jjtInsertChild(orphan, i+j);
               }
	       // Point to first new child for next iteration
               i--; 
            }
         }	    
      }	    	 
   }
   
   /**
    * Convert the children[] array into a parent-child tree. The last node in the original children[]
    * becomes the only child. The second last node in the original children[] becomes the first child
    * of this only child, and so on until the first node in the original children[] has become a
    * leaf on the new descendant tree. This method is used to change the tree structure for most
    * binary operator nodes to provide greater efficiency at eval() time.
    */
   public void reverseChildren () {
      SimExprNode orphan;
      if (children!=null) {
	 while (children.length > 1) {
            orphan = jjtRemoveChild(0);
            jjtGetChild(0).jjtInsertChild(orphan, 0);
	 }
      }	 
   }         

   /**
    * Set the node id (type)
    * @param id Node type
    */
   public void setId( int id) {
      this.id = id;
   }
                   
   /**
    * Set a reference to the associated token
    * @param token A SimExprToken
    */
   public void setToken(SimExprToken token) {
      this.token = token;
   }

   /**
    * Return string with node details
    * @return Node type name and token string, if present
    */
   public String toString() { 
      String s = SimExprTreeConstants.jjtNodeName[id];
      if (token!=null && token.image!=null)
         s = s + " ["+token.image+"]";
      return s;	
   }

   /**
    * Return string with node details, including specified prefix
    * @param prefix A String to prepend to the node details, or null
    * @return Node type name and token string, if present
    */
   public String toString(String prefix) { return prefix + toString(); }

   /**
    * Cut redundant nodes out of the descendant tree from this node.
    * Redundancy is indicated by a null token and only one child.
    * Replace each redundant node with its (only) child.
    */
   public void trim () {
      SimExprSimpleNode child, grandchild; 
      int i, nc = jjtGetNumChildren();
      
      if (nc==0)
         return;

      for (i=0; i<nc; i++) {
         child = children[i];
         while ((child.token==null) && (child.jjtGetNumChildren()==1)) {
	    grandchild = (SimExprSimpleNode)child.jjtGetChild(0);
	    jjtAddChild(grandchild, i);
	    grandchild.jjtSetParent(this);
	    child = grandchild;
         }
         child.trim();
      }	    
   }
                   
   // Evaluate a varexp node and return the SimValue it refers to. This may be a full or partial
   // variable
   // @param checkAvailability If true, throw exception if (queuebuffer) variable not available for read
   // @return The SimValue described by the var exp
   //
   private SimValue evalVarExp (boolean checkAvailability) {
   
      // Get reference to variable and generate specs list (subscripts, struct fields)
      ArrayList specs = new ArrayList();
      SimValue v = null;
      SimExprSimpleNode child;
      for (int i=0; i<children.length; i++) {
	 child = children[i];
	 switch (child.id) {
	 // Identifier: get reference to variable's SimValue, or queue/ram internal buffer
	 // if this expression is a buffer view.
	 case JJTIDENTIFIER:
	    child.nodeValue.replaceVal(child.nodeValue.getVariable().getValue()); // get orig value
	    if (checkAvailability || child.isBufferView())
	       child.eval();
	    v = child.nodeValue.getValue();
	    break;
	 // Array subscript		  
	 case JJTARRAYSUBSCRIPT:
	    child.eval();
	    // If subscript node has no children, it represents an empty subscript..
	    if (child.jjtGetNumChildren()==0)
	       specs.add(null);
	    // ..else if type is RANGE, the subscript represents a subscript range.. 
            else if (child.nodeValue.getType()==SimExprNodeValue.RANGE)
	       specs.add(child.nodeValue.getRange());		     		     
            // ..else represents a single integer subscript
	    else
	       specs.add(new Integer((int)child.nodeValue.getDouble()));
	    break;		     
	 // Struct field name
	 case JJTSTRUCTFIELD:
	    child.eval();
	    specs.add(child.token.image);
	    break;
	 }
      }	
      return v.getPart(specs);       		  
   }

   // Return a SimExprSimpleNode[] of the child nodes which are not string literals. Return null
   // if there are no such children. Used by trace/plot commands.
   // @return SimExprSimpleNode[] of the non-stringLiteral children, or null if there are no such children
   //
   private SimExprSimpleNode[] getExprs () {
      SimExprSimpleNode[] exprs = null;
      ArrayList exprList = new ArrayList();
      SimExprSimpleNode child;
      
      if (children!=null) {
         for (int i=0; i<children.length; i++) {
	    child = children[i];
	    if (child.isString())
	       continue;
	    exprList.add(child);
         }
      }
      if (exprList.size()>0)
	 exprs = (SimExprSimpleNode[])exprList.toArray(new SimExprSimpleNode[0]);
      return exprs;
   }
   
   // Return a String[] of the child Strings, which start at children[0]. Some other
   // non-String children may remain after these. Return null if there are no String children.
   // Used by trace/plot commands.
   // @return String[] of the child Strings, or null if there are no children
   //
   private String[] getNames () {
      String[] names = null;
      ArrayList nameList = new ArrayList();
      SimExprSimpleNode child;
      
      if (children!=null) {
         for (int i=0; i<children.length; i++) {
	    child = children[i];
	    if (!child.isString())
	       continue;
	    nameList.add(child.token.image);
         }
      }
      if (nameList.size()>0)
	 names = (String[])nameList.toArray(new String[0]);
      return names;
   }
   
   // Return a String[] of the child Strings or integer expressions (as Strings), which
   // start at children[0]. Some other children of other types may remain. Return null
   // if there are no children of the required type. Used by trace/plot commands.
   // @return String[] of the child Strings and integer expression results (as Strings)
   //
   private String[] getNamesOrIndices () {
      String[] names = null;
      ArrayList nameList = new ArrayList();
      SimExprSimpleNode child;
   
      if (children!=null) {
         for (int i=0; i<children.length; i++) {
	    child = children[i];
	    if (child.isString())
	       nameList.add(child.token.image);
            else if (SimType.isInt(child.nodeValue.getType()))
	       nameList.add(child.eval().print("%d"));
         }	       
      }	       
      if (nameList.size()>0)
	 names = (String[])nameList.toArray(new String[0]);
      return names;
   }
   		  
   // Determine whether a JJTVAREXP node, or any of its descendants has a
   // variable array subscript. A variable subscript is indicated by a
   // descendant identifier node, EXCEPT for the first child (identifier)
   // node of the JJTVAREXP node. This is handled by passing startChild=1
   // in the initial call.
   // @param startChild The index in the child node list at which to start
   //        checking descendant nodes. Set to 1 in initial call.
   // @return True if this JJTVAREXP node has at least one variable array subscript
   //
   private boolean hasVariableSubscript (int startChild) {

      // If an identifier, is part of a variable subscript
      if (id==JJTIDENTIFIER)
         return true;

      // Otherwise check all descendants for variable subscript
      boolean b = false;      	 	 
      for (int i=startChild; i<jjtGetNumChildren(); i++)
         b |= children[i].hasVariableSubscript(0);	 

      return b;
   }

   // Determine whether a JJTVAREXP node, or any of its descendants has a
   // variable array subscript range. A variable subscript is indicated by a
   // descendant range expression node containing two children, at least one
   // of which involves an identifier.
   // @return True if this JJTVAREXP node has at least one variable array subscript
   //
   private boolean hasVariableSubscriptRange () {
   
      // A variable subscript range is indicated by a range expression
      // containing two children, at least one of which involves an identifier
      if (id==JJTRANGEEXP && jjtGetNumChildren()==2 &&
          (children[0].hasVariableSubscript(0) ||
           children[1].hasVariableSubscript(0)))
         return true;	  
	  
      // Otherwise check all descendants for variable subscript range
      boolean b = false;      	 	 
      for (int i=0; i<jjtGetNumChildren(); i++)
         b |= children[i].hasVariableSubscriptRange();	 

      return b;
   }
   
   // Return true if this node represents a combinatorial ram output variable identifier
   // or a var expression involving one.
   // @return True if this node represents a combinatorial ram output  variable identifier
   // or a var expression involving one.
   //
   private boolean isCram () {
      switch (id) {
      case JJTIDENTIFIER:
	 return nodeValue.isCram();
      case JJTVAREXP:
         return children[0].isCram();	 
      }
      return false;
   }
      
   // Return true if this node represents a queue variable identifier
   // or a var expression involving one.
   // @return True if this node represents a queue variable identifier
   // or a var expression involving one.
   //
   private boolean isQueue () {
      switch (id) {
      case JJTIDENTIFIER:
	 return nodeValue.isQueue();
      case JJTVAREXP:
         return children[0].isQueue();	 
      }
      return false;
   }
      
   // Return true if this node represents a registered ram output variable identifier
   // or a var expression involving one.
   // @return True if this node represents a registered ram output  variable identifier
   // or a var expression involving one.
   //
   private boolean isRram () {
      switch (id) {
      case JJTIDENTIFIER:
	 return nodeValue.isRram();
      case JJTVAREXP:
         return children[0].isRram();	 
      }
      return false;
   }
      
   // Return true if this node represents String data of some type
   // @return True if this node represents String data of some type
   //
   private boolean isString () {
      return id==JJTSTRUCTFIELD ||
             id==JJTFORMATSPEC ||
	     id==JJTSTRINGLITERAL ||
	     id==JJTIDENTGROUP ||
	     id==JJTWORD;
   }      

   // Create a new SimExprSimpleNode of specified type, token type and token image
   // @param id SimExprSimpleNode type to create
   // @param tokenKind Associated SimExprToken kind to create, or -1 for null token
   // @param tokenImage String image for token, or null (ignored if tokenKind<0)
   // @return A new SimExprSimpleNode
   //
   private SimExprSimpleNode newNode (int id, int tokenKind, String tokenImage) {
      SimExprSimpleNode n = new SimExprSimpleNode(id);
      if (tokenKind>=0) {
         n.token = SimExprToken.newToken(tokenKind);
         n.token.image = tokenImage;
      }
      return n;	 
   } 
   
   // Set the ignoreAvailability flag for this (var exp or identifier) node and its children.
   // This indicates that queue read availability should not be checked before evaluating the queue variable.
   //
   private void ignoreAvailability () {
   
      switch (id) {
      case JJTIDENTIFIER:
         ignoreAvailability = true;
         break;
      case JJTVAREXP:
         children[0].ignoreAvailability();	 
         break;
      default:
         throw new SimException(
	    "SimExprSimpleNode.ignoreAvailability(): invalid node id ("+id+")");	 
      }
   }
   
   // Return true is this (var exp or identifier node) represents a view of a queue or ram internal
   // buffer, rather than the output value.
   //
   protected boolean isBufferView () {
   
      switch (id) {
      case JJTIDENTIFIER:
         return bufferView;
      case JJTVAREXP:
         return children[0].isBufferView();
      default:
         throw new SimException(
	    "SimExprSimpleNode.isBufferView(): invalid node id ("+id+")");	 	 
      }	    
   }   
   
}

