/*
 * 3PL - Parallel Pipeline Programming Language
 *
 * Copyright (C) 2002-2003
 *     CSIRO Manufacturing and Infrastructure Technology
 */

/* Generated By:JJTree: Do not edit this line. SimExprNode.java */

package threepl.simulator;

/** 
 * All AST nodes must implement this interface.  It provides basic
 * machinery for constructing the parent and child relationships
 * between nodes.
 *
 * @version $Revision: 451 $
 * @author Generated by JJTree, modified Andrew Tulloh
 */
public interface SimExprNode {

  /**
   * This method is called after the node has been made the current
   * node.  It indicates that child nodes can now be added to it.
   */
  public void jjtOpen();

  /**
   * This method is called after all the child nodes have been added.
   */
  public void jjtClose();

  /** 
   * This pair of methods are used to inform the node of its parent.
   */
  public void jjtSetParent(SimExprNode n);
  public SimExprNode jjtGetParent();

  /**
   * This method tells the node to add its argument to the node's
   * list of children. 
   */
  public void jjtAddChild(SimExprNode n, int i);

  /** 
   * This method returns a child node.  The children are numbered
   * from zero, left to right.
   */
  public SimExprNode jjtGetChild(int i);

  /**
   * Return the number of children the node has.
   */
  public int jjtGetNumChildren();
  
  /**
   * Remove a child node
   */
  public SimExprNode jjtRemoveChild (int i);

  /**
   * Insert a child node
   */
  public void jjtInsertChild ( SimExprNode child, int i );  
}
