package threepl.exec;

import static threepl.ThreePL.tdelist;
import static threepl.ThreePL.getModuleScope;

import java.util.ArrayList;
import java.util.Iterator;
import java.util.HashMap;
import java.util.HashSet;

import threepl.codegen.TDE;
import threepl.codegen.TDEConstants;
import threepl.codegen.TDEVar;
import threepl.exceptions.ExEx;
import threepl.parser.Constant;
import threepl.parser.SrcLoc;

/**
 * This class represents a collection of queue references.
 * It is used in the generation of queue acknowledgements. Queue availability
 * may be conditional on a signal; the test operand for a ?: operator
 * or a selection input to a select() function.
 *
 * <p>Field 'write_queues' is a (possibly empty) set containing the queue
 * variables (Var) whose write availability is required. This is used by
 * sync{}.
 *
 * Field 'read_queues' is a (possibly empty) set containing the queue
 * variables (Var) whose read availability is required. This is used by
 * sync{}.
 *
 * <p>Field 'read_ands' is a set of queues and conditional signals which are
 * all to be used to form availability and acknowledge expressions. This
 * field is a set of set pairs, the pair being a queue variable set and a
 * conditional signal set. For each set entry the queue and signal sets are
 * all ANDed together to form one term. The terms for each position in the
 * lists are ORed together. Sets are used for the queues and signals to be
 * ANDed to avoid duplicate entries.
 *
 * <p>When a write queue is ANDed to this queue reference by method 'and_set'
 * it is added to the 'write_queues' set.
 *
 * <p>When a read queue is ANDed to this queue reference by method 'and_set' it
 * is added to the 'read_queues' set. If set 'read_ands' is empty the queue is
 * added as a new pair otherwise it is added to every queue set in list
 * 'read_ands'.
 *
 * <p>When a conditional signal is ANDed to this queue reference by method 'and'
 * it is added to every signal set in list 'read_ands'.
 *
 * <p>When another queue reference is ANDed to this queue reference by method
 * 'and_set', if this queue reference 'read_ands' set is not empty the
 * product of the two queue references is generated by taking each
 * combination of list indices from each queue reference and taking a union
 * of the sets. If this queue reference 'read_ands' set is empty the queue
 * reference is copied.
 *
 * <p>When another queue reference is ORed to this queue reference by method 'or'
 * the lists are appended.
 *
 * <p>This process of multiplying through each time means that we maintain
 * the queue dependencies as a sum of products, no deeper.
 *
 */
public class QueueRefs implements Constant, TDEConstants {
    private HashSet<Queue>          write_queues = new HashSet<Queue>();
    private HashSet<Queue>          read_queues = new HashSet<Queue>();
    private HashSet<Queue>          write_av_queues = new HashSet<Queue>();
    private HashSet<Queue>          read_av_queues = new HashSet<Queue>();
    private ArrayList<SetPair>      read_ands = new ArrayList<SetPair>();    
    private HashMap<Scope,Val>      bqavails = new HashMap<Scope,Val>();
    private TDEVar                  ubqwavails;
    private TDEVar                  ubqravails;
    private HashMap<Scope,Val>      syncavails = new HashMap<Scope,Val>();
    private HashMap<Scope,Val>      ravails = new HashMap<Scope,Val>();
    private int                     bwqueues;   // number of buffered queues being written
    private int                     brqueues;   // number of buffered queues being read
    private int                     ubwqueues;  // number of unbuffered queues being written
    private int                     ubrqueues;  // number of unbuffered queues being read

    /**
     * This class holds a pair of sets representing an availability expression.
     * The set in field queues is a set of queue variables. The set in field sigs
     * is a set of TDEVar conditional signals. The class represents the logical
     * product of the elements in both sets. Instances of this set are stored
     * in another set, field read_ands in class QueueRefs, which represents
     * products to be ORed.
     */
    public class SetPair {
        HashSet<Queue>      queues = new HashSet<Queue>();
        HashSet<CondSig>    sigs = new HashSet<CondSig>();
        boolean             remove;

        /**
         * Construct an empty set pair.
         */
        public SetPair () {
        }
        
        /**
         * Construct a set pair.
         * @param   hsp is a set of queue variables
         * @param   hss is a set of conditional signals
         */
        public SetPair (HashSet<Queue> hsp, HashSet<CondSig> hss) {
            queues = hsp;
            sigs = hss;
        }
        
        /**
         * Copy a set pair.
         * @param   s is a pair of availability sets
         */
        public SetPair (SetPair s) {
            queues.addAll(s.queues);
            sigs.addAll(s.sigs);
        }
        
        /**
         * Compute the hash code for this set pair.
         * @return the hash code value.
         */
        public int hashCode () {
            if (sigs != null)
                return(queues.hashCode() + sigs.hashCode());
            else
                return(queues.hashCode());
        }
        
        /**
         * Equality check.
         * @param   o is the object to be checked for equality.
         * @return  true if the argument is equal to this set pair
         */
        public boolean equals (Object o) {
            if (!(o instanceof SetPair))
                return(false);
            SetPair sp = (SetPair)o;
            if (sp == this)
                return(true);
            if (sigs != null) {
                if (sp.sigs == null)
                    return(false);
                if(!sigs.equals(sp.sigs))
                    return(false);
            } else if (sp.sigs != null)
                return(false);
            return(queues.equals(sp.queues));
        }
        
        /**
         * Check that the queue set within a set pair is empty.
         * @return  true if the queue set within a set pair is empty
         */
        public boolean hasNoQueues () {
            return(queues.isEmpty());
        }
    }
    
    /**
     * This class wraps a signal with an inversion flag.
     * This allows inverted instances of a signal to be equated, otherwise
     * separate instances of inverters will be seen.
     */
    public class CondSig {
        TDEVar  sig;
        boolean inverted;
        
        /**
         * Construct a flagged signal.
         * @param   v is the signal to be optionally inverted
         * @param   inv is true if the enclosed signal is to be inverted
         */
        public CondSig (TDEVar v, boolean inv) {
            sig = v;
            inverted = inv;
        }
        
        /**
         * Compute the hash code.
         * @return the hash code value.
         */
        public int hashCode () {
            return(sig.hashCode() + (inverted ? 1 : 0));
        }
        
        /**
         * Equality check.
         * @param   o is the object to be checked for equality.
         * @return  true if the argument is equal to this
         */
        public boolean equals (Object o) {
            if (!(o instanceof CondSig))
                return(false);
            CondSig cs = (CondSig)o;
            if (cs == this)
                return(true);
            return((inverted == cs.inverted) && sig.equals(cs.sig));
        }
        
        /**
         * Inversion check.
         * @param   s is the conditional signal to be checked for inversion.
         * @return  true if the argument is the inversion of this
         */
        public boolean inversionof (CondSig s) {
            return(sig.equals(s.sig) && (inverted ^ s.inverted));
        }
        
        /**
         * Get the signal. If the inversion flag is true an inverter
         * is constructed and its output returned.
         * @param   loc is the source file location
         * @return  the signal or inverted signal
         */
        public TDEVar getSignal (SrcLoc loc) {
            if (!inverted)
                return(sig);
            TDE     invert  = new TDE(TDEType.INV, loc);
            invert.add2i(sig);
            return(invert.finish());
        }
    }
    
    /**
     * Construct an empty queue reference.
     */
    public QueueRefs () {
        //read_ands.add(new SetPair());
    }
    
    /**
     * Clear queue references.
     */
    public void clear () {
        write_queues = new HashSet<Queue>();
        read_queues = new HashSet<Queue>();
        read_ands = new ArrayList<SetPair>();
    }

    private void clearAvails () {
        bqavails.clear();
        ubqwavails = null;
        ubqravails = null;
        syncavails.clear();
        ravails.clear();
    }
       
    /**
     * Check if there are any queue references.
     * @return   true if there are no queue references
     */
    public boolean isEmpty () {
        for (SetPair sp : read_ands)
            if (!sp.hasNoQueues())
                return(false);
        return(write_queues.isEmpty() && read_queues.isEmpty());
    }
    
    /**
     * Get the set of queue reads.
     * @return   the set of queue reads
     */
    public HashSet<Queue> getReads () {
        return(read_queues);
    }
    
    /**
     * Get the set of queue writes.
     * @return   the set of queue writes
     */
    public HashSet<Queue> getWrites () {
        return(write_queues);
    }
    
    /**
     * Check if there is a single queue write reference only (i.e.
     * there are no queue subscripts to a LHS queue variable).
     * @return   true if there is a single queue write reference only
     */
    public boolean isSingleWrite () {
        return(read_queues.isEmpty() && (write_queues.size() == 1));
    }
    
    /**
     * AND a queue variable availability requirement.
     * @param   v is the queue variable
     * @param   write is true if queue write availability (rather than read)
     *          is required
     * @param   loc is the source file location
     */
    public void and_set (Queue v, boolean write, SrcLoc loc) {
        clearAvails();
        if (write) {
            write_queues.add(v);
        } else {
            read_queues.add(v);
            if (read_ands.isEmpty()) {
                HashSet<Queue> ps = new HashSet<Queue>();
                HashSet<CondSig> ss = new HashSet<CondSig>();
                ps.add(v);
                read_ands.add(new SetPair(ps, ss));
            } else {
                for (SetPair sp : read_ands)
                    sp.queues.add(v);
            }
            optimise();
            resolveCounts();
        }
    }
    
    /**
     * If there are queue read entries, AND a conditional signal to them.
     * @param   tdev is the conditional signal
     * @param   inv is true if the signal is to be inverted
     * @param   loc is the source file location
     */
    public void and (TDEVar tdev, boolean inv, SrcLoc loc) {
        if (read_queues.isEmpty())
            return;
        if (ubrqueues != 0)
            throw new ExEx("statement has unbuffered queue in ?: operator", loc);
        clearAvails();
        for (SetPair sp : read_ands)
            sp.sigs.add(new CondSig(tdev, inv));
        optimise();
    }
    
    /**
     * AND a queues reference unless this queue reference has no read_ands terms,
     * in which case copy the read_ands terms from the argument queue reference.
     * @param   pr is the queues reference
     * @param   loc is the source file location
     */
    public void and_set (QueueRefs pr, SrcLoc loc) {
        if (pr.isEmpty())
            return;

        if (isEmpty()) {
            write_queues.addAll(pr.write_queues);
            read_queues.addAll(pr.read_queues);
            Iterator<?>    it = pr.read_ands.iterator();
            while (it.hasNext())
                read_ands.add(new SetPair((SetPair)it.next()));
            bqavails.putAll(pr.bqavails);
            ubqwavails = pr.ubqwavails;
            ubqravails = pr.ubqravails;
            syncavails.putAll(pr.syncavails);
            ravails.putAll(pr.ravails);
            resolveCounts();
            return;
        }
        
        clearAvails();

        write_queues.addAll(pr.write_queues);

        if (pr.read_queues.isEmpty()) {
            resolveCounts();
            return;
        }
            
        read_queues.addAll(pr.read_queues);
        ArrayList<SetPair>  ra = new ArrayList<SetPair>();
        if (read_ands.isEmpty())
            read_ands.addAll(pr.read_ands);
        else {
            for (SetPair sp1 : read_ands) {
                for (SetPair sp2 : pr.read_ands) {
                    HashSet<Queue> ps = new HashSet<Queue>();
                    HashSet<CondSig> ss = new HashSet<CondSig>();
                    ps.addAll(sp1.queues);
                    ps.addAll(sp2.queues);
                    ss.addAll(sp1.sigs);
                    ss.addAll(sp2.sigs);
                    ra.add(new SetPair(ps, ss));
                }
            }
            read_ands = ra;
        }
        
        read_av_queues.addAll(pr.read_av_queues);
        write_av_queues.addAll(pr.write_av_queues);
        
        optimise();
        resolveCounts();
    }
    
    /**
     * OR a queue variable availability requirement.
     * @param   v is the queue variable
     * @param   write is true if queue write availability (rather than read)
     *          is required
    public void or (Var v, boolean write) {
        clearAvails();
        if (write) {
            write_queues.add(v);
        } else {
            read_queues.add(v);
            HashSet ps = new HashSet();
            HashSet ss = new HashSet();
            ps.add(v);
            read_ands.add(new SetPair(ps, ss));
        }
    }
     */
    
    /**
     * OR a conditional signal.
     * @param   tdev is the conditional signal
     * @param   inv is true if the signal is to be inverted
     * @param   loc is the source file location
     */
    public void or (TDEVar tdev, boolean inv, SrcLoc loc) {
        if (ubrqueues != 0)
            throw new ExEx("statement has unbuffered queue in ?: operator", loc);
        clearAvails();
        HashSet<Queue> ps = new HashSet<Queue>();
        HashSet<CondSig> ss = new HashSet<CondSig>();
        ss.add(new CondSig(tdev, inv));
        read_ands.add(new SetPair(ps, ss));
        optimise();
    }
     
    /**
     * OR a queues reference.
     * @param   pr is the queues reference
     * @param   loc is the source file location
     */
    public void or (QueueRefs pr, SrcLoc loc) {
        if (pr.isEmpty())
            return;

        if (ubrqueues != 0)
            throw new ExEx("statement has unbuffered queue in ?: operator", loc);
        Iterator<?>    it;
        if (isEmpty()) {
            write_queues.addAll(pr.write_queues);
            read_queues.addAll(pr.read_queues);
            it = pr.read_ands.iterator();
            while (it.hasNext())
                read_ands.add(new SetPair((SetPair)it.next()));
            bqavails.putAll(pr.bqavails);
            ubqwavails = pr.ubqwavails;
            ubqravails = pr.ubqravails;
            syncavails.putAll(pr.syncavails);
            ravails.putAll(pr.ravails);
            resolveCounts();
            return;
        }

        clearAvails();
        
        write_queues.addAll(pr.write_queues);

        read_queues.addAll(pr.read_queues);
        it = pr.read_ands.iterator();
        while (it.hasNext())
            read_ands.add(new SetPair((SetPair)it.next()));
        resolveCounts();
    }

    /**
     * Test a QueueRefs against this one for an overlap of the set of
     * queue reads. If there is an overlap, return true.
     * @param   pr the QueueRefs to test against this one
     * @return  true if an overlap of reads, false otherwise
     */
    public boolean readOverlap (QueueRefs pr) {
        HashSet<?>    s = pr.getReads();
        int                 init_size = s.size();
        if (init_size == 0)
            return(false); // body has no queue reads
        s = (HashSet<?>)s.clone();
        HashSet<Queue> ts = read_queues;
        if (ts.size() == 0)
            return(false); // test expression has no queue reads
        for (Queue p: ts)  // iterate through test expression queue reads
            s.remove(p);    // remove from the body set if present
        // if the set of body queue reads is unchanged, OK
        if (s.size() == init_size)
            return(false);
        // if the set of body queue reads is now empty and
        // the body queue writes set is empty, OK
        if ((s.size() == 0) && (pr.getWrites().size() == 0))
            return(false);
        
        return(true);
    }
    
    /**
     * Optimise sum of products.
     */
    private void optimise () {
        int         len;
        SetPair[]   a;
        Iterator<SetPair>    it;

        // Simplify p1 & p2 & ... & s | p1 & p2 &  ... & !s .
        len = read_ands.size();
        a = new SetPair[len];
        a = read_ands.toArray(a);
        for (int i=0 ; i<len ; i++) {
            if (a[i].remove)
                continue;
            HashSet<?> psi = a[i].queues;
            HashSet<?> ssi = a[i].sigs;
            for (int j=i+1 ; j<len ; j++) {
                if (a[j].remove)
                    continue;
                HashSet<?> psj = a[j].queues;
                HashSet<?> ssj = a[j].sigs;
                if (psi.equals(psj) && inversionof(ssi, ssj)) {
                    a[j].remove = true;
                    ssi.clear();
                }
            }
        }
        it = read_ands.iterator();
        while (it.hasNext()) {
            SetPair sp = it.next();
            if (sp.remove)
                it.remove();
        }

        // Eliminate superset terms.
        len = read_ands.size();
        a = new SetPair[len];
        a = read_ands.toArray(a);
        for (int i=0 ; i<len ; i++) {
            if (a[i].remove)
                continue;
            HashSet<?> psi = a[i].queues;
            HashSet<?> ssi = a[i].sigs;
            for (int j=i+1 ; j<len ; j++) {
                if (a[j].remove)
                    continue;
                if (a[j].queues.containsAll(psi) && a[j].sigs.containsAll(ssi))
                    a[j].remove = true;
            }
        }
        it = read_ands.iterator();
        while (it.hasNext()) {
            SetPair sp = it.next();
            if (sp.remove)
                it.remove();
        }
    }
    
    private static boolean inversionof (HashSet<?> ss1, HashSet<?> ss2) {
        if ((ss1.size() != 1) || (ss2.size() != 1))
            return(false);
        Iterator<?>    it;
        it = ss1.iterator();
        CondSig     sig1 = (CondSig)it.next();
        it = ss2.iterator();
        CondSig     sig2 = (CondSig)it.next();
        return(sig1.inversionof(sig2));
    }
   
    /**
     * Remove any queue read references from this queue reference that
     * are common to the argument queue reference.
     * @param   pr is the queues reference
    public void removeCommon (QueueRefs pr) {
        if (pr == null)
            return;

        write_queues.removeAll(pr.write_av_queues);
        
        Iterator    it = read_ands.iterator();
        read_queues.clear();
        while (it.hasNext()) {
            SetPair sp = (SetPair)it.next();
            if (!sp.sigs.isEmpty())
                continue;
            sp.queues.removeAll(pr.read_av_queues);
            if (sp.queues.isEmpty())
                it.remove();
            else
                read_queues.addAll(sp.queues);
        }
    }
     */

    /**
     * Set the read availability check set from a queues reference.
     * The set will be empty prior to this - this method is only called
     * at one place in nodes/ExprNode.java when evaluating the queue read
     * availability operator and the class is newly constructed
     * prior to the call.
     * Queues from both the argument write availability check set and
     * the argument write queues set are added.
     * @param   pr is the queues reference
     */
    public void setReadAVCheck (QueueRefs pr) {
        read_av_queues.addAll(pr.read_av_queues);
        if (pr.read_ands.size() != 1)
            return;
        for (SetPair sp : pr.read_ands)
            read_av_queues.addAll(sp.queues);
    }

    /**
     * Set the write availability check set from a queues reference.
     * The set will be empty prior to this - this method is only called
     * at one place in nodes/ExprNode.java when evaluating the queue write
     * availability operator and the class is newly constructed
     * prior to the call.
     * Queues from both the argument write availability check set and
     * the argument write queues set are added.
     * @param   pr is the queues reference
     */
    public void setWriteAVCheck (QueueRefs pr) {
        write_av_queues.addAll(pr.write_av_queues);
        write_av_queues.addAll(pr.write_queues);
    }
    
    /**
     * Add the read availability check set from a queues reference.
     * @param   pr is the queues reference
     */
    public void addReadAVChecks (QueueRefs pr) { read_av_queues.addAll(pr.read_av_queues); }
    
    /**
     * Add the read availability check set from a Ref or Val.
     * @param   rov is the reference or value
     */
    public void addReadAVChecks (RefOrVal rov) { read_av_queues.addAll(rov.getQueues().read_av_queues); }
    
    /**
     * Add the write availability check set from a queues reference.
     * @param   pr is the queues reference
     */
    public void addWriteAVChecks (QueueRefs pr) { write_av_queues.addAll(pr.write_av_queues); }
    
    /**
     * Add the write availability check set from a Ref or Val.
     * @param   rov is the reference or value
     */
    public void addWriteAVChecks (RefOrVal rov) { write_av_queues.addAll(rov.getQueues().write_av_queues); }

    /**
     * Get the read availability check set.
     * @return  the read availability check set
     */
    public HashSet<Queue> getReadAVChecks () { return(read_av_queues); }

    /**
     * Get the write availability check set.
     * @return  the write availability check set
     */
    public HashSet<Queue> getWriteAVChecks () { return(write_av_queues); }
     
    /**
     * Mark any of the queue variables as used.
     */
    public void setUsed () {
        for (Queue p : write_queues)
            p.setUsed();
        for (Queue p : read_queues)
            p.setUsed();
    }
     
    /**
     * Return a deep copy of this queues reference.
     * @return   the copy of this class
     */
    public QueueRefs copy () {
        QueueRefs    p = new QueueRefs();

        p.write_queues.addAll(write_queues);
        p.read_queues.addAll(read_queues);
        p.write_av_queues.addAll(write_av_queues);
        p.read_av_queues.addAll(read_av_queues);
        p.bqavails.putAll(bqavails);
        p.ubqwavails = ubqwavails;
        p.ubqravails = ubqravails;
        p.syncavails.putAll(syncavails);
        p.ravails.putAll(ravails);
        p.brqueues = brqueues;
        p.bwqueues = bwqueues;
        p.ubrqueues = ubrqueues;
        p.ubwqueues = ubwqueues;

        Iterator<SetPair>    it = read_ands.iterator();
        while (it.hasNext())
            p.read_ands.add(new SetPair(it.next()));

        return(p);
    }
    
    /**
     * Get the availability signal for buffered queues in this queues reference, or null.
     * Null is returned if the queue reference is empty.
     * @param   module_scope is the scope we are in
     * @param   checkedqueues specifies queues which don't need availability checking
     * @param   loc is the source file location
     * @return  the availability value
     */
    public Val getBQAvail (Scope module_scope, QueueRefs checkedqueues, SrcLoc loc) {
        if (read_queues.isEmpty() && write_queues.isEmpty())
            return(null);
        if (module_scope == null)
            module_scope = getModuleScope();
        if (bqavails.containsKey(module_scope))
            return(bqavails.get(module_scope));
        
        TDEVar  tdev = tdelist.signal("AV", loc);
        TDE     or = new TDE(TDEType.OR, loc);
        Val     val = new Val(null, Mode.VALUE, tdev, loc);
        
        if (read_queues.isEmpty() && !write_queues.isEmpty()) {
            // Have only writes to a queues.
            TDE     and = new TDE(TDEType.AND, loc);
            for (Queue p : write_queues) {
                if (p.getBufferSize() == 0)
                    continue;
                // add the queue to the input (write) domain variables for the Val
                val.addIVar(p);
                // If this queue is not already checked add it to the AND gate
                if ((checkedqueues == null) || !checkedqueues.write_av_queues.contains(p))
                    and.add2i(p.getWriteAvailSig(loc));
            }
            if (and.getInputs().size() != 0)
                or.add2i(and.finish());
        } else if (!read_queues.isEmpty()) {
            // Have reads from queues and possibly writes to a queue.
            boolean     skip_check = false;
            if (checkedqueues != null) {
                // More than 1 entry in either means ORed conditions
                // in which case cannot use checkedqueues.
                // Zero entry in either means no optimisation to be done
                // so don't try.
                if ((read_ands.size() != 1) || (checkedqueues.read_ands.size() != 1))
                    checkedqueues = null;
                else {
                    SetPair sp1 = read_ands.get(0);
                    SetPair sp2 = checkedqueues.read_ands.get(0);
                    if (sp1.sigs.isEmpty() && sp2.sigs.isEmpty()) {
                        // Have single entry in both set pair lists and
                        // the signal sets for both are empty - so
                        // see if the body read queues set is equal to or a
                        // subset of the read checked queue set. If true, all
                        // queue reads have already been checked and no further
                        // queue read availability checking is needed.
                        Iterator<?>    it = sp1.queues.iterator();
                        skip_check = true;
                        while (it.hasNext()) {
                            Queue    p = (Queue)it.next();
                            if (sp2.queues.contains(p) || checkedqueues.read_av_queues.contains(p))
                                continue;
                            skip_check = false;
                            break;
                        }
                    }
                }
            }
            for (SetPair sp : read_ands) {
                TDE     and = new TDE(TDEType.AND, loc);
                for (Queue q : write_queues ) {
                    if (q.getBufferSize() == 0)
                        continue;
                    val.addIVar(q);
                    if ((checkedqueues == null) || !checkedqueues.write_av_queues.contains(q)) {
                        and.add2i(q.getWriteAvailSig(loc));
                    }
                }
                for (Queue q : sp.queues) {
                    if (q.getBufferSize() == 0)
                        continue;
                    val.addOVar(q);
                    if (!skip_check && ((checkedqueues == null) || !checkedqueues.read_av_queues.contains(q)))
                        and.add2i(q.getReadAvailSig(module_scope, loc));
                }
                for (CondSig cs : sp.sigs)
                    and.add2i(cs.getSignal(loc));

                if (and.getInputs().size() != 0)
                    or.add2i(and.finish());
            }
        }

        if (or.getInputs().size() == 0)
            return(null);

        or.add2o(tdev);
        tdelist.addTDE(or);
        bqavails.put(module_scope, val);
        return(val);
    }  
    /**
     * Get the availability signal for unbuffered queue reads in this queues reference, or null.
     * Null is returned if the queue reference is empty.
     * @param   module_scope is the scope we are in
     * @param   checkedqueues specifies queues which don't need availability checking (must be empty or null)
     * @param   loc is the source file location
     * @return  the availability signal or null
     */
    public TDEVar getUBQRAvail (Scope module_scope, QueueRefs checkedqueues, SrcLoc loc) {
        if (read_queues.isEmpty() || (ubrqueues == 0))
            return(null);
        if (module_scope == null)
            module_scope = getModuleScope();
        if ((checkedqueues != null) && !checkedqueues.isEmpty())
            throw new ExEx("unbuffered queue encountered within sync", loc);
        if (ubqravails != null)
            return(ubqravails);
        
        TDEVar  tdev = tdelist.signal("UBQRAV", loc);
        
        TDE     and = new TDE(TDEType.AND, loc);
        for (Queue q : read_queues ) {
            if (q.getBufferSize() == 0)
                and.add2i(q.getReadAvailSig(module_scope, loc));
        }
        and.add2o(tdev);
        tdelist.addTDE(and);
        ubqravails = tdev;
        return(tdev);
    }
    
    /**
     * Get the availability signal for an unbuffered queue write in this queues reference, or null.
     * Null is returned if the queue reference is empty.
     * @param   module_scope is the scope we are in
     * @param   checkedqueues specifies queues which don't need availability checking (must be empty or null)
     * @param   loc is the source file location
     * @return  the availability signal or null
     */
    public TDEVar getUBQWAvail (Scope module_scope, QueueRefs checkedqueues, SrcLoc loc) {
        if (write_queues.isEmpty() || (ubwqueues == 0))
            return(null);
        if (module_scope == null)
            module_scope = getModuleScope();
        if ((checkedqueues != null) && !checkedqueues.isEmpty())
                throw new ExEx("unbuffered queue encountered within sync", loc);
        if (ubqwavails != null)
            return(ubqwavails);
        
        TDEVar  tdev = tdelist.signal("UBQWAV", loc);
        
        TDE     and = new TDE(TDEType.AND, loc);
        for (Queue q : write_queues ) {
            if (q.getBufferSize() == 0)
                and.add2i(q.getWriteAvailSig(loc));
        }
        and.add2o(tdev);
        tdelist.addTDE(and);
        ubqwavails = tdev;
        return(tdev);
    }  
    
    /**
     * Get the sync block availability signal for this queues reference, or null.
     * If there are no queue references null is returned. Note that the
     * queue availability does not include any conditional signals
     * (from queues in the 2nd or 3rd arguments of a ?: operator).
     * 
     * This is only called in one place -
     *  nodes/SyncBlock.execute() calls codegen/TDEList.execp() which calls exec/Queue.syncAvail()
     *  which calls exec/QueueRefs.getSyncAvail().
     * 
     * @param   module_scope is the scope we are in
     * @param   checkedqueues lists queues that need not be checked for
     *          availability
     * @param   loc is the source file location
     * @return  the availability value
     */
    public Val getSyncAvail (Scope module_scope, QueueRefs checkedqueues, SrcLoc loc) {
        if (read_queues.isEmpty() && write_queues.isEmpty())
            return(null);
        if (module_scope == null)
            module_scope = getModuleScope();
        if (syncavails.containsKey(module_scope))
            return(syncavails.get(module_scope));

        unbufferedQueues(true, "Sync block", loc);

        TDEVar  and_tdev = tdelist.signal("AV", loc);
        TDE     and = new TDE(TDEType.AND, loc);
        Val     val = new Val(null, Mode.VALUE, and_tdev, loc);

        for (Queue p : write_queues) {
            val.addIVar(p);
            if ((checkedqueues == null) || !checkedqueues.write_av_queues.contains(p))
                and.add2i(p.getWriteAvailSig(loc));
        }
        for (Queue p : read_queues) {
            val.addOVar(p);
            if ((checkedqueues == null) || !checkedqueues.read_av_queues.contains(p))
                and.add2i(p.getReadAvailSig(module_scope, loc));
        }
        if (and.getInputs().size() != 0) {
            and.add2o(and_tdev);
            tdelist.addTDE(and);
            syncavails.put(module_scope, val);
        } else
            return(null);
        
        return(val);
    }
    
    /**
     * Get the read availability signal for a '&lt;' operator for this
     * queues reference. This is only called from one place in method
     * getReadAvailVal() in exec/Val.java which in turn is called from
     * nodes/ExprNode.java when evaluating the read availability operator.
     * @param   module_scope is the scope we are in
     * @param   loc is the source file location
     * @return  the availability value
     */
    public Val getRAvail (Scope module_scope, SrcLoc loc) {
        if (read_queues.isEmpty())
            return(null);
        if (module_scope == null)
            module_scope = getModuleScope();
        if (ravails.containsKey(module_scope))
            return(ravails.get(module_scope));
            
        WordSpec    logws = new WordSpec(1, Ptype.LOG);
        TDEVar      tdev = tdelist.signal("RAV", logws,loc);
        TDE         or = new TDE(TDEType.OR, loc);
        Val         val = new Val(null, Mode.VALUE, tdev, loc);
        
        for (SetPair sp : read_ands) {
            TDE     and = new TDE(TDEType.AND, loc);
            for (Queue p : sp.queues) {
                and.add2i(p.getReadAvailSig(module_scope, loc));
                val.addOVar(p);
            }
            for (CondSig cs : sp.sigs)
                and.add2i(cs.getSignal(loc));
            or.add2i(and.finish());
        }

        or.add2o(tdev);
        tdelist.addTDE(or);
        ravails.put(module_scope, val);

        return(val);
    }

    /**
     * Add the pop logic for the queues referenced in
     * this queue reference.
     * @param   module_scope is the module we are in
     * @param   exec is the pop signal for the queue
     * @param   rpending is the alternative pop signal for the queue
     *          when it is unbuffered (it is really then a READ signal for
     *          synchronising the simultaneous read and write)
     * @param   loc is the source file location
     */
    public void addPops (Scope module_scope, TDEVar exec, TDEVar rpending, SrcLoc loc) {
        if (isEmpty())
            return;
        if (module_scope == null)
            module_scope = getModuleScope();
        for (Queue p : read_queues) {
            TDEVar  or_tdev = tdelist.signal("POP", loc);
            TDE     or = new TDE(TDEType.OR, loc);
            //or_tdev.setWordSpec(new WordSpec(1, 0, Ptype.LOG, null));
            for (SetPair sp : read_ands) {
                if (sp.queues.contains(p)) {
                    TDE     and = new TDE(TDEType.AND, loc);
                    if (p.getBufferSize() == 0) {
                        if (rpending != null)
                            and.add2i(rpending);
                    } else
                        and.add2i(exec);
                    for (CondSig cs : sp.sigs)
                        and.add2i(cs.getSignal(loc));
                    if (and.getInputs().size() != 0)
                        or.add2i(and.finish());
                }
            }
            if (or.getInputs().size() != 0) {
                or.add2o(or_tdev);
                tdelist.addTDE(or);
                p.addPop(module_scope, or_tdev, loc);
            }
        }
    }
    
    /**
     * Examine an instance of the class for queues of zero depth, i.e.
     * unbuffered. If there are no unbuffered queues then false is
     * returned. If allow_one is true and there is a single unbuffered
     * queue then true is returned. If allow_one is true and there is more
     * than one unbuffered queue an exception is thrown using the
     * message argument.
     * @param   allow_one if true directs that one unbuffered queue
     *          is allowed
     * @param   mess is an error message string
     * @param   loc is a source file location
     * @return  true if there is an unbuffered queue and it is allowed
     */
    public boolean unbufferedQueues (boolean allow_one, String mess, SrcLoc loc) {
        if (!haveUnbufferedQueues())
            return(false);
        if (allow_one && ((ubrqueues + ubwqueues) == 1))
            return(true);
        throw new ExEx("multiple unbuffered queues", loc);
    }
    
    /**
     * Traverse the read and write queue lists looking for an
     * asynchronous unbuffered queue.
     * @return  true if there is an asynchronous unbuffered queue
     */
    public boolean asyncUnbufferedQueue () {
        if (!haveUnbufferedQueues())
            return(false);  // no unbuffered queues
        
        for (Queue p : read_queues ) {
            Clock   iclk = p.getQueueWriteClkVar();
            Clock   oclk = p.getOutputClkVar(null);
            if ((iclk != null) && (iclk != oclk))
                return(true);
        }
        for (Queue p : write_queues ) {
            Clock   iclk = p.getQueueWriteClkVar();
            Clock   oclk = p.getOutputClkVar(null);
            if ((iclk != null) && (iclk != oclk))
                return(true);
        }
        return(false);
    }
    
    /**
     * Determine the number of buffered and unbuffered queues
     * in the read set and the write set.
     */
    private void resolveCounts () {
        for (Queue p : read_queues)
            if (p.getBufferSize() == 0)
                ubrqueues++;
            else
                brqueues++;
        for (Queue p : write_queues)
            if (p.getBufferSize() == 0)
                ubwqueues++;
            else
                bwqueues++;
    }
    
    /**
     * Determine if there are unbuffered queues.
     * @return true if there are unbuffered queues
     */
    public boolean haveUnbufferedQueues () { return((ubrqueues != 0) || (ubwqueues != 0)); }
    
    /**
     * Print the fields representing the sum-of-products expression for this
     * queue availability reference.
     * @param   mess is a label to be prepended to the first printed line
     *
    public void dump (String mess) {
        if (isEmpty()) {
            System.out.println(mess + " - empty");
            return;
        }
        StringBuffer    b;
        System.out.println(mess);
        System.out.println("\twrite queues:");
        Iterator<Queue> it = write_queues.iterator();
        while (it.hasNext())
            System.out.println("\t\t" + ((Var)it.next()).getEname());
        System.out.println("\tread queues:");
        it = read_queues.iterator();
        while (it.hasNext())
            System.out.println("\t\t" + ((Var)it.next()).getEname());
        System.out.println("\tread queue terms:");
        for (SetPair sp : read_ands) {
            b = new StringBuffer("\t\t");
            for (Queue p : sp.queues)
                b.append(" " + p.getEname() + ".NE");
            for (CondSig cs : sp.sigs)
                if (cs.inverted)
                    b.append(" !" + cs.sig.toString());
                else
                    b.append(" " + cs.sig.toString());
            System.out.println(b);
        }
    }
    */
}
