#! /usr/bin/env python3

import sys
import os
import math

infname = sys.argv[1:][0]

if infname.endswith('.bit'):
    print("bit file must be compressed")
    os.exit(1)

if not infname.endswith('.bit.gz'):
    design = infname
    infname = infname + '.bit.gz'
else:
    design = infname[0:-7]
outfname = design + "_config.py"
first = True
with open(outfname, 'w', encoding="utf-8") as of:
    of.write("data = bytearray([\n    ")
    with open(infname, 'rb') as bfile:
        count = 0
        bytes = bfile.read()
        for byte in bytes:
            if not first:
                of.write(', ')
            first = False
            if count == 8:
                of.write("\n    ")
                count = 0
            of.write('0x%.2x' % int(byte))
            count = count + 1
    of.write("\n])\n")
