#! /usr/bin/env python3

import sys
import os
import math

prog = os.path.basename(sys.argv[0])
if prog.lower().endswith('.py'):
    prog = prog[:-3]

if len(sys.argv) != 2:
    print('Usage: {} design'.format(prog), file=sys.stderr)
    sys.exit(1)

infname = sys.argv[1]
if infname.lower().endswith('.bit'):
    print("bit file must be compressed")
    sys.exit(1)
if not infname.lower().endswith('.bit.gz'):
    design = infname
    infname = infname + '.bit.gz'
else:
    design = infname[0:-7]
if not os.path.isfile(infname):
    print('{} not found or not a regular file'.format(infname), file=sys.stderr)
    sys.exit(1)
outfname = design + "_config.py"

first = True
with open(outfname, 'w', encoding="utf-8") as of:
    of.write("data = bytearray([\n    ")
    with open(infname, 'rb') as bfile:
        count = 0
        bytes = bfile.read()
        for byte in bytes:
            if not first:
                of.write(', ')
            first = False
            if count == 8:
                of.write("\n    ")
                count = 0
            of.write('0x%.2x' % int(byte))
            count = count + 1
    of.write("\n])\n")
