#! /usr/bin/env python3

import os
import sys

sys.path.append(os.environ['HOME'] + "/install/3pl/lib/python3")
import info2py

prog = os.path.basename(sys.argv[0])
if prog.lower().endswith('.py'):
    prog = prog[:-3]

if len(sys.argv) != 2:
    print('Usage: {} design'.format(prog), file=sys.stderr)
    sys.exit(1)

design = sys.argv[1]
info2py.info_from_file(design)
sys.exit()
