#! /usr/bin/env python3

import string
import textwrap
import argparse
import json
import sys
import time
import os
import math
from io import StringIO
if __name__ != "__main__":
    sys.path.append(os.environ['HOME'] + "/install/3pl")
    is_zynq = 'fpga_read_write' in sys.modules
    if is_zynq:
        import fpga as fpga_rw
    else:
        import cpu_serial as fpga_rw
import zlib
from types import ModuleType


global uniq
global debug
global bo
global zynq_part

uniq = 1        # integer to append to generated variables
debug = False   # flag to print generated python module
bo = 'little'   # CPU byte order, littleendian or bigendian
zynq_part = 'xc7z'

template_mask = string.Template(
    textwrap.indent(
        textwrap.dedent(
            '''\
            fval = val & ${m}
            '''), '    '))

template_mask_and_shift = string.Template(
    textwrap.indent(
        textwrap.dedent(
            '''\
            fval = val & ${m}
            val >>= ${b}
            '''), '    '))

template_divide = string.Template(
    textwrap.indent(
        textwrap.dedent(
            '''\
            fval /= (1 << ${s})
            '''), '    '))

template_single = string.Template(
    textwrap.indent(
        textwrap.dedent(
            '''\
            val = ${d} 
            '''), '    '))

template_shift_and_or = string.Template(
    textwrap.indent(
        textwrap.dedent(
            '''\
            val = val | ((${d} & ${m}) << shift)
            shift += ${b}
            '''), '    '))

template_handle_negative = string.Template(
    textwrap.indent(
        textwrap.dedent(
            '''\
            if (fval & ${s}) != 0:
                 fval = -((fval ^ ${m}) + 1)
            '''), '    '))

template_int_to_bool = string.Template(
    textwrap.indent(
        textwrap.dedent(
            '''\
            if fval != 0:
                fval = True
            else:
                fval = False        
            '''), '    '))

template_reg_read_head = string.Template(
    textwrap.dedent(
        '''
        def ${n}_read():
            rba = fpga_rw.comms_read(0, ${a}, 0, ${w})
            val = int.from_bytes(rba, byteorder=${bo}, signed=False)
        '''))

template_null_reg_write = string.Template(
    textwrap.dedent(
        '''
        def ${n}_write():
            wba = bytearray()
            fpga_rw.comms_write(0, ${a}, 0, wba)
        '''))

template_reg_write_head_a = string.Template(
    textwrap.dedent(
        '''
        def ${n}_write(wdata):
        '''))

template_reg_write_head_b = string.Template(
    textwrap.dedent(
        '''
        def ${n}_write(wdata):
            shift = 0
            val = 0
        '''))

template_reg_write_tail = string.Template(
    textwrap.indent(
        textwrap.dedent(
            '''\
                if val < 0:
                    wba = val.to_bytes(${bytes}, byteorder=${bo}, signed=True)
                else:
                    wba = val.to_bytes(${bytes}, byteorder=${bo})
                fpga_rw.comms_write(0, ${a}, 0, wba)
            '''), '    '))

template_queue_avail_read = string.Template(
    textwrap.dedent(
        '''
        def ${n}_read():
            rba = fpga_rw.comms_read(0, ${a}, 0, ${bytes})
            val = int.from_bytes(rba, byteorder=${bo}, signed=False)
            return(val)
        '''))

template_queue_thresh_write_head = string.Template(
    textwrap.dedent(
        '''
        def ${n}_write(wdata):
        '''))

template_queue_thresh_write_tail = string.Template(
    textwrap.indent(
        textwrap.dedent(
            '''\
                wba = val.to_bytes(${bytes}, byteorder=${bo})
                fpga_rw.comms_write(0, ${a}, 0, wba)
            '''), '    '))

template_mem_read_head = string.Template(
    textwrap.dedent(
        '''
        def ${n}_read(memaddr):
            rba = fpga_rw.comms_read(1, ${a}, memaddr, ${bytes})
            val = int.from_bytes(rba, byteorder=${bo}, signed=False)
        '''))

template_mem_write_head_a = string.Template(
    textwrap.dedent(
        '''
        def ${n}_write(wdata, memaddr):
        '''))

template_mem_write_head_b = string.Template(
    textwrap.dedent(
        '''
        def ${n}_write(wdata, memaddr):
            shift = 0
            val = 0
        '''))

template_mem_write_tail = string.Template(
    textwrap.indent(
        textwrap.dedent(
            '''\
                wba = val.to_bytes(${bytes}, byteorder=${bo})
                fpga_rw.comms_write(1, ${a}, memaddr, wba)
            '''), '    '))

template_event_serial = string.Template(
    textwrap.dedent(
        '''
        # event "${n}"
        def ${n}_wait():
            fpga_rw.semaphores[${e}].acquire()
        
        def ${n}_count():
            return(fpga_rw.event_count(${e}))
        '''))

template_event_zynq = string.Template(
    textwrap.dedent(
        '''
        # event "${n}"
        def ${n}_wait():
            fpga_rw.event_wait(${e})
        
        def ${n}_count():
            return(fpga_rw.event_count(${e}))
        '''))



#----------------------------------------------------------------------
# data_unpack()
# The data from the FPGA read is in an integer variable named 'val'
# Emit code to mask out this data field, of type 'dtype',
# from the data integer and remove the data field by
# shifting right. The extracted data is written to 'v'.
#
def data_unpack (dtype, buff, simple):
    global uniq
    t = dtype['type']
    if t == 'log':
        bits = 1
        tokens['b'] = 1
        tokens['m'] = 1
        if not simple:
            buff.write(template_mask_and_shift.substitute(tokens))
        else:
            buff.write(template_mask.substitute(tokens))
        buff.write(template_int_to_bool.substitute(tokens))
        return('fval')
    
    elif t == 'uint' or t == 'bits':
        bits = dtype['bits']
        tokens['b'] = bits
        tokens['m'] = hex(((1 << bits) - 1))
        if not simple:
            buff.write(template_mask_and_shift.substitute(tokens))
        else:
            buff.write(template_mask.substitute(tokens))
        return('fval')

    elif t == 'int':
        bits = dtype['bits']
        tokens['b'] = bits
        tokens['m'] = hex(((1 << bits) - 1))
        tokens['s'] = hex(1 << (bits - 1))
        if not simple:
            buff.write(template_mask_and_shift.substitute(tokens))
        else:
            buff.write(template_mask.substitute(tokens))
        buff.write(template_handle_negative.substitute(tokens))
        return('fval')
    
    elif t == 'ufixed':
        intbits = dtype['int_bits']
        fracbits = dtype['frac_bits']
        bits = intbits + fracbits
        tokens['b'] = bits
        tokens['m'] = hex(((1 << bits) - 1))
        if not simple:
            buff.write(template_mask_and_shift.substitute(tokens))
        else:
            buff.write(template_mask.substitute(tokens))
        tokens['s'] = fracbits
        buff.write(template_divide.substitute(tokens))
        return('fval')

    elif t == 'fixed':
        intbits = dtype['int_bits']
        fracbits = dtype['frac_bits']
        bits = intbits + fracbits
        tokens['b'] = bits
        tokens['m'] = hex(((1 << bits) - 1))
        tokens['s'] = hex(1 << (bits - 1))
#        buff.write('    fval = val\n')
        if not simple:
            buff.write(template_mask_and_shift.substitute(tokens))
        else:
            buff.write(template_mask.substitute(tokens))
        buff.write(template_handle_negative.substitute(tokens))

        tokens['s'] = fracbits
        buff.write(template_divide.substitute(tokens))
        return('fval')
        
    elif t == 'float':
        mantbits = dtype['mant_bits']
        expbits = dtype['exp_bits']
        bits = mantbits + expbits + 1
        tvar = 'v' + str(uniq)
        uniq = uniq + 1
        
        tokens['b'] = mantbits
        tokens['m'] = hex(((1 << mantbits) - 1))
        one = 1 << mantbits
        buff.write(template_mask_and_shift.substitute(tokens))
        buff.write('    mant = fval\n')
        
        tokens['b'] = expbits
        tokens['m'] = hex(((1 << expbits) - 1))
        buff.write(template_mask_and_shift.substitute(tokens))
        buff.write('    exp = fval - 127\n')
        #buff.write('    print("exp = " + hex(exp))\n')
        
        buff.write('    if mant != 0 or exp != 0:\n')      
        buff.write('        mant = mant + ' + str(one) + '\n')
        #buff.write('    print("mant = " + hex(mant))\n')
        
        tokens['b'] = 1
        buff.write(template_mask_and_shift.substitute(tokens))
        buff.write('    if fval == 0:\n')
        buff.write('        sign = 1\n')
        buff.write('    else:\n')
        buff.write('        sign = -1\n')
                
        buff.write('    ' + tvar + ' = sign * mant * 2.0 ** exp / ' + str(one) + '\n')
        
        return(tvar)
    
    elif t == 'array':
        tvar = 'v' + str(uniq)
        uniq = uniq + 1
        buff.write('    ' + tvar + ' = []\n')

        dimension = dtype['dimension']
        array_type = dtype['arraytype']
        for i in range(dimension):
            buff.write('    ' + tvar + '.append(' + data_unpack(array_type, buff, False) + ')\n')

        return(tvar)
    
    elif t == 'struct':
        tvar = 'v' + str(uniq)
        uniq = uniq + 1
        buff.write('    ' + tvar + ' = {}\n')
        for field in dtype['fields']:
            fname = field['name']
            buff.write('    ' + tvar + "['" + fname + "'] = " + data_unpack(field, buff, False) + '\n')
        return(tvar)

#----------------------------------------------------------------------
# data_pack_single()
#
def data_pack_single (wdata, bits, buff):
    tokens['b'] = bits
    tokens['d'] = wdata
    buff.write(template_single.substitute(tokens))

#----------------------------------------------------------------------
# data_pack()
#
def data_pack (wdata, dtype, buff):
    global uniq
    shift = 0
    t = dtype['type']
    if t == 'log':
        bits = 1
        tokens['b'] = 1
        tokens['m'] = 1
        tokens['d'] = wdata
        buff.write(template_shift_and_or.substitute(tokens))
        
        return
        
    elif t == 'uint' or t == 'int' or t == 'bits':
        bits = dtype['bits']
        tokens['b'] = bits
        tokens['m'] = hex(((1 << bits) - 1))
        tokens['d'] = wdata
        buff.write(template_shift_and_or.substitute(tokens))
        
        return
        
    elif t == 'ufixed' or t == 'fixed':
        intbits = dtype['int_bits']
        fracbits = dtype['frac_bits']
        buff.write('    intval =  math.floor(wdata)\n')
        buff.write('    fracval =   math.floor((wdata - intval) * 2 ** ' + str(fracbits) + ')\n')
        
        tokens['b'] = fracbits
        tokens['m'] = hex(((1 << fracbits) - 1))
        tokens['d'] = 'fracval'
        buff.write(template_shift_and_or.substitute(tokens))

        tokens['b'] = intbits
        tokens['m'] = hex(((1 << intbits) - 1))
        tokens['d'] = 'intval'
        buff.write(template_shift_and_or.substitute(tokens))
        
        #buff.write('    print("fix/ufix write val = " + hex(val))\n')
        
        return
        
    elif t == 'float':
        mantbits = dtype['mant_bits']
        expbits = dtype['exp_bits']
        buff.write('    m, e = math.frexp(wdata)\n')
        #buff.write('    print("FFF wdata " + str(wdata))\n')
        #buff.write('    print("FFF m " + str(m))\n')
        #buff.write('    print("FFF e " + str(e))\n')
        buff.write('    if m < 0.0:\n')
        buff.write('        m = -m\n')
        buff.write('        s = 1\n')
        buff.write('    else:\n')
        buff.write('        s = 0\n')
        buff.write('    a = 2 ** ' + str(mantbits+1) + '\n')
        buff.write('    b = a - 2\n')
        buff.write('    m = math.floor(m * a) & b\n')
        buff.write('    c = 2 ** ' + str(expbits-1) + ' - 1\n')
        buff.write('    e = (e - 1) + c\n')
        #buff.write('    print("FFF a " + str(a))\n')
        #buff.write('    print("FFF b " + str(b))\n')
        #buff.write('    print("FFF m " + str(m))\n')
        #buff.write('    print("FFF c " + str(c))\n')
        #buff.write('    print("FFF e " + str(e))\n')
        
        tokens['b'] = mantbits
        tokens['m'] = hex(((1 << mantbits) - 1))
        tokens['d'] = 'm'
        buff.write(template_shift_and_or.substitute(tokens))

        tokens['b'] = expbits
        tokens['m'] = hex(((1 << expbits) - 1))
        tokens['d'] = 'e'
        buff.write(template_shift_and_or.substitute(tokens))

        tokens['b'] = 1
        tokens['m'] = 1
        tokens['d'] = 's'
        buff.write(template_shift_and_or.substitute(tokens))
        
    elif t == 'array':
        tvar = 'v' + str(uniq)
        uniq = uniq + 1
        dimension = dtype['dimension']
        array_type = dtype['arraytype']
        for i in range(dimension):
            buff.write("    " + tvar + " = " + wdata + "[" + str(i) + "]\n")
            data_pack(tvar, array_type, buff)
        
        return
        
    elif t == 'struct':
        tvar = 'v' + str(uniq)
        uniq = uniq + 1
        for field in dtype['fields']:
            fname = field['name']
            buff.write("    " + tvar + " = " + wdata + "['" + fname + "']\n")
            data_pack(tvar, field, buff)

#----------------------------------------------------------------------
# emit()
# Generate the python code determined from the .info file.
#
def emit (info):
    global tokens
    buff = StringIO()

    # set up substitution tokens
    tokens = {
        'd': info['directives']['designName'],
        'i': info['directives']['sourceFile'],
        'z': time.strftime('%a, %d %b %Y %H:%M:%S %z'),
        'c': '',
        'bo': "'" + bo + "'"
    }
    
    directives = info['directives']
    part = directives['part']
    if part[0:4] == zynq_part:
        is_zynq = True
    else:
        is_zynq = False

    # emit header
    #buff.write("import fpga_rw\n")
    buff.write("import os\n")
    buff.write("import math\n")
    if __name__ == "__main__":
        buff.write("import string\n")
        buff.write("import textwrap\n")
        buff.write("import argparse\n")
        buff.write("import json\n")
        buff.write("import sys\n")
        buff.write("import time\n")
        buff.write("sys.path.append(os.environ['HOME'] + '/install/3pl')\n")
    if is_zynq:
        buff.write("import fpga as fpga_rw\n")
    else:
        buff.write("import cpu_serial as fpga_rw\n")

    # compile lists of spaces and addresses for initialisation
    names = []
    spaces = {}
    dma_interfaces = {}

    # emit python code for each interface in each space
    scount = 0
    for sname, space in info['spaces'].items():
        tokens['s'] = sname

        for iname, interface in space['interfaces'].items():
            tokens['n'] = iname

            # omit infoword/inforeset
            if iname == 'infoword' or iname == 'inforeset':
                continue

            bytes = (interface['data_bits'] + 7) // 8
            tokens['a'] = interface['data_addr']
            tokens['w'] = bytes

            ifname = interface['interface']

            names.append(iname)
            if sname == 'reg':
                dtype = interface['data_type']                        
                t = dtype['type']
                if t == 'log' or t == 'bits' or t == 'int' or t == 'uint':
                    simple = True
                else:
                    simple = False
                if t == 'int' or t == 'fixed':
                    signed = True
                else:
                    signed = False
                
                if "port" in interface:
                    if interface['write']:
                        tokens['bytes'] = bytes
                        if simple:
                            buff.write(template_mem_write_head_a.substitute(tokens))
                            data_pack_single('wdata', dtype['bits'], buff)
                        else:
                            buff.write(template_mem_write_head_b.substitute(tokens))
                            data_pack('wdata', dtype, buff)
                        buff.write(template_mem_write_tail.substitute(tokens))
                    else:
                        buff.write(template_mem_read_head.substitute(tokens))
                        rvar = data_unpack(dtype, buff, simple) # result is in 'rvar'
                        buff.write('    return(' + rvar + ')\n')
                else:
                    if interface['write']:
                        if interface['data_bits'] == 0:
                            buff.write(template_null_reg_write.substitute(tokens))
                        else:
                            tokens['bytes'] = bytes
                            if simple:
                                buff.write(template_reg_write_head_a.substitute(tokens))
                            else:
                                buff.write(template_reg_write_head_b.substitute(tokens))
                            if simple:
                                data_pack_single('wdata', dtype['bits'], buff)
                            else:
                                data_pack('wdata', dtype, buff)
                            buff.write(template_reg_write_tail.substitute(tokens))
                    else:
                        buff.write(template_reg_read_head.substitute(tokens))
                        rvar = data_unpack(dtype, buff, simple) # result is in 'rvar'
                        buff.write('    return(' + rvar + ')\n')
                
                if "avail_addr" in interface:
                    tokens['a'] = interface['avail_addr']
                    depth = interface['data_depth']
                    check = interface['check']
                    bytes = 1
                    if not check and depth > 255:
                        bytes = 2
                    tokens['n'] = iname + '_avail'
                    tokens['bytes'] = bytes
                    buff.write(template_queue_avail_read.substitute(tokens))

                if "avail_thresh_addr" in interface:
                    tokens['a'] = interface['avail_thresh_addr']
                    depth = interface['data_depth']
                    bytes = 1
                    bits = 8
                    if depth > 255:
                        bytes = 2
                        bits = 16
                    tokens['n'] = iname + '_avail_thresh'
                    tokens['bytes'] = bytes
                    buff.write(template_queue_thresh_write_head.substitute(tokens))
                    data_pack_single('wdata', bits, buff)
                    buff.write(template_queue_thresh_write_tail.substitute(tokens))

    # emit code for events
    for ename, event in info['events'].items():
        tokens['n'] = ename
        intnum = event['intr']
        tokens['e'] = intnum

        if is_zynq:
            buff.write(template_event_zynq.substitute(tokens))
        else:
            buff.write(template_event_serial.substitute(tokens))
        
    return(buff.getvalue())


#----------------------------------------------------------------------
# Build the JSON structure from the info string.
#
def extract_json (jsonstring):
    try:
        info = json.loads(jsonstring)
    except json.JSONDecodeError as ex:
        print('line ' + str(ex.lineno) + ': ' + ex.msg)
        exit(1)
    
    return info

#----------------------------------------------------------------------
# Parse the json information string, build the information structure,
# traverse it to build interface functions and compile them into a
# module. The interface moduke is returned.
#
def build_info (info):    
    try:
        infostruct = json.loads(info)
    except json.JSONDecodeError as ex:
        print('line ' + str(ex.lineno) + ': ' + ex.msg)
        exit(1)
    
    # construct the interface functions
    src = emit(infostruct)
    if debug:
        print("-----------------------------------------------------------")
        print(src)
        print("-----------------------------------------------------------")
    
    if __name__ != "__main__":
        # compile the interface functions
        global om
        om = compile(src, 'interface', 'exec')
        module = ModuleType("fpgamodule")
        exec(om, module.__dict__)
        return(module)
    else:
        fname = design + "_fpga.py"
        with open(fname, 'w', encoding="utf-8") as f:
            f.write(src)


#----------------------------------------------------------------------
# Read the compressed JSON structure from the FPGA
# and expand it. Return a code module containing the interface
# functions.
#
def info_from_fpga ():
    # reset the json interface
    fpga_rw.comms_write(0, 1, 0, None)

    # get the checksum
    rba = fpga_rw.comms_read(0, 1, 0, 4)
    checksum = int.from_bytes(rba, byteorder=bo, signed=False)

    # get the uncompressed byte count
    rba = fpga_rw.comms_read(0, 1, 0, 4)
    ucl = int.from_bytes(rba, byteorder=bo, signed=False)

    # get the compressed byte count
    rba = fpga_rw.comms_read(0, 1, 0, 4)
    cl = int.from_bytes(rba, byteorder=bo, signed=False)

    # read the compressed json info string
    words = cl // 4 + 1
    rba = bytearray()
    for i in range(words):
        rba += fpga_rw.comms_read(0, 1, 0, 4)

    # decompress the json string
    infostring = zlib.decompress(rba[2:-4], -15)
    
    return(build_info(str(infostring, 'utf-8')))


#----------------------------------------------------------------------
# Read the compressed JSON structure from the bit file
# and expand it. Return a code module containing the interface
# functions.
#
#def info_from_bitfile ():
    # read the bitfile
    
    # decompress if necessary
    # look for gzip compression header in data
    #if (! ((data[0] == 0x1f) && (data[1] == 0x8b))) {
    
    # read the information string length from the end of the file
    
    # seek to the start of the information string
    
    # read the information string

#----------------------------------------------------------------------
# Read the JSON structure from the .info file
# and expand it. Return a code module containing the interface
# functions.
#
def info_from_file (infofile):
    if not infofile.endswith('.info'):
        infofile = infofile + '.info'
    with open(infofile, 'r') as infile:
        infostring = infile.read()
    return(build_info(infostring))



if __name__ == "__main__":
    is_zynq = 'fpga_read_write' in sys.modules
    design = sys.argv[1]
    info_from_file(design)
    sys.exit()
