#! /usr/bin/env python3

import os
import sys

sys.path.append(os.environ['HOME'] + "/install/3pl/lib/python3")
from info2py import info_from_file

prog = os.path.basename(sys.argv[0])
if prog.lower().endswith('.py'):
    prog = prog[:-3]

if len(sys.argv) != 2:
    print('Usage: {} design'.format(prog), file=sys.stderr)
    sys.exit(1)

try:
    design = sys.argv[1]
    info_from_file(design)
    sys.exit(0)
except Exception as e:
    print('Error: exception {}.'.format(e), file=sys.stderr)
    sys.exit(1)
