# THIS FILE IS AUTOMATICALLY GENERATED -- DO NOT EDIT
#
#   Generated from prog.info
#   by info2py 9026 2020-02-06 23:30:55Z dun202
#   on Fri, 08 Apr 2022 14:45:44 +1000

import cpu_serial


def fpga_SW_write(wdata):
    shift = 0
    val = 0
    v1 = wdata['f1']
    val = val | ((v1 & 0x1ff) << shift)
    shift += 9
    v1 = wdata['f2']
    val = val | ((v1 & 0xfff) << shift)
    shift += 12
    v1 = wdata['f3']
    val = val | ((v1 & 1) << shift)
    shift += 1
    v1 = wdata['f4']
    val = val | ((v1 & 0xffff) << shift)
    shift += 16
    wba = val.to_bytes(5, byteorder='little')
    cpu_serial.comms_write(0, 2, 0, wba);

def fpga_SW_write(wdata):
    shift = 0
    val = 0
    v2 = wdata['f1']
    val = val | ((v2 & 0x1ff) << shift)
    shift += 9
    v2 = wdata['f2']
    val = val | ((v2 & 0xfff) << shift)
    shift += 12
    v2 = wdata['f3']
    val = val | ((v2 & 1) << shift)
    shift += 1
    v2 = wdata['f4']
    val = val | ((v2 & 0xffff) << shift)
    shift += 16
    wba = val.to_bytes(5, byteorder='little')
    cpu_serial.comms_write(0, 2, 0, wba);

def fpga_SR_read():
    rba = cpu_serial.comms_read(0, 2, 0);
    val = int.from_bytes(rba, byteorder='little', signed=False)
    v3 = {}
    v = val & 0x1ff
    val >>= 9
    v3['f1'] = v
    v = val & 0xfff
    val >>= 12
    if (v & 0x800) != 0:
        v = -(0x1000 - v)        
    v3['f2'] = v
    v = val & 1
    val >>= 1
    if v != 0:
        v = True
    else:
        v = False        
    v3['f3'] = v
    v = val & 0xffff
    val >>= 16
    v3['f4'] = v
    return(v3)

def fpga_SR_read():
    rba = cpu_serial.comms_read(0, 2, 0);
    val = int.from_bytes(rba, byteorder='little', signed=False)
    v4 = {}
    v = val & 0x1ff
    val >>= 9
    v4['f1'] = v
    v = val & 0xfff
    val >>= 12
    if (v & 0x800) != 0:
        v = -(0x1000 - v)        
    v4['f2'] = v
    v = val & 1
    val >>= 1
    if v != 0:
        v = True
    else:
        v = False        
    v4['f3'] = v
    v = val & 0xffff
    val >>= 16
    v4['f4'] = v
    return(v4)
