# THIS FILE IS AUTOMATICALLY GENERATED -- DO NOT EDIT
#
#   Generated from prog.info
#   by info2py 9026 2020-02-06 23:30:55Z dun202
#   on Mon, 04 Apr 2022 12:02:30 +1000

import cpu_serial


def fpga_STARTW_write(wdata):
    shift = 0
    val = 0
    val = val | ((wdata & 1) << shift)
    shift += 1
    wba = val.to_bytes(1, byteorder='little')
    cpu_serial.comms_write(0, 2, 0, wba);

# event "EV1"
def fpga_EV1_wait():
    cpu_serial.semaphores[0].acquire()

# event "EV2"
def fpga_EV2_wait():
    cpu_serial.semaphores[1].acquire()
