// THIS FILE IS AUTOMATICALLY GENERATED -- DO NOT EDIT
//
//   Generated from prog.info
//   by info2c 9026 2020-02-06 23:30:55Z dun202
//   on Wed, 23 Mar 2022 14:17:57 +1100

#ifndef __fpga__prog_h__
#define __fpga__prog_h__


// interface "STARTW" in space "reg" (bus "serial")
typedef uint8_t fpga_STARTW_t;
const unsigned fpga_STARTW_addr = 2;
static void
fpga_STARTW_write(fpga_STARTW_t val) {
    comms_write(0, fpga_STARTW_addr, 0, 1, (char *)&val);
}

// event "EV1"
void
fpga_EV1_wait() {
    sem_wait(sem[0]);
}

// event "EV2"
void
fpga_EV2_wait() {
    sem_wait(sem[1]);
}

#define INTERRUPTS 2

#endif
