INSTDIR = $(HOME)/install/3pl

install::
	install setup.py $(INSTDIR)
	install mk_setup $(INSTDIR)
	install fpga.c $(INSTDIR)
	install fpga.h $(INSTDIR)
	install fpga_py_extension.c $(INSTDIR)
	install fpga.py $(INSTDIR)

