// THIS FILE IS AUTOMATICALLY GENERATED -- DO NOT EDIT
//
//   Generated from prog.info
//   by info2c 9925 2021-07-09 07:11:13Z dun202
//   on Sat, 23 Jul 2022 21:05:02 +1000

#ifndef __fpga__prog_h__
#define __fpga__prog_h__


// interface "inforeset" in space "reg" (bus "axi_mgp0")
const unsigned fpga_inforeset_addr = 2;
static __inline__ void
fpga_inforeset_write() {
    uint32_t    val = 0;
    FPGA_REG_WRITE(fpga_inforeset_addr, val, 1);
}

// interface "SR" in space "reg" (bus "axi_mgp0")
typedef uint8_t fpga_SR_t;
const unsigned fpga_SR_addr = 2;
static __inline__ fpga_SR_t
fpga_SR_read() {
    FPGA_REG_READ(fpga_SR_addr, fpga_SR_t, 1);
}

// interface "SW" in space "reg" (bus "axi_mgp0")
typedef uint8_t fpga_SW_t;
const unsigned fpga_SW_addr = 4;
static __inline__ void
fpga_SW_write(fpga_SW_t val) {
    FPGA_REG_WRITE(fpga_SW_addr, val, 1);
}

// interface "infoword" in space "reg" (bus "axi_mgp0")
typedef uint32_t fpga_infoword_t;
const unsigned fpga_infoword_addr = 1;
static __inline__ fpga_infoword_t
fpga_infoword_read() {
    FPGA_REG_READ(fpga_infoword_addr, fpga_infoword_t, 1);
}

// space and event bitfield for fpga_map() 2nd argument
#define fpga_map_needed \
    fpga_map_none \
    | fpga_space_reg

#endif
